#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Jun 01, 2020 05:25:45 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 772x621+773+263
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Camara de diputados"
    vTcl:DefineAlias "$top" "window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab44 \
        -font TkDefaultFont -foreground black \
        -text {Cantidad de diputados por provincia} \
        -background $vTcl(actual_gui_bg) -height 135 -width 770 
    vTcl:DefineAlias "$top.lab44" "Labelframe1" vTcl:WidgetProc "window" 1
    set site_3_0 $top.lab44
    label $site_3_0.lab45 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Provincia: 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1" vTcl:WidgetProc "window" 1
    ttk::combobox $site_3_0.tCo46 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo46" "cb_prov" vTcl:WidgetProc "window" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu47 \
        -command calcular1 -takefocus {} -text Calcular 
    vTcl:DefineAlias "$site_3_0.tBu47" "bt_calcular1" vTcl:WidgetProc "window" 1
    label $site_3_0.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Cantidad: 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "window" 1
    label $site_3_0.lab49 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text 0 
    vTcl:DefineAlias "$site_3_0.lab49" "lbl_cantidad1" vTcl:WidgetProc "window" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.039 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.135 -height 0 -relheight 0.127 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo46 \
        -in $site_3_0 -x 0 -relx 0.156 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.186 -height 0 -relheight 0.127 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu47 \
        -in $site_3_0 -x 0 -relx 0.377 -y 0 -rely 0.364 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.61 -y 0 -rely 0.37 -width 0 \
        -relwidth 0.096 -height 0 -relheight 0.126 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.701 -y 0 -rely 0.37 -width 0 \
        -relwidth 0.044 -height 0 -relheight 0.156 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab50 \
        -font TkDefaultFont -foreground black \
        -text {Cantidad de diputados por Bloque Politico} \
        -background $vTcl(actual_gui_bg) -height 125 -width 770 
    vTcl:DefineAlias "$top.lab50" "Labelframe2" vTcl:WidgetProc "window" 1
    set site_3_0 $top.lab50
    label $site_3_0.lab51 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Bloque: 
    vTcl:DefineAlias "$site_3_0.lab51" "Label3" vTcl:WidgetProc "window" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent52" "et_bloque" vTcl:WidgetProc "window" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu54 \
        -command calcular2 -takefocus {} -text Calcular 
    vTcl:DefineAlias "$site_3_0.tBu54" "bt_calcular2" vTcl:WidgetProc "window" 1
    label $site_3_0.lab55 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Hombres: 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4" vTcl:WidgetProc "window" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Mujeres: 
    vTcl:DefineAlias "$site_3_0.lab56" "Label4_2" vTcl:WidgetProc "window" 1
    label $site_3_0.lab57 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text 0 
    vTcl:DefineAlias "$site_3_0.lab57" "lbl_hombres" vTcl:WidgetProc "window" 1
    label $site_3_0.lab58 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text 0 
    vTcl:DefineAlias "$site_3_0.lab58" "lbl_mujeres" vTcl:WidgetProc "window" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.039 -y 0 -rely 0.32 -width 0 \
        -relwidth 0.07 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 0 -relx 0.117 -y 0 -rely 0.32 -width 124 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu54 \
        -in $site_3_0 -x 0 -relx 0.338 -y 0 -rely 0.32 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.61 -y 0 -rely 0.24 -width 0 \
        -relwidth 0.083 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.61 -y 0 -rely 0.56 -width 0 \
        -relwidth 0.083 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.74 -y 0 -rely 0.24 -width 0 \
        -relwidth 0.044 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.74 -y 0 -rely 0.56 -width 0 \
        -relwidth 0.044 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab59 \
        -font TkDefaultFont -foreground black -text {Cantidad de Viajes} \
        -background $vTcl(actual_gui_bg) -height 145 -width 770 
    vTcl:DefineAlias "$top.lab59" "Labelframe3" vTcl:WidgetProc "window" 1
    set site_3_0 $top.lab59
    label $site_3_0.lab60 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Origen: 
    vTcl:DefineAlias "$site_3_0.lab60" "Label5" vTcl:WidgetProc "window" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Destino: 
    vTcl:DefineAlias "$site_3_0.lab61" "Label5_3" vTcl:WidgetProc "window" 1
    entry $site_3_0.ent62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 114 
    vTcl:DefineAlias "$site_3_0.ent62" "et_origen" vTcl:WidgetProc "window" 1
    entry $site_3_0.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 114 
    vTcl:DefineAlias "$site_3_0.ent63" "et_destino" vTcl:WidgetProc "window" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu64 \
        -command calcular3 -takefocus {} -text Calcular 
    vTcl:DefineAlias "$site_3_0.tBu64" "bt_calcular3" vTcl:WidgetProc "window" 1
    label $site_3_0.lab65 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cantidad: } 
    vTcl:DefineAlias "$site_3_0.lab65" "Label6" vTcl:WidgetProc "window" 1
    label $site_3_0.lab66 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text 0 
    vTcl:DefineAlias "$site_3_0.lab66" "lbl_cantidad2" vTcl:WidgetProc "window" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.065 -y 0 -rely 0.276 -width 0 \
        -relwidth 0.07 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.065 -y 0 -rely 0.621 -width 0 \
        -relwidth 0.07 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.276 -width 114 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.621 -width 114 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu64 \
        -in $site_3_0 -x 0 -relx 0.416 -y 0 -rely 0.483 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.584 -y 0 -rely 0.483 -width 0 \
        -relwidth 0.096 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.688 -y 0 -rely 0.483 -width 0 \
        -relwidth 0.044 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab67 \
        -font TkDefaultFont -foreground black -text {Buscador de diputados} \
        -background $vTcl(actual_gui_bg) -height 235 -width 770 
    vTcl:DefineAlias "$top.lab67" "Labelframe4" vTcl:WidgetProc "window" 1
    set site_3_0 $top.lab67
    label $site_3_0.lab68 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Diputado ID:} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label7" vTcl:WidgetProc "window" 1
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Nombre Completo:} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label7_4" vTcl:WidgetProc "window" 1
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_3_0.lab70" "Label7_5" vTcl:WidgetProc "window" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Cantidad de Viajes:} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label7_5" vTcl:WidgetProc "window" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Bloque: 
    vTcl:DefineAlias "$site_3_0.lab72" "Label7_5" vTcl:WidgetProc "window" 1
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Año Inicio:} 
    vTcl:DefineAlias "$site_3_0.lab73" "Label7_5" vTcl:WidgetProc "window" 1
    label $site_3_0.lab74 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text { } 
    vTcl:DefineAlias "$site_3_0.lab74" "lbl_nombre" vTcl:WidgetProc "window" 1
    label $site_3_0.lab75 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text { } 
    vTcl:DefineAlias "$site_3_0.lab75" "lbl_provincia" vTcl:WidgetProc "window" 1
    label $site_3_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text { } 
    vTcl:DefineAlias "$site_3_0.lab76" "lbl_cantidad" vTcl:WidgetProc "window" 1
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text { } 
    vTcl:DefineAlias "$site_3_0.lab77" "lbl_bloque" vTcl:WidgetProc "window" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text { } 
    vTcl:DefineAlias "$site_3_0.lab78" "lbl_inicio" vTcl:WidgetProc "window" 1
    entry $site_3_0.ent79 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent79" "et_id" vTcl:WidgetProc "window" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu80 \
        -command buscar -takefocus {} -text Buscar 
    vTcl:DefineAlias "$site_3_0.tBu80" "bt_buscar" vTcl:WidgetProc "window" 1
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.078 -y 0 -rely 0.17 -width 0 \
        -relwidth 0.122 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.34 -width 0 \
        -relwidth 0.148 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.091 -y 0 -rely 0.511 -width 0 \
        -relwidth 0.096 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.065 -y 0 -rely 0.681 -width 0 \
        -relwidth 0.148 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.506 -y 0 -rely 0.298 -width 0 \
        -relwidth 0.148 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.506 -y 0 -rely 0.511 -width 0 \
        -relwidth 0.148 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx 0.234 -y 0 -rely 0.34 -width 0 \
        -relwidth 0.304 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 0 -relx 0.234 -y 0 -rely 0.511 -width 0 \
        -relwidth 0.291 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 0 -relx 0.234 -y 0 -rely 0.681 -width 0 \
        -relwidth 0.304 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.623 -y 0 -rely 0.298 -width 0 \
        -relwidth 0.304 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 0 -relx 0.623 -y 0 -rely 0.511 -width 0 \
        -relwidth 0.148 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent79 \
        -in $site_3_0 -x 0 -relx 0.247 -y 0 -rely 0.17 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu80 \
        -in $site_3_0 -x 0 -relx 0.429 -y 0 -rely 0.17 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.997 -height 0 \
        -relheight 0.217 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -y 0 -rely 0.209 -width 0 -relwidth 0.997 -height 0 \
        -relheight 0.201 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -y 0 -rely 0.403 -width 0 -relwidth 0.997 -height 0 \
        -relheight 0.233 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -y 0 -rely 0.628 -width 0 -relwidth 0.997 -height 0 \
        -relheight 0.378 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

