#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 05:02:12 PM -03  platform: Windows NT

import sys
import abm

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    w.cb_prov['values'] = abm.listaProvincias()

def buscar():
    idIng = w.et_id.get()
    lista = abm.buscadorDiputados(idIng)
    w.lbl_nombre.config(text=lista[0])
    w.lbl_provincia.config(text=lista[1])
    w.lbl_cantidad.config(text=lista[4])
    w.lbl_bloque.config(text=lista[2])
    w.lbl_inicio.config(text=lista[3])

def calcular1():
    prov = w.cb_prov.get()
    w.lbl_cantidad1.config(text=abm.diputadosPorProv(prov))

def calcular2():
    bloque = w.et_bloque.get()
    abm.diputadosBloqueGenero(bloque,"M")
    w.lbl_hombres.config(text=abm.diputadosBloqueGenero(bloque,"M"))
    w.lbl_mujeres.config(text=abm.diputadosBloqueGenero(bloque,"F"))

def calcular3():
    origen = w.et_origen.get()
    destino = w.et_destino.get()
    cantidad = abm.viajesPorOrigenYDestino(origen,destino)
    w.lbl_cantidad2.config(text=cantidad)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import main
    main.vp_start_gui()




