#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 04:21:21 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import json
with open("covid19.json", encoding = 'utf-8') as archivo:
    listaCasos = json.load(archivo)

def set_Tk_var():
    global confirmadosArg
    confirmadosArg = tk.StringVar()
    global FallecidosArg
    FallecidosArg = tk.StringVar()
    global RecuperadosArg
    RecuperadosArg = tk.StringVar()
    global confirmadosPa
    confirmadosPa = tk.StringVar()
    global FallecidosPa
    FallecidosPa = tk.StringVar()
    global RecuperadosPa
    RecuperadosPa = tk.StringVar()
    global confirmadosUr
    confirmadosUr = tk.StringVar()
    global FallecidosUr
    FallecidosUr = tk.StringVar()
    global RecuperadosUr
    RecuperadosUr = tk.StringVar()
    global confirmadosBr
    confirmadosBr = tk.StringVar()
    global FallecidosBr
    FallecidosBr = tk.StringVar()
    global RecuperadosBr
    RecuperadosBr = tk.StringVar()
    global paisMasR
    paisMasR = tk.StringVar()
    global cantidadMasR
    cantidadMasR = tk.StringVar()
    global confirmadosBuscador
    confirmadosBuscador = tk.StringVar()
    global fallecidosBuscador
    fallecidosBuscador = tk.StringVar()
    global Recuperados_buscador
    Recuperados_buscador = tk.StringVar()

def CconfirmadosArg():
    cantidadArg = 0
    CfallecidosArg = 0
    CrecuperadosArg = 0
    for caso in listaCasos:
        if caso["pais"] == "Argentina":
            cantidadArg = int(caso["confirmados"])
            CfallecidosArg = int(caso["muertos"])
            CrecuperadosArg = int(caso["recuperados"])
    confirmadosArg.set(cantidadArg)
    FallecidosArg.set(CfallecidosArg)
    RecuperadosArg.set(CrecuperadosArg)

def CconfirmadosPa():
    cantidadPa = 0
    CfallecidosPa = 0
    CrecuperadosPa = 0
    for caso in listaCasos:
        if caso["pais"] == "Paraguay":
            cantidadPa = int(caso["confirmados"])
            CfallecidosPa = int(caso["muertos"])
            CrecuperadosPa = int(caso["recuperados"])
    confirmadosPa.set(cantidadPa)
    FallecidosPa.set(CfallecidosPa)
    RecuperadosPa.set(CrecuperadosPa)

def CconfirmadosUr():
    cantidadUr = 0
    CfallecidosUr = 0
    CrecuperadosUr = 0
    for caso in listaCasos:
        if caso["pais"] == "Uruguay":
            cantidadUr = int(caso["confirmados"])
            CfallecidosUr = int(caso["muertos"])
            CrecuperadosUr = int(caso["recuperados"])
    confirmadosUr.set(cantidadUr)
    FallecidosUr.set(CfallecidosUr)
    RecuperadosUr.set(CrecuperadosUr)

def CconfirmadosBr():
    cantidadBr = 0
    CfallecidosBr = 0
    CrecuperadosBr = 0
    for caso in listaCasos:
        if caso["pais"] == "Brazil":
            cantidadBr = int(caso["confirmados"])
            CfallecidosBr = int(caso["muertos"])
            CrecuperadosBr = int(caso["recuperados"])
    confirmadosBr.set(cantidadBr)
    FallecidosBr.set(CfallecidosBr)
    RecuperadosBr.set(CrecuperadosBr)


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    CconfirmadosArg()
    CconfirmadosPa()
    CconfirmadosUr()
    CconfirmadosBr()

def buscar_buscador():
    global w
    pais = w.txtPais_buscador.get()
    dia = str(w.txtDia_buscador.get())
    for caso in listaCasos:
        if pais == caso["pais"] and dia == caso["dia"]:
            confirmadosBuscador.set(caso["confirmados"])
            fallecidosBuscador.set(caso["muertos"])
            Recuperados_buscador.set(caso["recuperados"])

def buscar_mas_recuperado():
    masRecuperado = 0
    for caso in listaCasos:
        if int(caso["recuperados"]) > masRecuperado:
            masRecuperado = int(caso["recuperados"])
            paisMR = caso["pais"]
    cantidadMasR.set(masRecuperado)
    paisMasR.set(paisMR)
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import coronavirus
    coronavirus.vp_start_gui()




