#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 04:21:15 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import coronavirus_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    coronavirus_support.set_Tk_var()
    top = Toplevel1 (root)
    coronavirus_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    coronavirus_support.set_Tk_var()
    top = Toplevel1 (w)
    coronavirus_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1094x629+437+209")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.lblTitulo = tk.Label(top)
        self.lblTitulo.place(relx=-0.024, rely=0.06, height=36, width=515)
        self.lblTitulo.configure(background="#d9d9d9")
        self.lblTitulo.configure(disabledforeground="#a3a3a3")
        self.lblTitulo.configure(foreground="#000000")
        self.lblTitulo.configure(text='''Visualización de Información por paises:''')

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.027, rely=0.159, relheight=0.288
                , relwidth=0.229)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(background="#d9d9d9")

        self.lblArg = tk.Label(self.Labelframe1)
        self.lblArg.place(relx=0.268, rely=0.066, height=33, width=104
                , bordermode='ignore')
        self.lblArg.configure(background="#d9d9d9")
        self.lblArg.configure(disabledforeground="#a3a3a3")
        self.lblArg.configure(foreground="#000000")
        self.lblArg.configure(text='''Argentina''')

        self.Label1 = tk.Label(self.Labelframe1)
        self.Label1.place(relx=0.12, rely=0.276, height=26, width=102
                , bordermode='ignore')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Confirmados:''')

        self.Label1_10 = tk.Label(self.Labelframe1)
        self.Label1_10.place(relx=0.12, rely=0.497, height=26, width=92
                , bordermode='ignore')
        self.Label1_10.configure(activebackground="#f9f9f9")
        self.Label1_10.configure(activeforeground="black")
        self.Label1_10.configure(background="#d9d9d9")
        self.Label1_10.configure(disabledforeground="#a3a3a3")
        self.Label1_10.configure(foreground="#000000")
        self.Label1_10.configure(highlightbackground="#d9d9d9")
        self.Label1_10.configure(highlightcolor="black")
        self.Label1_10.configure(text='''Fallecidos:''')

        self.Label1_11 = tk.Label(self.Labelframe1)
        self.Label1_11.place(relx=0.12, rely=0.718, height=26, width=112
                , bordermode='ignore')
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(activeforeground="black")
        self.Label1_11.configure(background="#d9d9d9")
        self.Label1_11.configure(disabledforeground="#a3a3a3")
        self.Label1_11.configure(foreground="#000000")
        self.Label1_11.configure(highlightbackground="#d9d9d9")
        self.Label1_11.configure(highlightcolor="black")
        self.Label1_11.configure(text='''Recuperados:''')

        self.txt_ConfirmadosArg = tk.Entry(self.Labelframe1)
        self.txt_ConfirmadosArg.place(relx=0.6, rely=0.276, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txt_ConfirmadosArg.configure(background="white")
        self.txt_ConfirmadosArg.configure(disabledforeground="#a3a3a3")
        self.txt_ConfirmadosArg.configure(font="TkFixedFont")
        self.txt_ConfirmadosArg.configure(foreground="#000000")
        self.txt_ConfirmadosArg.configure(insertbackground="black")
        self.txt_ConfirmadosArg.configure(state='readonly')
        self.txt_ConfirmadosArg.configure(textvariable=coronavirus_support.confirmadosArg)

        self.txtFallecidosArg = tk.Entry(self.Labelframe1)
        self.txtFallecidosArg.place(relx=0.6, rely=0.497, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txtFallecidosArg.configure(background="white")
        self.txtFallecidosArg.configure(disabledforeground="#a3a3a3")
        self.txtFallecidosArg.configure(font="TkFixedFont")
        self.txtFallecidosArg.configure(foreground="#000000")
        self.txtFallecidosArg.configure(highlightbackground="#d9d9d9")
        self.txtFallecidosArg.configure(highlightcolor="black")
        self.txtFallecidosArg.configure(insertbackground="black")
        self.txtFallecidosArg.configure(selectbackground="#c4c4c4")
        self.txtFallecidosArg.configure(selectforeground="black")
        self.txtFallecidosArg.configure(state='readonly')
        self.txtFallecidosArg.configure(textvariable=coronavirus_support.FallecidosArg)

        self.txtRecuperadosArg = tk.Entry(self.Labelframe1)
        self.txtRecuperadosArg.place(relx=0.6, rely=0.718, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txtRecuperadosArg.configure(background="white")
        self.txtRecuperadosArg.configure(disabledforeground="#a3a3a3")
        self.txtRecuperadosArg.configure(font="TkFixedFont")
        self.txtRecuperadosArg.configure(foreground="#000000")
        self.txtRecuperadosArg.configure(highlightbackground="#d9d9d9")
        self.txtRecuperadosArg.configure(highlightcolor="black")
        self.txtRecuperadosArg.configure(insertbackground="black")
        self.txtRecuperadosArg.configure(selectbackground="#c4c4c4")
        self.txtRecuperadosArg.configure(selectforeground="black")
        self.txtRecuperadosArg.configure(state='readonly')
        self.txtRecuperadosArg.configure(textvariable=coronavirus_support.RecuperadosArg)

        self.Labelframe1_15 = tk.LabelFrame(top)
        self.Labelframe1_15.place(relx=0.265, rely=0.159, relheight=0.288
                , relwidth=0.229)
        self.Labelframe1_15.configure(relief='groove')
        self.Labelframe1_15.configure(foreground="black")
        self.Labelframe1_15.configure(background="#d9d9d9")
        self.Labelframe1_15.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_15.configure(highlightcolor="black")

        self.lblArg_16 = tk.Label(self.Labelframe1_15)
        self.lblArg_16.place(relx=0.268, rely=0.066, height=33, width=104
                , bordermode='ignore')
        self.lblArg_16.configure(activebackground="#f9f9f9")
        self.lblArg_16.configure(activeforeground="black")
        self.lblArg_16.configure(background="#d9d9d9")
        self.lblArg_16.configure(disabledforeground="#a3a3a3")
        self.lblArg_16.configure(foreground="#000000")
        self.lblArg_16.configure(highlightbackground="#d9d9d9")
        self.lblArg_16.configure(highlightcolor="black")
        self.lblArg_16.configure(text='''Paraguay''')

        self.Label1_17 = tk.Label(self.Labelframe1_15)
        self.Label1_17.place(relx=0.12, rely=0.276, height=26, width=102
                , bordermode='ignore')
        self.Label1_17.configure(activebackground="#f9f9f9")
        self.Label1_17.configure(activeforeground="black")
        self.Label1_17.configure(background="#d9d9d9")
        self.Label1_17.configure(disabledforeground="#a3a3a3")
        self.Label1_17.configure(foreground="#000000")
        self.Label1_17.configure(highlightbackground="#d9d9d9")
        self.Label1_17.configure(highlightcolor="black")
        self.Label1_17.configure(text='''Confirmados:''')

        self.Label1_11 = tk.Label(self.Labelframe1_15)
        self.Label1_11.place(relx=0.12, rely=0.497, height=26, width=92
                , bordermode='ignore')
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(activeforeground="black")
        self.Label1_11.configure(background="#d9d9d9")
        self.Label1_11.configure(disabledforeground="#a3a3a3")
        self.Label1_11.configure(foreground="#000000")
        self.Label1_11.configure(highlightbackground="#d9d9d9")
        self.Label1_11.configure(highlightcolor="black")
        self.Label1_11.configure(text='''Fallecidos:''')

        self.Label1_12 = tk.Label(self.Labelframe1_15)
        self.Label1_12.place(relx=0.12, rely=0.718, height=26, width=112
                , bordermode='ignore')
        self.Label1_12.configure(activebackground="#f9f9f9")
        self.Label1_12.configure(activeforeground="black")
        self.Label1_12.configure(background="#d9d9d9")
        self.Label1_12.configure(disabledforeground="#a3a3a3")
        self.Label1_12.configure(foreground="#000000")
        self.Label1_12.configure(highlightbackground="#d9d9d9")
        self.Label1_12.configure(highlightcolor="black")
        self.Label1_12.configure(text='''Recuperados:''')

        self.txt_ConfirmadosPar = tk.Entry(self.Labelframe1_15)
        self.txt_ConfirmadosPar.place(relx=0.6, rely=0.276, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txt_ConfirmadosPar.configure(background="white")
        self.txt_ConfirmadosPar.configure(disabledforeground="#a3a3a3")
        self.txt_ConfirmadosPar.configure(font="TkFixedFont")
        self.txt_ConfirmadosPar.configure(foreground="#000000")
        self.txt_ConfirmadosPar.configure(highlightbackground="#d9d9d9")
        self.txt_ConfirmadosPar.configure(highlightcolor="black")
        self.txt_ConfirmadosPar.configure(insertbackground="black")
        self.txt_ConfirmadosPar.configure(selectbackground="#c4c4c4")
        self.txt_ConfirmadosPar.configure(selectforeground="black")
        self.txt_ConfirmadosPar.configure(state='readonly')
        self.txt_ConfirmadosPar.configure(textvariable=coronavirus_support.confirmadosPa)

        self.txtFallecidosPa = tk.Entry(self.Labelframe1_15)
        self.txtFallecidosPa.place(relx=0.6, rely=0.497, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txtFallecidosPa.configure(background="white")
        self.txtFallecidosPa.configure(disabledforeground="#a3a3a3")
        self.txtFallecidosPa.configure(font="TkFixedFont")
        self.txtFallecidosPa.configure(foreground="#000000")
        self.txtFallecidosPa.configure(highlightbackground="#d9d9d9")
        self.txtFallecidosPa.configure(highlightcolor="black")
        self.txtFallecidosPa.configure(insertbackground="black")
        self.txtFallecidosPa.configure(selectbackground="#c4c4c4")
        self.txtFallecidosPa.configure(selectforeground="black")
        self.txtFallecidosPa.configure(state='readonly')
        self.txtFallecidosPa.configure(textvariable=coronavirus_support.FallecidosPa)

        self.txtRecuperadosPa = tk.Entry(self.Labelframe1_15)
        self.txtRecuperadosPa.place(relx=0.6, rely=0.718, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txtRecuperadosPa.configure(background="white")
        self.txtRecuperadosPa.configure(disabledforeground="#a3a3a3")
        self.txtRecuperadosPa.configure(font="TkFixedFont")
        self.txtRecuperadosPa.configure(foreground="#000000")
        self.txtRecuperadosPa.configure(highlightbackground="#d9d9d9")
        self.txtRecuperadosPa.configure(highlightcolor="black")
        self.txtRecuperadosPa.configure(insertbackground="black")
        self.txtRecuperadosPa.configure(selectbackground="#c4c4c4")
        self.txtRecuperadosPa.configure(selectforeground="black")
        self.txtRecuperadosPa.configure(state='readonly')
        self.txtRecuperadosPa.configure(textvariable=coronavirus_support.RecuperadosPa)

        self.Labelframe1_17 = tk.LabelFrame(top)
        self.Labelframe1_17.place(relx=0.503, rely=0.159, relheight=0.288
                , relwidth=0.229)
        self.Labelframe1_17.configure(relief='groove')
        self.Labelframe1_17.configure(foreground="black")
        self.Labelframe1_17.configure(background="#d9d9d9")
        self.Labelframe1_17.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_17.configure(highlightcolor="black")

        self.lblArg_18 = tk.Label(self.Labelframe1_17)
        self.lblArg_18.place(relx=0.271, rely=0.066, height=33, width=103
                , bordermode='ignore')
        self.lblArg_18.configure(activebackground="#f9f9f9")
        self.lblArg_18.configure(activeforeground="black")
        self.lblArg_18.configure(background="#d9d9d9")
        self.lblArg_18.configure(disabledforeground="#a3a3a3")
        self.lblArg_18.configure(foreground="#000000")
        self.lblArg_18.configure(highlightbackground="#d9d9d9")
        self.lblArg_18.configure(highlightcolor="black")
        self.lblArg_18.configure(text='''Uruguay''')

        self.Label1_19 = tk.Label(self.Labelframe1_17)
        self.Label1_19.place(relx=0.12, rely=0.276, height=26, width=103
                , bordermode='ignore')
        self.Label1_19.configure(activebackground="#f9f9f9")
        self.Label1_19.configure(activeforeground="black")
        self.Label1_19.configure(background="#d9d9d9")
        self.Label1_19.configure(disabledforeground="#a3a3a3")
        self.Label1_19.configure(foreground="#000000")
        self.Label1_19.configure(highlightbackground="#d9d9d9")
        self.Label1_19.configure(highlightcolor="black")
        self.Label1_19.configure(text='''Confirmados:''')

        self.Label1_11 = tk.Label(self.Labelframe1_17)
        self.Label1_11.place(relx=0.12, rely=0.497, height=26, width=92
                , bordermode='ignore')
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(activeforeground="black")
        self.Label1_11.configure(background="#d9d9d9")
        self.Label1_11.configure(disabledforeground="#a3a3a3")
        self.Label1_11.configure(foreground="#000000")
        self.Label1_11.configure(highlightbackground="#d9d9d9")
        self.Label1_11.configure(highlightcolor="black")
        self.Label1_11.configure(text='''Fallecidos:''')

        self.Label1_12 = tk.Label(self.Labelframe1_17)
        self.Label1_12.place(relx=0.12, rely=0.718, height=26, width=113
                , bordermode='ignore')
        self.Label1_12.configure(activebackground="#f9f9f9")
        self.Label1_12.configure(activeforeground="black")
        self.Label1_12.configure(background="#d9d9d9")
        self.Label1_12.configure(disabledforeground="#a3a3a3")
        self.Label1_12.configure(foreground="#000000")
        self.Label1_12.configure(highlightbackground="#d9d9d9")
        self.Label1_12.configure(highlightcolor="black")
        self.Label1_12.configure(text='''Recuperados:''')

        self.txt_ConfirmadosUr = tk.Entry(self.Labelframe1_17)
        self.txt_ConfirmadosUr.place(relx=0.602, rely=0.276, height=24
                , relwidth=0.295, bordermode='ignore')
        self.txt_ConfirmadosUr.configure(background="white")
        self.txt_ConfirmadosUr.configure(disabledforeground="#a3a3a3")
        self.txt_ConfirmadosUr.configure(font="TkFixedFont")
        self.txt_ConfirmadosUr.configure(foreground="#000000")
        self.txt_ConfirmadosUr.configure(highlightbackground="#d9d9d9")
        self.txt_ConfirmadosUr.configure(highlightcolor="black")
        self.txt_ConfirmadosUr.configure(insertbackground="black")
        self.txt_ConfirmadosUr.configure(selectbackground="#c4c4c4")
        self.txt_ConfirmadosUr.configure(selectforeground="black")
        self.txt_ConfirmadosUr.configure(state='readonly')
        self.txt_ConfirmadosUr.configure(textvariable=coronavirus_support.confirmadosUr)

        self.txtFallecidosUr = tk.Entry(self.Labelframe1_17)
        self.txtFallecidosUr.place(relx=0.602, rely=0.497, height=24
                , relwidth=0.295, bordermode='ignore')
        self.txtFallecidosUr.configure(background="white")
        self.txtFallecidosUr.configure(disabledforeground="#a3a3a3")
        self.txtFallecidosUr.configure(font="TkFixedFont")
        self.txtFallecidosUr.configure(foreground="#000000")
        self.txtFallecidosUr.configure(highlightbackground="#d9d9d9")
        self.txtFallecidosUr.configure(highlightcolor="black")
        self.txtFallecidosUr.configure(insertbackground="black")
        self.txtFallecidosUr.configure(selectbackground="#c4c4c4")
        self.txtFallecidosUr.configure(selectforeground="black")
        self.txtFallecidosUr.configure(state='readonly')
        self.txtFallecidosUr.configure(textvariable=coronavirus_support.FallecidosUr)

        self.txtRecuperadosUr = tk.Entry(self.Labelframe1_17)
        self.txtRecuperadosUr.place(relx=0.602, rely=0.718, height=24
                , relwidth=0.295, bordermode='ignore')
        self.txtRecuperadosUr.configure(background="white")
        self.txtRecuperadosUr.configure(disabledforeground="#a3a3a3")
        self.txtRecuperadosUr.configure(font="TkFixedFont")
        self.txtRecuperadosUr.configure(foreground="#000000")
        self.txtRecuperadosUr.configure(highlightbackground="#d9d9d9")
        self.txtRecuperadosUr.configure(highlightcolor="black")
        self.txtRecuperadosUr.configure(insertbackground="black")
        self.txtRecuperadosUr.configure(selectbackground="#c4c4c4")
        self.txtRecuperadosUr.configure(selectforeground="black")
        self.txtRecuperadosUr.configure(state='readonly')
        self.txtRecuperadosUr.configure(textvariable=coronavirus_support.RecuperadosUr)

        self.Labelframe1_15 = tk.LabelFrame(self.Labelframe1_17)
        self.Labelframe1_15.place(relx=1.518, rely=1.061, relheight=1.0
                , relwidth=1.0, bordermode='ignore')
        self.Labelframe1_15.configure(relief='groove')
        self.Labelframe1_15.configure(foreground="black")
        self.Labelframe1_15.configure(background="#d9d9d9")
        self.Labelframe1_15.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_15.configure(highlightcolor="black")

        self.lblArg_16 = tk.Label(self.Labelframe1_15)
        self.lblArg_16.place(relx=0.271, rely=0.066, height=33, width=103
                , bordermode='ignore')
        self.lblArg_16.configure(activebackground="#f9f9f9")
        self.lblArg_16.configure(activeforeground="black")
        self.lblArg_16.configure(background="#d9d9d9")
        self.lblArg_16.configure(disabledforeground="#a3a3a3")
        self.lblArg_16.configure(foreground="#000000")
        self.lblArg_16.configure(highlightbackground="#d9d9d9")
        self.lblArg_16.configure(highlightcolor="black")
        self.lblArg_16.configure(text='''Argentina''')

        self.Label1_17 = tk.Label(self.Labelframe1_15)
        self.Label1_17.place(relx=0.12, rely=0.276, height=26, width=103
                , bordermode='ignore')
        self.Label1_17.configure(activebackground="#f9f9f9")
        self.Label1_17.configure(activeforeground="black")
        self.Label1_17.configure(background="#d9d9d9")
        self.Label1_17.configure(disabledforeground="#a3a3a3")
        self.Label1_17.configure(foreground="#000000")
        self.Label1_17.configure(highlightbackground="#d9d9d9")
        self.Label1_17.configure(highlightcolor="black")
        self.Label1_17.configure(text='''Confirmados:''')

        self.Label1_12 = tk.Label(self.Labelframe1_15)
        self.Label1_12.place(relx=0.12, rely=0.497, height=26, width=92
                , bordermode='ignore')
        self.Label1_12.configure(activebackground="#f9f9f9")
        self.Label1_12.configure(activeforeground="black")
        self.Label1_12.configure(background="#d9d9d9")
        self.Label1_12.configure(disabledforeground="#a3a3a3")
        self.Label1_12.configure(foreground="#000000")
        self.Label1_12.configure(highlightbackground="#d9d9d9")
        self.Label1_12.configure(highlightcolor="black")
        self.Label1_12.configure(text='''Fallecidos:''')

        self.Label1_13 = tk.Label(self.Labelframe1_15)
        self.Label1_13.place(relx=0.12, rely=0.718, height=26, width=113
                , bordermode='ignore')
        self.Label1_13.configure(activebackground="#f9f9f9")
        self.Label1_13.configure(activeforeground="black")
        self.Label1_13.configure(background="#d9d9d9")
        self.Label1_13.configure(disabledforeground="#a3a3a3")
        self.Label1_13.configure(foreground="#000000")
        self.Label1_13.configure(highlightbackground="#d9d9d9")
        self.Label1_13.configure(highlightcolor="black")
        self.Label1_13.configure(text='''Recuperados:''')

        self.Entry1_14 = tk.Entry(self.Labelframe1_15)
        self.Entry1_14.place(relx=0.602, rely=0.276, height=24, relwidth=0.295
                , bordermode='ignore')
        self.Entry1_14.configure(background="white")
        self.Entry1_14.configure(disabledforeground="#a3a3a3")
        self.Entry1_14.configure(font="TkFixedFont")
        self.Entry1_14.configure(foreground="#000000")
        self.Entry1_14.configure(highlightbackground="#d9d9d9")
        self.Entry1_14.configure(highlightcolor="black")
        self.Entry1_14.configure(insertbackground="black")
        self.Entry1_14.configure(selectbackground="#c4c4c4")
        self.Entry1_14.configure(selectforeground="black")

        self.Entry1_14 = tk.Entry(self.Labelframe1_15)
        self.Entry1_14.place(relx=0.602, rely=0.497, height=24, relwidth=0.295
                , bordermode='ignore')
        self.Entry1_14.configure(background="white")
        self.Entry1_14.configure(disabledforeground="#a3a3a3")
        self.Entry1_14.configure(font="TkFixedFont")
        self.Entry1_14.configure(foreground="#000000")
        self.Entry1_14.configure(highlightbackground="#d9d9d9")
        self.Entry1_14.configure(highlightcolor="black")
        self.Entry1_14.configure(insertbackground="black")
        self.Entry1_14.configure(selectbackground="#c4c4c4")
        self.Entry1_14.configure(selectforeground="black")

        self.Entry1_15 = tk.Entry(self.Labelframe1_15)
        self.Entry1_15.place(relx=0.602, rely=0.718, height=24, relwidth=0.295
                , bordermode='ignore')
        self.Entry1_15.configure(background="white")
        self.Entry1_15.configure(disabledforeground="#a3a3a3")
        self.Entry1_15.configure(font="TkFixedFont")
        self.Entry1_15.configure(foreground="#000000")
        self.Entry1_15.configure(highlightbackground="#d9d9d9")
        self.Entry1_15.configure(highlightcolor="black")
        self.Entry1_15.configure(insertbackground="black")
        self.Entry1_15.configure(selectbackground="#c4c4c4")
        self.Entry1_15.configure(selectforeground="black")

        self.Labelframe1_16 = tk.LabelFrame(top)
        self.Labelframe1_16.place(relx=0.74, rely=0.159, relheight=0.288
                , relwidth=0.229)
        self.Labelframe1_16.configure(relief='groove')
        self.Labelframe1_16.configure(foreground="black")
        self.Labelframe1_16.configure(background="#d9d9d9")
        self.Labelframe1_16.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_16.configure(highlightcolor="black")

        self.lblArg_17 = tk.Label(self.Labelframe1_16)
        self.lblArg_17.place(relx=0.268, rely=0.066, height=33, width=104
                , bordermode='ignore')
        self.lblArg_17.configure(activebackground="#f9f9f9")
        self.lblArg_17.configure(activeforeground="black")
        self.lblArg_17.configure(background="#d9d9d9")
        self.lblArg_17.configure(disabledforeground="#a3a3a3")
        self.lblArg_17.configure(foreground="#000000")
        self.lblArg_17.configure(highlightbackground="#d9d9d9")
        self.lblArg_17.configure(highlightcolor="black")
        self.lblArg_17.configure(text='''Brasil''')

        self.Label1_18 = tk.Label(self.Labelframe1_16)
        self.Label1_18.place(relx=0.12, rely=0.276, height=26, width=102
                , bordermode='ignore')
        self.Label1_18.configure(activebackground="#f9f9f9")
        self.Label1_18.configure(activeforeground="black")
        self.Label1_18.configure(background="#d9d9d9")
        self.Label1_18.configure(disabledforeground="#a3a3a3")
        self.Label1_18.configure(foreground="#000000")
        self.Label1_18.configure(highlightbackground="#d9d9d9")
        self.Label1_18.configure(highlightcolor="black")
        self.Label1_18.configure(text='''Confirmados:''')

        self.Label1_11 = tk.Label(self.Labelframe1_16)
        self.Label1_11.place(relx=0.12, rely=0.497, height=26, width=92
                , bordermode='ignore')
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(activeforeground="black")
        self.Label1_11.configure(background="#d9d9d9")
        self.Label1_11.configure(disabledforeground="#a3a3a3")
        self.Label1_11.configure(foreground="#000000")
        self.Label1_11.configure(highlightbackground="#d9d9d9")
        self.Label1_11.configure(highlightcolor="black")
        self.Label1_11.configure(text='''Fallecidos:''')

        self.Label1_12 = tk.Label(self.Labelframe1_16)
        self.Label1_12.place(relx=0.12, rely=0.718, height=26, width=112
                , bordermode='ignore')
        self.Label1_12.configure(activebackground="#f9f9f9")
        self.Label1_12.configure(activeforeground="black")
        self.Label1_12.configure(background="#d9d9d9")
        self.Label1_12.configure(disabledforeground="#a3a3a3")
        self.Label1_12.configure(foreground="#000000")
        self.Label1_12.configure(highlightbackground="#d9d9d9")
        self.Label1_12.configure(highlightcolor="black")
        self.Label1_12.configure(text='''Recuperados:''')

        self.txt_ConfirmadosBr = tk.Entry(self.Labelframe1_16)
        self.txt_ConfirmadosBr.place(relx=0.6, rely=0.276, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txt_ConfirmadosBr.configure(background="white")
        self.txt_ConfirmadosBr.configure(disabledforeground="#a3a3a3")
        self.txt_ConfirmadosBr.configure(font="TkFixedFont")
        self.txt_ConfirmadosBr.configure(foreground="#000000")
        self.txt_ConfirmadosBr.configure(highlightbackground="#d9d9d9")
        self.txt_ConfirmadosBr.configure(highlightcolor="black")
        self.txt_ConfirmadosBr.configure(insertbackground="black")
        self.txt_ConfirmadosBr.configure(selectbackground="#c4c4c4")
        self.txt_ConfirmadosBr.configure(selectforeground="black")
        self.txt_ConfirmadosBr.configure(state='readonly')
        self.txt_ConfirmadosBr.configure(textvariable=coronavirus_support.confirmadosBr)

        self.txtFallecidosBr = tk.Entry(self.Labelframe1_16)
        self.txtFallecidosBr.place(relx=0.6, rely=0.497, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txtFallecidosBr.configure(background="white")
        self.txtFallecidosBr.configure(disabledforeground="#a3a3a3")
        self.txtFallecidosBr.configure(font="TkFixedFont")
        self.txtFallecidosBr.configure(foreground="#000000")
        self.txtFallecidosBr.configure(highlightbackground="#d9d9d9")
        self.txtFallecidosBr.configure(highlightcolor="black")
        self.txtFallecidosBr.configure(insertbackground="black")
        self.txtFallecidosBr.configure(selectbackground="#c4c4c4")
        self.txtFallecidosBr.configure(selectforeground="black")
        self.txtFallecidosBr.configure(state='readonly')
        self.txtFallecidosBr.configure(textvariable=coronavirus_support.FallecidosBr)

        self.txtRecuperadosBr = tk.Entry(self.Labelframe1_16)
        self.txtRecuperadosBr.place(relx=0.6, rely=0.718, height=24
                , relwidth=0.296, bordermode='ignore')
        self.txtRecuperadosBr.configure(background="white")
        self.txtRecuperadosBr.configure(disabledforeground="#a3a3a3")
        self.txtRecuperadosBr.configure(font="TkFixedFont")
        self.txtRecuperadosBr.configure(foreground="#000000")
        self.txtRecuperadosBr.configure(highlightbackground="#d9d9d9")
        self.txtRecuperadosBr.configure(highlightcolor="black")
        self.txtRecuperadosBr.configure(insertbackground="black")
        self.txtRecuperadosBr.configure(selectbackground="#c4c4c4")
        self.txtRecuperadosBr.configure(selectforeground="black")
        self.txtRecuperadosBr.configure(state='readonly')
        self.txtRecuperadosBr.configure(textvariable=coronavirus_support.RecuperadosBr)

        self.Labelframe1_15 = tk.LabelFrame(self.Labelframe1_16)
        self.Labelframe1_15.place(relx=1.516, rely=1.061, relheight=1.0
                , relwidth=1.0, bordermode='ignore')
        self.Labelframe1_15.configure(relief='groove')
        self.Labelframe1_15.configure(foreground="black")
        self.Labelframe1_15.configure(background="#d9d9d9")
        self.Labelframe1_15.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_15.configure(highlightcolor="black")

        self.lblArg_16 = tk.Label(self.Labelframe1_15)
        self.lblArg_16.place(relx=0.268, rely=0.066, height=33, width=104
                , bordermode='ignore')
        self.lblArg_16.configure(activebackground="#f9f9f9")
        self.lblArg_16.configure(activeforeground="black")
        self.lblArg_16.configure(background="#d9d9d9")
        self.lblArg_16.configure(disabledforeground="#a3a3a3")
        self.lblArg_16.configure(foreground="#000000")
        self.lblArg_16.configure(highlightbackground="#d9d9d9")
        self.lblArg_16.configure(highlightcolor="black")
        self.lblArg_16.configure(text='''Argentina''')

        self.Label1_17 = tk.Label(self.Labelframe1_15)
        self.Label1_17.place(relx=0.12, rely=0.276, height=26, width=102
                , bordermode='ignore')
        self.Label1_17.configure(activebackground="#f9f9f9")
        self.Label1_17.configure(activeforeground="black")
        self.Label1_17.configure(background="#d9d9d9")
        self.Label1_17.configure(disabledforeground="#a3a3a3")
        self.Label1_17.configure(foreground="#000000")
        self.Label1_17.configure(highlightbackground="#d9d9d9")
        self.Label1_17.configure(highlightcolor="black")
        self.Label1_17.configure(text='''Confirmados:''')

        self.Label1_13 = tk.Label(self.Labelframe1_15)
        self.Label1_13.place(relx=0.12, rely=0.497, height=26, width=92
                , bordermode='ignore')
        self.Label1_13.configure(activebackground="#f9f9f9")
        self.Label1_13.configure(activeforeground="black")
        self.Label1_13.configure(background="#d9d9d9")
        self.Label1_13.configure(disabledforeground="#a3a3a3")
        self.Label1_13.configure(foreground="#000000")
        self.Label1_13.configure(highlightbackground="#d9d9d9")
        self.Label1_13.configure(highlightcolor="black")
        self.Label1_13.configure(text='''Fallecidos:''')

        self.Label1_14 = tk.Label(self.Labelframe1_15)
        self.Label1_14.place(relx=0.12, rely=0.718, height=26, width=112
                , bordermode='ignore')
        self.Label1_14.configure(activebackground="#f9f9f9")
        self.Label1_14.configure(activeforeground="black")
        self.Label1_14.configure(background="#d9d9d9")
        self.Label1_14.configure(disabledforeground="#a3a3a3")
        self.Label1_14.configure(foreground="#000000")
        self.Label1_14.configure(highlightbackground="#d9d9d9")
        self.Label1_14.configure(highlightcolor="black")
        self.Label1_14.configure(text='''Recuperados:''')

        self.Entry1_15 = tk.Entry(self.Labelframe1_15)
        self.Entry1_15.place(relx=0.6, rely=0.276, height=24, relwidth=0.296
                , bordermode='ignore')
        self.Entry1_15.configure(background="white")
        self.Entry1_15.configure(disabledforeground="#a3a3a3")
        self.Entry1_15.configure(font="TkFixedFont")
        self.Entry1_15.configure(foreground="#000000")
        self.Entry1_15.configure(highlightbackground="#d9d9d9")
        self.Entry1_15.configure(highlightcolor="black")
        self.Entry1_15.configure(insertbackground="black")
        self.Entry1_15.configure(selectbackground="#c4c4c4")
        self.Entry1_15.configure(selectforeground="black")

        self.Entry1_15 = tk.Entry(self.Labelframe1_15)
        self.Entry1_15.place(relx=0.6, rely=0.497, height=24, relwidth=0.296
                , bordermode='ignore')
        self.Entry1_15.configure(background="white")
        self.Entry1_15.configure(disabledforeground="#a3a3a3")
        self.Entry1_15.configure(font="TkFixedFont")
        self.Entry1_15.configure(foreground="#000000")
        self.Entry1_15.configure(highlightbackground="#d9d9d9")
        self.Entry1_15.configure(highlightcolor="black")
        self.Entry1_15.configure(insertbackground="black")
        self.Entry1_15.configure(selectbackground="#c4c4c4")
        self.Entry1_15.configure(selectforeground="black")

        self.Entry1_16 = tk.Entry(self.Labelframe1_15)
        self.Entry1_16.place(relx=0.6, rely=0.718, height=24, relwidth=0.296
                , bordermode='ignore')
        self.Entry1_16.configure(background="white")
        self.Entry1_16.configure(disabledforeground="#a3a3a3")
        self.Entry1_16.configure(font="TkFixedFont")
        self.Entry1_16.configure(foreground="#000000")
        self.Entry1_16.configure(highlightbackground="#d9d9d9")
        self.Entry1_16.configure(highlightcolor="black")
        self.Entry1_16.configure(insertbackground="black")
        self.Entry1_16.configure(selectbackground="#c4c4c4")
        self.Entry1_16.configure(selectforeground="black")

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.027, rely=0.477, relheight=0.157
                , relwidth=0.937)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(background="#d9d9d9")

        self.Label2 = tk.Label(self.Labelframe2)
        self.Label2.place(relx=0.02, rely=0.202, height=49, width=222
                , bordermode='ignore')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''País con más recuperados''')

        self.btn_buscar_masR = tk.Button(self.Labelframe2)
        self.btn_buscar_masR.place(relx=0.273, rely=0.202, height=49, width=106
                , bordermode='ignore')
        self.btn_buscar_masR.configure(activebackground="#ececec")
        self.btn_buscar_masR.configure(activeforeground="#000000")
        self.btn_buscar_masR.configure(background="#d9d9d9")
        self.btn_buscar_masR.configure(command=coronavirus_support.buscar_mas_recuperado)
        self.btn_buscar_masR.configure(disabledforeground="#a3a3a3")
        self.btn_buscar_masR.configure(foreground="#000000")
        self.btn_buscar_masR.configure(highlightbackground="#d9d9d9")
        self.btn_buscar_masR.configure(highlightcolor="black")
        self.btn_buscar_masR.configure(pady="0")
        self.btn_buscar_masR.configure(text='''BUSCAR''')

        self.Label3 = tk.Label(self.Labelframe2)
        self.Label3.place(relx=0.566, rely=0.202, height=26, width=42
                , bordermode='ignore')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''País:''')

        self.Label4 = tk.Label(self.Labelframe2)
        self.Label4.place(relx=0.556, rely=0.505, height=26, width=92
                , bordermode='ignore')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Cantidad:''')

        self.txt_país_masR = tk.Entry(self.Labelframe2)
        self.txt_país_masR.place(relx=0.615, rely=0.202, height=24
                , relwidth=0.209, bordermode='ignore')
        self.txt_país_masR.configure(background="white")
        self.txt_país_masR.configure(disabledforeground="#a3a3a3")
        self.txt_país_masR.configure(font="TkFixedFont")
        self.txt_país_masR.configure(foreground="#000000")
        self.txt_país_masR.configure(insertbackground="black")
        self.txt_país_masR.configure(state='readonly')
        self.txt_país_masR.configure(textvariable=coronavirus_support.paisMasR)

        self.txt_cantidad_masR = tk.Entry(self.Labelframe2)
        self.txt_cantidad_masR.place(relx=0.644, rely=0.505, height=24
                , relwidth=0.101, bordermode='ignore')
        self.txt_cantidad_masR.configure(background="white")
        self.txt_cantidad_masR.configure(disabledforeground="#a3a3a3")
        self.txt_cantidad_masR.configure(font="TkFixedFont")
        self.txt_cantidad_masR.configure(foreground="#000000")
        self.txt_cantidad_masR.configure(insertbackground="black")
        self.txt_cantidad_masR.configure(state='readonly')
        self.txt_cantidad_masR.configure(textvariable=coronavirus_support.cantidadMasR)

        self.Labelframe3 = tk.LabelFrame(top)
        self.Labelframe3.place(relx=0.027, rely=0.668, relheight=0.278
                , relwidth=0.939)
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Buscador''')
        self.Labelframe3.configure(background="#d9d9d9")

        self.Label5 = tk.Label(self.Labelframe3)
        self.Label5.place(relx=0.049, rely=0.229, height=26, width=61
                , bordermode='ignore')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''País:''')

        self.Label6 = tk.Label(self.Labelframe3)
        self.Label6.place(relx=0.049, rely=0.514, height=26, width=63
                , bordermode='ignore')
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Día:''')

        self.txtPais_buscador = tk.Entry(self.Labelframe3)
        self.txtPais_buscador.place(relx=0.117, rely=0.229, height=24
                , relwidth=0.179, bordermode='ignore')
        self.txtPais_buscador.configure(background="white")
        self.txtPais_buscador.configure(disabledforeground="#a3a3a3")
        self.txtPais_buscador.configure(font="TkFixedFont")
        self.txtPais_buscador.configure(foreground="#000000")
        self.txtPais_buscador.configure(insertbackground="black")

        self.txtDia_buscador = tk.Entry(self.Labelframe3)
        self.txtDia_buscador.place(relx=0.117, rely=0.514, height=24
                , relwidth=0.121, bordermode='ignore')
        self.txtDia_buscador.configure(background="white")
        self.txtDia_buscador.configure(disabledforeground="#a3a3a3")
        self.txtDia_buscador.configure(font="TkFixedFont")
        self.txtDia_buscador.configure(foreground="#000000")
        self.txtDia_buscador.configure(insertbackground="black")

        self.btn_buscarBuscador = tk.Button(self.Labelframe3)
        self.btn_buscarBuscador.place(relx=0.351, rely=0.286, height=53
                , width=106, bordermode='ignore')
        self.btn_buscarBuscador.configure(activebackground="#ececec")
        self.btn_buscarBuscador.configure(activeforeground="#000000")
        self.btn_buscarBuscador.configure(background="#d9d9d9")
        self.btn_buscarBuscador.configure(command=coronavirus_support.buscar_buscador)
        self.btn_buscarBuscador.configure(disabledforeground="#a3a3a3")
        self.btn_buscarBuscador.configure(foreground="#000000")
        self.btn_buscarBuscador.configure(highlightbackground="#d9d9d9")
        self.btn_buscarBuscador.configure(highlightcolor="black")
        self.btn_buscarBuscador.configure(pady="0")
        self.btn_buscarBuscador.configure(text='''BUSCAR''')

        self.Label7 = tk.Label(self.Labelframe3)
        self.Label7.place(relx=0.604, rely=0.171, height=26, width=112
                , bordermode='ignore')
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Confirmados:''')

        self.Label8 = tk.Label(self.Labelframe3)
        self.Label8.place(relx=0.604, rely=0.4, height=26, width=102
                , bordermode='ignore')
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Fallecidos:''')

        self.Label9 = tk.Label(self.Labelframe3)
        self.Label9.place(relx=0.613, rely=0.629, height=26, width=99
                , bordermode='ignore')
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Recuperados:''')

        self.txtConfirmados_buscador = tk.Entry(self.Labelframe3)
        self.txtConfirmados_buscador.place(relx=0.721, rely=0.171, height=24
                , relwidth=0.101, bordermode='ignore')
        self.txtConfirmados_buscador.configure(background="white")
        self.txtConfirmados_buscador.configure(disabledforeground="#a3a3a3")
        self.txtConfirmados_buscador.configure(font="TkFixedFont")
        self.txtConfirmados_buscador.configure(foreground="#000000")
        self.txtConfirmados_buscador.configure(insertbackground="black")
        self.txtConfirmados_buscador.configure(state='readonly')
        self.txtConfirmados_buscador.configure(textvariable=coronavirus_support.confirmadosBuscador)

        self.txtFallecidos_buscador = tk.Entry(self.Labelframe3)
        self.txtFallecidos_buscador.place(relx=0.721, rely=0.4, height=24
                , relwidth=0.101, bordermode='ignore')
        self.txtFallecidos_buscador.configure(background="white")
        self.txtFallecidos_buscador.configure(disabledforeground="#a3a3a3")
        self.txtFallecidos_buscador.configure(font="TkFixedFont")
        self.txtFallecidos_buscador.configure(foreground="#000000")
        self.txtFallecidos_buscador.configure(highlightbackground="#d9d9d9")
        self.txtFallecidos_buscador.configure(highlightcolor="black")
        self.txtFallecidos_buscador.configure(insertbackground="black")
        self.txtFallecidos_buscador.configure(selectbackground="#c4c4c4")
        self.txtFallecidos_buscador.configure(selectforeground="black")
        self.txtFallecidos_buscador.configure(state='readonly')
        self.txtFallecidos_buscador.configure(textvariable=coronavirus_support.fallecidosBuscador)

        self.txtRecuperados_buscador = tk.Entry(self.Labelframe3)
        self.txtRecuperados_buscador.place(relx=0.721, rely=0.629, height=24
                , relwidth=0.101, bordermode='ignore')
        self.txtRecuperados_buscador.configure(background="white")
        self.txtRecuperados_buscador.configure(disabledforeground="#a3a3a3")
        self.txtRecuperados_buscador.configure(font="TkFixedFont")
        self.txtRecuperados_buscador.configure(foreground="#000000")
        self.txtRecuperados_buscador.configure(highlightbackground="#d9d9d9")
        self.txtRecuperados_buscador.configure(highlightcolor="black")
        self.txtRecuperados_buscador.configure(insertbackground="black")
        self.txtRecuperados_buscador.configure(selectbackground="#c4c4c4")
        self.txtRecuperados_buscador.configure(selectforeground="black")
        self.txtRecuperados_buscador.configure(textvariable=coronavirus_support.Recuperados_buscador)

if __name__ == '__main__':
    vp_start_gui()





