#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 27, 2020 04:09:00 PM -03  platform: Windows NT
#    May 27, 2020 04:27:39 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

import json

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

with open('covid19.json') as archivoCov:
    lstPais = json.load(archivoCov)



def set_Tk_var():
    global confirPara
    confirPara = tk.IntVar()
    global confirAr
    confirAr = tk.IntVar()
    global falleAr
    falleAr = tk.IntVar()
    global recuAr
    recuAr = tk.IntVar()
    global fallePara
    fallePara = tk.IntVar()
    global recuPara
    recuPara = tk.IntVar()
    global confirUru
    confirUru = tk.IntVar()
    global falleUru
    falleUru = tk.IntVar()
    global recuUru
    recuUru = tk.IntVar()
    global confirBra
    confirBra = tk.IntVar()
    global falleBra
    falleBra = tk.IntVar()
    global recuBra
    recuBra = tk.IntVar()
    global pais
    pais = tk.IntVar()
    global cantidad
    cantidad = tk.IntVar()
    global paisBusc
    paisBusc = tk.StringVar()
    global dia
    dia = tk.StringVar()
    global confi
    confi = tk.StringVar()
    global falle
    falle = tk.StringVar()
    global recu
    recu = tk.StringVar()

    for datos in lstPais:
        if datos["pais"] == "Argentina":
            if int(datos["confirmados"]) >= confirAr.get():
                confirAr.set(datos["confirmados"])
            if int(datos["muertos"]) >= falleAr.get():
                falleAr.set(datos["muertos"])
            if int(datos["recuperados"]) >= recuAr.get():
                recuAr.set(datos["recuperados"])
        if datos["pais"] == "Paraguay":
            if int(datos["confirmados"]) >= confirPara.get():
                confirPara.set(datos["confirmados"])
            if int(datos["muertos"]) >= fallePara.get():
                fallePara.set(datos["muertos"])
            if int(datos["recuperados"]) >= recuPara.get():
                recuPara.set(datos["recuperados"])
        if datos["pais"] == "Uruguay":
            if int(datos["confirmados"]) >= confirUru.get():
                confirUru.set(datos["confirmados"])
            if int(datos["muertos"]) >= falleUru.get():
                falleUru.set(datos["muertos"])
            if int(datos["recuperados"]) >= recuUru.get():
                recuUru.set(datos["recuperados"])
        if datos["pais"] == "Brazil":
            if int(datos["confirmados"]) >= confirBra.get():
                confirBra.set(datos["confirmados"])
            if int(datos["muertos"]) >= falleBra.get():
                falleBra.set(datos["muertos"])
            if int(datos["recuperados"]) >= recuBra.get():
                recuBra.set(datos["recuperados"])

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def busc2():
    print('covid_support.busc2')
    sys.stdout.flush()
    paisB=paisBusc.get()
    diaB=dia.get()
    for datos in lstPais:
        if paisB == datos["pais"] and diaB == datos["dia"]:
            confi.set(datos["confirmados"])
            falle.set(datos["muertos"])
            recu.set(datos["recuperados"])

def buscPaisMas():
    print('covid_support.buscPaisMas')
    sys.stdout.flush()
    for datos in lstPais:
        if datos["pais"]:
            if int(datos["confirmados"]) >= cantidad.get():
                cantidad.set(datos["confirmados"])
                pais.set(datos["pais"])

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import covid
    covid.vp_start_gui()





            #loc.set(datos["localidad_nombre"])
            #pro.set(datos["provincia_nombre"])
            #dep.set(datos["departamento_nombre"])
            #financiamiento.set(datos["origen_financiamiento"])
            #domi.set(datos["domicilio"])





