#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 27, 2020 04:27:30 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import covid_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    covid_support.set_Tk_var()
    top = Toplevel1 (root)
    covid_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    covid_support.set_Tk_var()
    top = Toplevel1 (w)
    covid_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("835x450+458+257")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Covid-19")
        top.configure(background="#d9d9d9")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.036, rely=0.044, height=21, width=216)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Vizualizacion de Informacion por Paises:''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.036, rely=0.111, relheight=0.322
                , relwidth=0.208)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.287, rely=0.069, height=21, width=68)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Argentina''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.057, rely=0.276, height=21, width=75)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Confirmados''')

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.511, rely=0.276,height=20, relwidth=0.425)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(textvariable=covid_support.confirAr)

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.115, rely=0.483, height=21, width=54)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Fallecidos''')

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.511, rely=0.483,height=20, relwidth=0.425)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=covid_support.falleAr)

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.057, rely=0.69, height=21, width=74)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Recuperados''')

        self.Entry3 = tk.Entry(self.Frame1)
        self.Entry3.place(relx=0.511, rely=0.69,height=20, relwidth=0.425)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(textvariable=covid_support.recuAr)

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.273, rely=0.111, relheight=0.322
                , relwidth=0.208)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")

        self.Label6 = tk.Label(self.Frame2)
        self.Label6.place(relx=0.345, rely=0.069, height=21, width=55)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Paraguay''')

        self.Label7 = tk.Label(self.Frame2)
        self.Label7.place(relx=0.057, rely=0.276, height=21, width=75)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Confirmados''')

        self.Label8 = tk.Label(self.Frame2)
        self.Label8.place(relx=0.115, rely=0.483, height=21, width=58)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Fallecidos''')

        self.Label9 = tk.Label(self.Frame2)
        self.Label9.place(relx=0.057, rely=0.69, height=21, width=74)
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Recuperados''')

        self.Entry4 = tk.Entry(self.Frame2)
        self.Entry4.place(relx=0.511, rely=0.276,height=20, relwidth=0.425)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(textvariable=covid_support.confirPara)

        self.Entry5 = tk.Entry(self.Frame2)
        self.Entry5.place(relx=0.511, rely=0.483,height=20, relwidth=0.425)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(textvariable=covid_support.fallePara)

        self.Entry6 = tk.Entry(self.Frame2)
        self.Entry6.place(relx=0.511, rely=0.69,height=20, relwidth=0.425)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(textvariable=covid_support.recuPara)

        self.Frame2_2 = tk.Frame(top)
        self.Frame2_2.place(relx=0.515, rely=0.111, relheight=0.322
                , relwidth=0.208)
        self.Frame2_2.configure(relief='groove')
        self.Frame2_2.configure(borderwidth="2")
        self.Frame2_2.configure(relief="groove")
        self.Frame2_2.configure(background="#d9d9d9")
        self.Frame2_2.configure(highlightbackground="#d9d9d9")
        self.Frame2_2.configure(highlightcolor="black")

        self.Label6_3 = tk.Label(self.Frame2_2)
        self.Label6_3.place(relx=0.345, rely=0.069, height=21, width=55)
        self.Label6_3.configure(activebackground="#f9f9f9")
        self.Label6_3.configure(activeforeground="black")
        self.Label6_3.configure(background="#d9d9d9")
        self.Label6_3.configure(disabledforeground="#a3a3a3")
        self.Label6_3.configure(foreground="#000000")
        self.Label6_3.configure(highlightbackground="#d9d9d9")
        self.Label6_3.configure(highlightcolor="black")
        self.Label6_3.configure(text='''Uruguay''')

        self.Label7_4 = tk.Label(self.Frame2_2)
        self.Label7_4.place(relx=0.057, rely=0.276, height=21, width=75)
        self.Label7_4.configure(activebackground="#f9f9f9")
        self.Label7_4.configure(activeforeground="black")
        self.Label7_4.configure(background="#d9d9d9")
        self.Label7_4.configure(disabledforeground="#a3a3a3")
        self.Label7_4.configure(foreground="#000000")
        self.Label7_4.configure(highlightbackground="#d9d9d9")
        self.Label7_4.configure(highlightcolor="black")
        self.Label7_4.configure(text='''Confirmados''')

        self.Label8_5 = tk.Label(self.Frame2_2)
        self.Label8_5.place(relx=0.115, rely=0.483, height=21, width=58)
        self.Label8_5.configure(activebackground="#f9f9f9")
        self.Label8_5.configure(activeforeground="black")
        self.Label8_5.configure(background="#d9d9d9")
        self.Label8_5.configure(disabledforeground="#a3a3a3")
        self.Label8_5.configure(foreground="#000000")
        self.Label8_5.configure(highlightbackground="#d9d9d9")
        self.Label8_5.configure(highlightcolor="black")
        self.Label8_5.configure(text='''Fallecidos''')

        self.Label9_6 = tk.Label(self.Frame2_2)
        self.Label9_6.place(relx=0.057, rely=0.69, height=21, width=74)
        self.Label9_6.configure(activebackground="#f9f9f9")
        self.Label9_6.configure(activeforeground="black")
        self.Label9_6.configure(background="#d9d9d9")
        self.Label9_6.configure(disabledforeground="#a3a3a3")
        self.Label9_6.configure(foreground="#000000")
        self.Label9_6.configure(highlightbackground="#d9d9d9")
        self.Label9_6.configure(highlightcolor="black")
        self.Label9_6.configure(text='''Recuperados''')

        self.Entry4_7 = tk.Entry(self.Frame2_2)
        self.Entry4_7.place(relx=0.511, rely=0.276,height=20, relwidth=0.425)
        self.Entry4_7.configure(background="white")
        self.Entry4_7.configure(disabledforeground="#a3a3a3")
        self.Entry4_7.configure(font="TkFixedFont")
        self.Entry4_7.configure(foreground="#000000")
        self.Entry4_7.configure(highlightbackground="#d9d9d9")
        self.Entry4_7.configure(highlightcolor="black")
        self.Entry4_7.configure(insertbackground="black")
        self.Entry4_7.configure(selectbackground="#c4c4c4")
        self.Entry4_7.configure(selectforeground="black")
        self.Entry4_7.configure(textvariable=covid_support.confirUru)

        self.Entry5_8 = tk.Entry(self.Frame2_2)
        self.Entry5_8.place(relx=0.511, rely=0.483,height=20, relwidth=0.425)
        self.Entry5_8.configure(background="white")
        self.Entry5_8.configure(disabledforeground="#a3a3a3")
        self.Entry5_8.configure(font="TkFixedFont")
        self.Entry5_8.configure(foreground="#000000")
        self.Entry5_8.configure(highlightbackground="#d9d9d9")
        self.Entry5_8.configure(highlightcolor="black")
        self.Entry5_8.configure(insertbackground="black")
        self.Entry5_8.configure(selectbackground="#c4c4c4")
        self.Entry5_8.configure(selectforeground="black")
        self.Entry5_8.configure(textvariable=covid_support.falleUru)

        self.Entry6_9 = tk.Entry(self.Frame2_2)
        self.Entry6_9.place(relx=0.511, rely=0.69,height=20, relwidth=0.425)
        self.Entry6_9.configure(background="white")
        self.Entry6_9.configure(disabledforeground="#a3a3a3")
        self.Entry6_9.configure(font="TkFixedFont")
        self.Entry6_9.configure(foreground="#000000")
        self.Entry6_9.configure(highlightbackground="#d9d9d9")
        self.Entry6_9.configure(highlightcolor="black")
        self.Entry6_9.configure(insertbackground="black")
        self.Entry6_9.configure(selectbackground="#c4c4c4")
        self.Entry6_9.configure(selectforeground="black")
        self.Entry6_9.configure(textvariable=covid_support.recuUru)

        self.Frame2_3 = tk.Frame(top)
        self.Frame2_3.place(relx=0.754, rely=0.111, relheight=0.322
                , relwidth=0.208)
        self.Frame2_3.configure(relief='groove')
        self.Frame2_3.configure(borderwidth="2")
        self.Frame2_3.configure(relief="groove")
        self.Frame2_3.configure(background="#d9d9d9")
        self.Frame2_3.configure(highlightbackground="#d9d9d9")
        self.Frame2_3.configure(highlightcolor="black")

        self.Label6_4 = tk.Label(self.Frame2_3)
        self.Label6_4.place(relx=0.345, rely=0.069, height=21, width=55)
        self.Label6_4.configure(activebackground="#f9f9f9")
        self.Label6_4.configure(activeforeground="black")
        self.Label6_4.configure(background="#d9d9d9")
        self.Label6_4.configure(disabledforeground="#a3a3a3")
        self.Label6_4.configure(foreground="#000000")
        self.Label6_4.configure(highlightbackground="#d9d9d9")
        self.Label6_4.configure(highlightcolor="black")
        self.Label6_4.configure(text='''Brasil''')

        self.Label7_5 = tk.Label(self.Frame2_3)
        self.Label7_5.place(relx=0.057, rely=0.276, height=21, width=75)
        self.Label7_5.configure(activebackground="#f9f9f9")
        self.Label7_5.configure(activeforeground="black")
        self.Label7_5.configure(background="#d9d9d9")
        self.Label7_5.configure(disabledforeground="#a3a3a3")
        self.Label7_5.configure(foreground="#000000")
        self.Label7_5.configure(highlightbackground="#d9d9d9")
        self.Label7_5.configure(highlightcolor="black")
        self.Label7_5.configure(text='''Confirmados''')

        self.Label8_6 = tk.Label(self.Frame2_3)
        self.Label8_6.place(relx=0.115, rely=0.483, height=21, width=58)
        self.Label8_6.configure(activebackground="#f9f9f9")
        self.Label8_6.configure(activeforeground="black")
        self.Label8_6.configure(background="#d9d9d9")
        self.Label8_6.configure(disabledforeground="#a3a3a3")
        self.Label8_6.configure(foreground="#000000")
        self.Label8_6.configure(highlightbackground="#d9d9d9")
        self.Label8_6.configure(highlightcolor="black")
        self.Label8_6.configure(text='''Fallecidos''')

        self.Label9_7 = tk.Label(self.Frame2_3)
        self.Label9_7.place(relx=0.057, rely=0.69, height=21, width=74)
        self.Label9_7.configure(activebackground="#f9f9f9")
        self.Label9_7.configure(activeforeground="black")
        self.Label9_7.configure(background="#d9d9d9")
        self.Label9_7.configure(disabledforeground="#a3a3a3")
        self.Label9_7.configure(foreground="#000000")
        self.Label9_7.configure(highlightbackground="#d9d9d9")
        self.Label9_7.configure(highlightcolor="black")
        self.Label9_7.configure(text='''Recuperados''')

        self.Entry4_8 = tk.Entry(self.Frame2_3)
        self.Entry4_8.place(relx=0.511, rely=0.276,height=20, relwidth=0.425)
        self.Entry4_8.configure(background="white")
        self.Entry4_8.configure(disabledforeground="#a3a3a3")
        self.Entry4_8.configure(font="TkFixedFont")
        self.Entry4_8.configure(foreground="#000000")
        self.Entry4_8.configure(highlightbackground="#d9d9d9")
        self.Entry4_8.configure(highlightcolor="black")
        self.Entry4_8.configure(insertbackground="black")
        self.Entry4_8.configure(selectbackground="#c4c4c4")
        self.Entry4_8.configure(selectforeground="black")
        self.Entry4_8.configure(textvariable=covid_support.confirBra)

        self.Entry5_9 = tk.Entry(self.Frame2_3)
        self.Entry5_9.place(relx=0.511, rely=0.483,height=20, relwidth=0.425)
        self.Entry5_9.configure(background="white")
        self.Entry5_9.configure(disabledforeground="#a3a3a3")
        self.Entry5_9.configure(font="TkFixedFont")
        self.Entry5_9.configure(foreground="#000000")
        self.Entry5_9.configure(highlightbackground="#d9d9d9")
        self.Entry5_9.configure(highlightcolor="black")
        self.Entry5_9.configure(insertbackground="black")
        self.Entry5_9.configure(selectbackground="#c4c4c4")
        self.Entry5_9.configure(selectforeground="black")
        self.Entry5_9.configure(textvariable=covid_support.falleBra)

        self.Entry6_10 = tk.Entry(self.Frame2_3)
        self.Entry6_10.place(relx=0.511, rely=0.69,height=20, relwidth=0.425)
        self.Entry6_10.configure(background="white")
        self.Entry6_10.configure(disabledforeground="#a3a3a3")
        self.Entry6_10.configure(font="TkFixedFont")
        self.Entry6_10.configure(foreground="#000000")
        self.Entry6_10.configure(highlightbackground="#d9d9d9")
        self.Entry6_10.configure(highlightcolor="black")
        self.Entry6_10.configure(insertbackground="black")
        self.Entry6_10.configure(selectbackground="#c4c4c4")
        self.Entry6_10.configure(selectforeground="black")
        self.Entry6_10.configure(textvariable=covid_support.recuBra)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.036, rely=0.467, relheight=0.189
                , relwidth=0.928)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")

        self.Label10 = tk.Label(self.Frame3)
        self.Label10.place(relx=0.026, rely=0.353, height=21, width=143)
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''País con más recuperados''')

        self.Button1 = tk.Button(self.Frame3)
        self.Button1.place(relx=0.323, rely=0.235, height=44, width=77)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=covid_support.buscPaisMas)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Buscar''')

        self.Label11 = tk.Label(self.Frame3)
        self.Label11.place(relx=0.516, rely=0.118, height=21, width=37)
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''Pais''')

        self.Label12 = tk.Label(self.Frame3)
        self.Label12.place(relx=0.503, rely=0.588, height=21, width=54)
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(text='''Cantidad''')

        self.Entry7 = tk.Entry(self.Frame3)
        self.Entry7.place(relx=0.581, rely=0.118,height=20, relwidth=0.134)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(textvariable=covid_support.pais)

        self.Entry8 = tk.Entry(self.Frame3)
        self.Entry8.place(relx=0.581, rely=0.588,height=20, relwidth=0.07)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(textvariable=covid_support.cantidad)

        self.Label13 = tk.Label(top)
        self.Label13.place(relx=0.036, rely=0.667, height=21, width=55)
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(text='''Buscador''')

        self.Frame4 = tk.Frame(top)
        self.Frame4.place(relx=0.036, rely=0.733, relheight=0.233
                , relwidth=0.928)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#d9d9d9")

        self.Label14 = tk.Label(self.Frame4)
        self.Label14.place(relx=0.013, rely=0.095, height=21, width=27)
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(text='''Pais''')

        self.Label15 = tk.Label(self.Frame4)
        self.Label15.place(relx=0.013, rely=0.381, height=21, width=23)
        self.Label15.configure(background="#d9d9d9")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(text='''Dia''')

        self.Entry9 = tk.Entry(self.Frame4)
        self.Entry9.place(relx=0.052, rely=0.095,height=20, relwidth=0.16)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(textvariable=covid_support.paisBusc)

        self.Entry10 = tk.Entry(self.Frame4)
        self.Entry10.place(relx=0.052, rely=0.381,height=20, relwidth=0.044)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(textvariable=covid_support.dia)

        self.Button2 = tk.Button(self.Frame4)
        self.Button2.place(relx=0.323, rely=0.19, height=44, width=77)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=covid_support.busc2)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Buscar''')

        self.Label16 = tk.Label(self.Frame4)
        self.Label16.place(relx=0.516, rely=0.095, height=21, width=75)
        self.Label16.configure(background="#d9d9d9")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(text='''Confirmados''')

        self.Label17 = tk.Label(self.Frame4)
        self.Label17.place(relx=0.529, rely=0.381, height=21, width=58)
        self.Label17.configure(background="#d9d9d9")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(foreground="#000000")
        self.Label17.configure(text='''Fallecidos''')

        self.Label18 = tk.Label(self.Frame4)
        self.Label18.place(relx=0.516, rely=0.667, height=21, width=74)
        self.Label18.configure(background="#d9d9d9")
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(foreground="#000000")
        self.Label18.configure(text='''Recuperados''')

        self.Entry11 = tk.Entry(self.Frame4)
        self.Entry11.place(relx=0.645, rely=0.095,height=20, relwidth=0.108)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(textvariable=covid_support.confi)

        self.Entry12 = tk.Entry(self.Frame4)
        self.Entry12.place(relx=0.645, rely=0.381,height=20, relwidth=0.108)
        self.Entry12.configure(background="white")
        self.Entry12.configure(disabledforeground="#a3a3a3")
        self.Entry12.configure(font="TkFixedFont")
        self.Entry12.configure(foreground="#000000")
        self.Entry12.configure(insertbackground="black")
        self.Entry12.configure(textvariable=covid_support.falle)

        self.Entry13 = tk.Entry(self.Frame4)
        self.Entry13.place(relx=0.645, rely=0.667,height=20, relwidth=0.108)
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font="TkFixedFont")
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(insertbackground="black")
        self.Entry13.configure(textvariable=covid_support.recu)

if __name__ == '__main__':
    vp_start_gui()





