#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 06:34:56 PM -03  platform: Windows NT

import sys
import  ABM as ABM

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entryPais
    entryPais = tk.StringVar()
    global entryDia
    entryDia = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    visualizar()

def visualizar ():
    lstcovid19 = ABM.archivoJson()
    for element in lstcovid19:
        confirmados= int(element['confirmados'])
        fallecidos = int (element['muertos'])
        recuperados = int (element['recuperados'])
        pais = element['pais']
        if pais == 'Argentina':
            w.lblConfirmados.configure(text = str(confirmados))
            w.lblFallecidos.configure (text = str (fallecidos))
            w.lblRecuperados.configure(text = str (recuperados))
        elif pais == 'Paraguay':
            w.lblConfirmadosPY.configure(text = str(confirmados))
            w.lblFallecidosPY.configure (text = str (fallecidos))
            w.lblRecuperadosPY.configure(text = str (recuperados))
        elif pais == 'Uruguay':
            w.lblConfirmadosUY.configure(text = str(confirmados))
            w.lblFallecidosUY.configure (text = str (fallecidos))
            w.lblRecuperadosUY.configure(text = str (recuperados))
        elif pais == 'Brazil':
            w.lblConfirmadosBR.configure(text = str(confirmados))
            w.lblFallecidosBR.configure (text = str (fallecidos))
            w.lblRecuperadosBR.configure(text = str (recuperados))




def buscarPais():
    lstcovid19 = ABM.archivoJson()
    for element in lstcovid19:
        recuperados = int (element['recuperados'])
        confirmados= int(element['confirmados'])
        fallecidos = int (element['muertos'])
        pais = element['pais']
        dia = element['dia']
        diaBuscado = entryDia.get()
        paisBuscado = entryPais.get()
        if pais == paisBuscado:
            if dia == diaBuscado:
                w.bConfirmados.configure(text = confirmados)
                w.bFallecidos.configure (text = fallecidos)
                w.bRecuperados.configure (text = recuperados)


def buscarRecuperados():
    lstcovid19 = ABM.archivoJson()
    lstConfirmados  =list()
    for element in lstcovid19:
        confirmados= int(element['confirmados'])
        pais = element['pais']
        lstConfirmados.append(confirmados)
        max_item = max(lstConfirmados, key=int)
        if max_item == confirmados:
            w.recuperadosPais.configure(text= pais)
            w.recuperadosCantidad.configure (text = max_item)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Covid19
    Covid19.vp_start_gui()




