#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 04:50:23 PM -03  platform: Windows NT

import sys
import json
with open('covid19.json', encoding='utf-8') as archivoCovid:
    lstPais = json.load(archivoCovid)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global confiarg
    confiarg = tk.IntVar()
    global fallearg
    fallearg = tk.IntVar()
    global recuparg
    recuparg = tk.IntVar()
    global confirpar
    confirpar = tk.IntVar()
    global fallepar
    fallepar = tk.IntVar()
    global recuparaguay
    recuparaguay = tk.IntVar()
    global confiuru
    confiuru = tk.IntVar()
    global falleuru
    falleuru = tk.IntVar()
    global recuuru
    recuuru = tk.IntVar()
    global confirbra
    confirbra = tk.IntVar()
    global fallebra
    fallebra = tk.IntVar()
    global recupbra
    recupbra = tk.IntVar()
    global ent_pais
    ent_pais = tk.IntVar()
    global ent_cant
    ent_cant = tk.IntVar()
    global bus_pais
    bus_pais = tk.StringVar()
    global bus_dia
    bus_dia = tk.StringVar()
    global entry_confir
    entry_confir = tk.StringVar()
    global entry_fallec
    entry_fallec = tk.StringVar()
    global entry_recup
    entry_recup = tk.StringVar()

    for pais in lstPais:
        if pais ["pais"]== "Argentina":
            if int(pais["confirmados"])>=confiarg.get():
                confiarg.set(pais["confirmados"])
            if int (pais["muertos"])>=fallearg.get():
                fallearg.set(pais["muertos"])
            if int(pais["recuperados"])>=recuparg.get():
                recuparg.set(pais["recuperados"])
        if pais ["pais"]== "Paraguay":
            if int(pais["confirmados"])>=confirpar.get():
                confirpar.set(pais["confirmados"])
            if int (pais["muertos"])>=fallepar.get():
                fallepar.set(pais["muertos"])
            if int(pais["recuperados"])>=recuparaguay.get():
                recuparaguay.set(pais["recuperados"])
        if pais ["pais"]== "Uruguay":
            if int(pais["confirmados"])>=confiuru.get():
                confiuru.set(pais["confirmados"])
            if int (pais["muertos"])>=falleuru.get():
                falleuru.set(pais["muertos"])
            if int(pais["recuperados"])>=recuuru.get():
                recuuru.set(pais["recuperados"])
        if pais ["pais"]== "Brazil":
            if int(pais["confirmados"])>=confirbra.get():
                confirbra.set(pais["confirmados"])
            if int (pais["muertos"])>=fallebra.get():
                fallebra.set(pais["muertos"])
            if int(pais["recuperados"])>=recupbra.get():
                recupbra.set(pais["recuperados"])

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def Busc_precuperado():
    print('Covid-19 demo_support.Busc_precuperado')
    sys.stdout.flush()
    for datos in lstPais:
        if datos["pais"]:
            if int(datos["confirmados"]) >= ent_cant.get():
                ent_cant.set(datos["confirmados"])
                ent_pais.set(datos["pais"])

def bus_buscar():
    print('Covid-19 demo_support.bus_buscar')
    sys.stdout.flush()
    paises=bus_pais.get()
    dias=bus_dia.get()
    for datos in lstPais:
        if paises == datos["pais"] and dias == datos["dia"]:
            entry_confir.set(datos["confirmados"])
            entry_fallec.set(datos["muertos"])
            entry_recup.set(datos["recuperados"])


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Covidemo
    Covidemo.vp_start_gui()




