#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 04:52:16 PM -03  platform: Windows NT
#    May 27, 2020 05:28:53 PM -03  platform: Windows NT
import json
import sys
with open("covid19.json", encoding='utf-8') as archivodeDias:
    listaFechasObservacion = json.load(archivodeDias)
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entry_dias
    entry_dias = tk.StringVar()
    #argentina-----------------------------
    global lbl_confir_arg
    lbl_confir_arg = tk.StringVar()
    lbl_confir_arg.set('-----------')
    global lbl_falle_arg
    lbl_falle_arg = tk.StringVar()
    lbl_falle_arg.set('-----------')
    global lbl_recup_arg
    lbl_recup_arg = tk.StringVar()
    lbl_recup_arg.set('-----------')
    #paraguay-----------------------------
    global lbl_confir_parag
    lbl_confir_parag = tk.StringVar()
    lbl_confir_parag.set('-----------')
    global lbl_falle_parag
    lbl_falle_parag = tk.StringVar()
    lbl_falle_parag.set('-----------')
    global lbl_recup_parag
    lbl_recup_parag = tk.StringVar()
    lbl_recup_parag.set('-----------')
    #uruguay---------------------
    global lbl_confir_urug
    lbl_confir_urug = tk.StringVar()
    lbl_confir_urug.set('-----------')
    global lbl_falle_urug
    lbl_falle_urug = tk.StringVar()
    lbl_falle_urug.set('-----------')
    global lbl_recup_urug
    lbl_recup_urug = tk.StringVar()
    lbl_recup_urug.set('-----------')
    #brasil----------------------------------
    global lbl_confir_bra
    lbl_confir_bra = tk.StringVar()
    lbl_confir_bra.set('-----------')
    global lbl_falle_bra
    lbl_falle_bra = tk.StringVar()
    lbl_falle_bra.set('-----------')
    global lbl_recup_bra
    lbl_recup_bra = tk.StringVar()
    lbl_recup_bra.set('-----------')
    #--------pais mas recuperados
    global lbl_pais_recuperado
    lbl_pais_recuperado = tk.StringVar()
    lbl_pais_recuperado.set('------------------')
    global lbl_cantidad_rec
    lbl_cantidad_rec = tk.StringVar()
    lbl_cantidad_rec.set('------------------')
    #buscador_pais-------------------------------
    global combobox_paises
    combobox_paises = tk.StringVar()
    global lbl_pais_confir
    lbl_pais_confir = tk.StringVar()
    lbl_pais_confir.set('------------------')
    global lbl_pais_falle
    lbl_pais_falle = tk.StringVar()
    lbl_pais_falle.set('------------------')
    global lbl_pais_recup
    lbl_pais_recup = tk.StringVar()
    lbl_pais_recup.set('------------------')
    global lbl_dia_pais
    lbl_dia_pais = tk.StringVar()
    lbl_dia_pais.set('------------------')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    mostrar_nombres_paises()

    w.tcombobox_paises.configure(values=mostrar_nombres_paises(),state="readonly")

def mostrar_datos_paises():
    global list_aux
    confirmados_l = [0, 0, 0, 0]
    fallecidos_l = [0, 0, 0, 0]
    recuperados_l = [0, 0, 0, 0]
    for i in listaFechasObservacion:
        if i['pais'] == "Argentina":
            confirmados_l[0] += int(i['confirmados'])
            fallecidos_l[0] += int(i['muertos'])
            recuperados_l[0] += int(i['recuperados'])
        elif i['pais'] == "Paraguay":
            confirmados_l[1] += int(i['confirmados'])
            fallecidos_l[1] += int(i['muertos'])
            recuperados_l[1] += int(i['recuperados'])
        elif i['pais'] == "Uruguay":
            confirmados_l[2] += int(i['confirmados'])
            fallecidos_l[2] += int(i['muertos'])
            recuperados_l[2] += int(i['recuperados'])
        elif i['pais'] == "Brazil":
            confirmados_l[3] += int(i['confirmados'])
            fallecidos_l[3] += int(i['muertos'])
            recuperados_l[3] += int(i['recuperados'])



def pais_encontrado():
    confirmados = "---"
    recuperados = "---"
    fallecidos = "---"
    for dato in listaFechasObservacion:
        if w.tcombobox_paises.get()==dato["pais"] and  entry_dias.get()==dato["fechaobservacion"]:
            confirmados=dato["confirmados"]
            recuperados=dato["recuperados"]
            fallecidos=dato["muertos"]
        lbl_pais_confir.set(confirmados)
        lbl_pais_falle.set(fallecidos)
        lbl_pais_recup.set(recuperados)

    sys.stdout.flush()

def pais_mas_recuperados():
    indice = confirmados_l.index(max(confirmados_l))
    cantidad = max(confirmados_l)
    list_aux[1] = cantidad

    if indice == 0:
        list_aux[0] = 'Argentina'
    elif indice == 1:
        list_aux[0] = 'Paraguay'
    elif indice == 2:
        list_aux[0] = 'Uruguay'
    elif indice == 3:
        list_aux[0] = 'Brasil'


def set_pais_confirmados():
    global list_aux
    entr_pais_var.set(list_aux[0])
    entr_cant_var.set(list_aux[1])

    sys.stdout.flush()
#funciones para combobox
def mostrar_nombres_paises():
    global listaFinan
    lista_de_paises=list()
    for finan in listaFechasObservacion:
        if finan["pais"] not in lista_de_paises:
            lista_de_paises.append(finan["pais"])
    return lista_de_paises

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Demo_parcial
    Demo_parcial.vp_start_gui()





