#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  May 27, 2020 05:27:16 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 1006x606+557+181
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "covid"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 185 -width 232 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab50 \
        -background #0080ff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief groove -text ----------- \
        -textvariable lbl_confir_arg 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Fallecidos: 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Recuperados: 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #ff0000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_falle_arg 
    vTcl:DefineAlias "$site_3_0.lab54" "Label3_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #27ed2d \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_recup_arg 
    vTcl:DefineAlias "$site_3_0.lab55" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Argentina 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.517 -y 0 -rely 0.161 -width 0 \
        -relwidth 0.478 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.093 -y 0 -rely 0.432 -width 0 \
        -relwidth 0.442 -height 0 -relheight 0.222 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.086 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.397 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.517 -y 0 -rely 0.442 -width 0 \
        -relwidth 0.478 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.512 -y 0 -rely 0.703 -width 0 \
        -relwidth 0.479 -height 0 -relheight 0.184 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.203 -y 0 -rely 0.054 -width 0 \
        -relwidth 0.312 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra46
    label $top.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Visualización de información por países:} 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text Confirmados: 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra58 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 185 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 202 
    vTcl:DefineAlias "$top.fra58" "Frame1_6" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra58
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Fallecidos: 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Recuperados: 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Paraguay 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Confirmados: 
    vTcl:DefineAlias "$site_3_0.lab59" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black -background #0080ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_confir_parag 
    vTcl:DefineAlias "$site_3_0.lab81" "Label3_7" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab81
    label $site_3_0.lab82 \
        -activebackground #f9f9f9 -activeforeground black -background #ff0000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_falle_parag 
    vTcl:DefineAlias "$site_3_0.lab82" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black -background #27ed2d \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_recup_parag 
    vTcl:DefineAlias "$site_3_0.lab83" "Label3_4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab83
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.402 -width 0 \
        -relwidth 0.35 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.448 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.203 -y 0 -rely 0.054 -width 0 \
        -relwidth 0.312 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.161 -width 0 \
        -relwidth 0.448 -height 0 -relheight 0.217 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 0 -relx 0.493 -y 0 -rely 0.161 -width 0 \
        -relwidth 0.498 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -relx 0.443 -y 0 -rely 0.402 -width 0 \
        -relwidth 0.547 -height 0 -relheight 0.181 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 0 -relx 0.493 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.498 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra58
    frame $top.fra60 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 185 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 260 
    vTcl:DefineAlias "$top.fra60" "Frame1_7" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra60
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Fallecidos: 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Recuperados: 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Uruguay 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Confirmados: 
    vTcl:DefineAlias "$site_3_0.lab59" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab84 \
        -activebackground #f9f9f9 -activeforeground black -background #0080ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_confir_urug 
    vTcl:DefineAlias "$site_3_0.lab84" "Label3_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab85 \
        -activebackground #f9f9f9 -activeforeground black -background #ff0000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_falle_urug 
    vTcl:DefineAlias "$site_3_0.lab85" "Label3_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab86 \
        -activebackground #f9f9f9 -activeforeground black -background #27ed2d \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_recup_urug 
    vTcl:DefineAlias "$site_3_0.lab86" "Label3_5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.139 -y 0 -rely 0.432 -width 0 \
        -relwidth 0.398 -height 0 -relheight 0.222 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.157 -y 0 -rely 0.703 -width 0 \
        -relwidth 0.398 -height 0 -relheight 0.222 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.203 -y 0 -rely 0.054 -width 0 \
        -relwidth 0.312 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.12 -y 0 -rely 0.162 -width 0 \
        -relwidth 0.449 -height 0 -relheight 0.216 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 0 -relx 0.52 -y 0 -rely 0.161 -width 0 \
        -relwidth 0.404 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 0 -relx 0.48 -y 0 -rely 0.442 -width 0 \
        -relwidth 0.444 -height 0 -relheight 0.181 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.723 -width 0 \
        -relwidth 0.404 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra60
    frame $top.fra61 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 185 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 260 
    vTcl:DefineAlias "$top.fra61" "Frame1_8" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra61
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Fallecidos: 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Recuperados: 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Brasil 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Confirmados: 
    vTcl:DefineAlias "$site_3_0.lab59" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab87 \
        -activebackground #f9f9f9 -activeforeground black -background #0080ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_confir_bra 
    vTcl:DefineAlias "$site_3_0.lab87" "Label3_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab88 \
        -activebackground #f9f9f9 -activeforeground black -background #ff0000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_falle_bra 
    vTcl:DefineAlias "$site_3_0.lab88" "Label3_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab89 \
        -activebackground #f9f9f9 -activeforeground black -background #27ed2d \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_recup_bra 
    vTcl:DefineAlias "$site_3_0.lab89" "Label3_6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.079 -y 0 -rely 0.442 -width 0 \
        -relwidth 0.397 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.119 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.397 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.203 -y 0 -rely 0.054 -width 0 \
        -relwidth 0.312 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.12 -y 0 -rely 0.162 -width 0 \
        -relwidth 0.448 -height 0 -relheight 0.216 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab87 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.161 -width 0 \
        -relwidth 0.381 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 0 -relx 0.476 -y 0 -rely 0.442 -width 0 \
        -relwidth 0.385 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab89 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.401 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra61
    frame $top.fra62 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 122 -width 965 
    vTcl:DefineAlias "$top.fra62" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra62
    label $site_3_0.lab63 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {País con más recuperados} 
    vTcl:DefineAlias "$site_3_0.lab63" "Label4" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu64 \
        -command pais_mas_recuperados -takefocus {} -text buscar 
    vTcl:DefineAlias "$site_3_0.tBu64" "btn_buscar_Recuperados" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text País: 
    vTcl:DefineAlias "$site_3_0.lab65" "Label4_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ------------------ \
        -textvariable lbl_pais_recuperado 
    vTcl:DefineAlias "$site_3_0.lab66" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_3_0.lab67" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ------------------ \
        -textvariable lbl_cantidad_rec 
    vTcl:DefineAlias "$site_3_0.lab68" "Label4_11" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.084 -y 0 -rely 0.316 -width 0 \
        -relwidth 0.232 -height 0 -relheight 0.274 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu64 \
        -in $site_3_0 -x 0 -relx 0.314 -y 0 -rely 0.316 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.45 -y 0 -rely 0.105 -width 0 \
        -relwidth 0.085 -height 0 -relheight 0.274 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.528 -y 0 -rely 0.076 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.275 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.44 -y 0 -rely 0.526 -width 0 \
        -relwidth 0.074 -height 0 -relheight 0.274 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.528 -y 0 -rely 0.534 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.275 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab70 \
        -font TkDefaultFont -foreground black -text BUSCADOR \
        -background $vTcl(actual_gui_bg) -height 145 -width 970 
    vTcl:DefineAlias "$top.lab70" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab70
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text País: 
    vTcl:DefineAlias "$site_3_0.lab71" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo73 \
        -font TkTextFont -textvariable combobox_paises -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo73" "tcombobox_paises" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu74 \
        -command pais_encontrado -takefocus {} -text buscar 
    vTcl:DefineAlias "$site_3_0.tBu74" "btn_buscar_Recuperados_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab75 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Confirmados: 
    vTcl:DefineAlias "$site_3_0.lab75" "Label2_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Fallecidos: 
    vTcl:DefineAlias "$site_3_0.lab76" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Recuperados: 
    vTcl:DefineAlias "$site_3_0.lab77" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ------------------ -textvariable lbl_pais_confir 
    vTcl:DefineAlias "$site_3_0.lab78" "Label4_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab79 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ------------------ -textvariable lbl_pais_falle 
    vTcl:DefineAlias "$site_3_0.lab79" "Label4_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab80 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ------------------ -textvariable lbl_pais_recup 
    vTcl:DefineAlias "$site_3_0.lab80" "Label4_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab90 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Dia: 
    vTcl:DefineAlias "$site_3_0.lab90" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent92 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_dias -width 10 
    vTcl:DefineAlias "$site_3_0.ent92" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.207 -width 0 \
        -relwidth 0.085 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo73 \
        -in $site_3_0 -x 0 -relx 0.124 -y 0 -rely 0.207 -width 0 \
        -relwidth 0.194 -height 0 -relheight 0.179 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu74 \
        -in $site_3_0 -x 0 -relx 0.361 -y 0 -rely 0.207 -width 98 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 0 -relx 0.66 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.108 -height 0 -relheight 0.228 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 0 -relx 0.66 -y 0 -rely 0.414 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.241 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.67 -y 0 -rely 0.69 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.241 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 0 -relx 0.773 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.158 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 0 -relx 0.773 -y 0 -rely 0.414 -width 0 \
        -relwidth 0.158 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 0 -relx 0.773 -y 0 -rely 0.69 -width 0 \
        -relwidth 0.16 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 0 -relx 0.041 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.108 -height 0 -relheight 0.228 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent92 \
        -in $site_3_0 -x 0 -relx 0.124 -y 0 -rely 0.552 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.089 -width 0 -relwidth 0.231 \
        -height 0 -relheight 0.411 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.022 -width 0 -relwidth 0.487 \
        -height 0 -relheight 0.067 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.156 -width 0 -relwidth 0.104 \
        -height 0 -relheight 0.089 -anchor nw -bordermode ignore 
    place $top.fra58 \
        -in $top -x 0 -relx 0.249 -y 0 -rely 0.089 -width 0 -relwidth 0.201 \
        -height 0 -relheight 0.411 -anchor nw -bordermode ignore 
    place $top.fra60 \
        -in $top -x 0 -relx 0.457 -y 0 -rely 0.089 -width 0 -relwidth 0.249 \
        -height 0 -relheight 0.411 -anchor nw -bordermode ignore 
    place $top.fra61 \
        -in $top -x 0 -relx 0.716 -y 0 -rely 0.089 -width 0 -relwidth 0.25 \
        -height 0 -relheight 0.411 -anchor nw -bordermode ignore 
    place $top.fra62 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.521 -width 0 -relwidth 0.959 \
        -height 0 -relheight 0.216 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.02 -y 0 -rely 0.743 -width 0 -relwidth 0.964 \
        -height 0 -relheight 0.239 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

