#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:18:28 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import parcial_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    parcial_support.set_Tk_var()
    top = Toplevel1 (root)
    parcial_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    parcial_support.set_Tk_var()
    top = Toplevel1 (w)
    parcial_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("763x640+852+309")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.026, rely=0.016, height=26, width=251)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Cantidad de Diputados por Provincia''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.013, rely=0.063, relwidth=0.957)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.039, rely=0.094, height=26, width=71)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Provincia:''')

        self.txtProvincia = tk.Entry(top)
        self.txtProvincia.place(relx=0.144, rely=0.094, height=24
                , relwidth=0.307)
        self.txtProvincia.configure(background="white")
        self.txtProvincia.configure(disabledforeground="#a3a3a3")
        self.txtProvincia.configure(font="TkFixedFont")
        self.txtProvincia.configure(foreground="#000000")
        self.txtProvincia.configure(insertbackground="black")
        self.txtProvincia.configure(textvariable=parcial_support.provincia)

        self.CalcularProvincia = tk.Button(top)
        self.CalcularProvincia.place(relx=0.459, rely=0.094, height=33
                , width=106)
        self.CalcularProvincia.configure(activebackground="#ececec")
        self.CalcularProvincia.configure(activeforeground="#000000")
        self.CalcularProvincia.configure(background="#d9d9d9")
        self.CalcularProvincia.configure(command=parcial_support.calcuclar_provincia)
        self.CalcularProvincia.configure(cursor="fleur")
        self.CalcularProvincia.configure(disabledforeground="#a3a3a3")
        self.CalcularProvincia.configure(foreground="#000000")
        self.CalcularProvincia.configure(highlightbackground="#d9d9d9")
        self.CalcularProvincia.configure(highlightcolor="black")
        self.CalcularProvincia.configure(pady="0")
        self.CalcularProvincia.configure(text='''Calcular''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.695, rely=0.094, height=26, width=69)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Cantidad:''')

        self.txtCantidad = tk.Entry(top)
        self.txtCantidad.place(relx=0.786, rely=0.094, height=24, relwidth=0.136)

        self.txtCantidad.configure(background="white")
        self.txtCantidad.configure(disabledforeground="#a3a3a3")
        self.txtCantidad.configure(font="TkFixedFont")
        self.txtCantidad.configure(foreground="#000000")
        self.txtCantidad.configure(insertbackground="black")
        self.txtCantidad.configure(state='readonly')
        self.txtCantidad.configure(textvariable=parcial_support.cantidad)

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.026, rely=0.188, height=27, width=291)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Cantidad de Diputados por Bloque Político''')

        self.TSeparator1_2 = ttk.Separator(top)
        self.TSeparator1_2.place(relx=0.013, rely=0.234, relwidth=0.957)

        self.Label2_3 = tk.Label(top)
        self.Label2_3.place(relx=0.039, rely=0.266, height=26, width=71)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#d9d9d9")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Bloque:''')

        self.txtBloque = tk.Entry(top)
        self.txtBloque.place(relx=0.144, rely=0.266,height=24, relwidth=0.307)
        self.txtBloque.configure(background="white")
        self.txtBloque.configure(disabledforeground="#a3a3a3")
        self.txtBloque.configure(font="TkFixedFont")
        self.txtBloque.configure(foreground="#000000")
        self.txtBloque.configure(highlightbackground="#d9d9d9")
        self.txtBloque.configure(highlightcolor="black")
        self.txtBloque.configure(insertbackground="black")
        self.txtBloque.configure(selectbackground="#c4c4c4")
        self.txtBloque.configure(selectforeground="black")
        self.txtBloque.configure(textvariable=parcial_support.bloque)

        self.CalcularBloque = tk.Button(top)
        self.CalcularBloque.place(relx=0.459, rely=0.266, height=33, width=106)
        self.CalcularBloque.configure(activebackground="#ececec")
        self.CalcularBloque.configure(activeforeground="#000000")
        self.CalcularBloque.configure(background="#d9d9d9")
        self.CalcularBloque.configure(command=parcial_support.calcular_bloque)
        self.CalcularBloque.configure(disabledforeground="#a3a3a3")
        self.CalcularBloque.configure(foreground="#000000")
        self.CalcularBloque.configure(highlightbackground="#d9d9d9")
        self.CalcularBloque.configure(highlightcolor="black")
        self.CalcularBloque.configure(pady="0")
        self.CalcularBloque.configure(text='''Calcular''')

        self.Label3_6 = tk.Label(top)
        self.Label3_6.place(relx=0.695, rely=0.25, height=26, width=69)
        self.Label3_6.configure(activebackground="#f9f9f9")
        self.Label3_6.configure(activeforeground="black")
        self.Label3_6.configure(background="#d9d9d9")
        self.Label3_6.configure(disabledforeground="#a3a3a3")
        self.Label3_6.configure(foreground="#000000")
        self.Label3_6.configure(highlightbackground="#d9d9d9")
        self.Label3_6.configure(highlightcolor="black")
        self.Label3_6.configure(text='''Hombres:''')

        self.Label3_7 = tk.Label(top)
        self.Label3_7.place(relx=0.695, rely=0.297, height=26, width=69)
        self.Label3_7.configure(activebackground="#f9f9f9")
        self.Label3_7.configure(activeforeground="black")
        self.Label3_7.configure(background="#d9d9d9")
        self.Label3_7.configure(disabledforeground="#a3a3a3")
        self.Label3_7.configure(foreground="#000000")
        self.Label3_7.configure(highlightbackground="#d9d9d9")
        self.Label3_7.configure(highlightcolor="black")
        self.Label3_7.configure(text='''Mujeres:''')

        self.txtHombres = tk.Entry(top)
        self.txtHombres.place(relx=0.799, rely=0.25,height=24, relwidth=0.136)
        self.txtHombres.configure(background="white")
        self.txtHombres.configure(disabledforeground="#a3a3a3")
        self.txtHombres.configure(font="TkFixedFont")
        self.txtHombres.configure(foreground="#000000")
        self.txtHombres.configure(highlightbackground="#d9d9d9")
        self.txtHombres.configure(highlightcolor="black")
        self.txtHombres.configure(insertbackground="black")
        self.txtHombres.configure(selectbackground="#c4c4c4")
        self.txtHombres.configure(selectforeground="black")
        self.txtHombres.configure(state='readonly')
        self.txtHombres.configure(textvariable=parcial_support.hombres)

        self.txtMujeres = tk.Entry(top)
        self.txtMujeres.place(relx=0.799, rely=0.297,height=24, relwidth=0.136)
        self.txtMujeres.configure(background="white")
        self.txtMujeres.configure(disabledforeground="#a3a3a3")
        self.txtMujeres.configure(font="TkFixedFont")
        self.txtMujeres.configure(foreground="#000000")
        self.txtMujeres.configure(highlightbackground="#d9d9d9")
        self.txtMujeres.configure(highlightcolor="black")
        self.txtMujeres.configure(insertbackground="black")
        self.txtMujeres.configure(selectbackground="#c4c4c4")
        self.txtMujeres.configure(selectforeground="black")
        self.txtMujeres.configure(state='readonly')
        self.txtMujeres.configure(textvariable=parcial_support.mujeres)

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.026, rely=0.391, height=27, width=130)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Cantidad de Viajes''')

        self.TSeparator1_3 = ttk.Separator(top)
        self.TSeparator1_3.place(relx=0.026, rely=0.438, relwidth=0.957)

        self.Label2_4 = tk.Label(top)
        self.Label2_4.place(relx=0.039, rely=0.453, height=26, width=71)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#d9d9d9")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Origen:''')

        self.Label2_4 = tk.Label(top)
        self.Label2_4.place(relx=0.039, rely=0.5, height=26, width=71)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#d9d9d9")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Destino:''')

if __name__ == '__main__':
    vp_start_gui()





