#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:44:28 PM -03  platform: Windows NT

import sys
import json
with open('diputados.json', encoding = 'utf-8') as filedip:
    lista_diputados = json.load(filedip)
with open('viajes.json', encoding = 'utf-8') as fileviajes:
    lista_viajes = json.load(fileviajes)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global buscProv
    buscProv = tk.StringVar()
    global buscCantProv
    buscCantProv = tk.StringVar()
    global buscBloq
    buscBloq = tk.StringVar()
    global buscCantBloq
    buscCantBloq = tk.StringVar()
    buscCantBloq.set(' ')
    global buscGen
    buscGen = tk.StringVar()
    global buscOrig
    buscOrig = tk.StringVar()
    global buscCantViaje
    buscCantViaje = tk.StringVar()
    buscCantViaje.set(' ')
    global buscDest
    buscDest = tk.StringVar()
    global idDip
    idDip = tk.StringVar()
    global nomComp
    nomComp = tk.StringVar()
    global prov
    prov = tk.StringVar()
    global bloque
    bloque = tk.StringVar()
    global anoInicio
    anoInicio = tk.StringVar()
    global cantViajesDip
    cantViajesDip = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def buscDiputado():
    id=idDip.get()
    cont = 0
    viajes = 0
    for diputado in lista_diputados:
        if diputado[str(lista_diputados.index(diputado)+1)]["\ufeffdiputado_id"] == id:
            nomcomp=(diputado[str(lista_diputados.index(diputado)+1)]["diputado_nombre"]+" "+diputado[str(lista_diputados.index(diputado)+1)]["diputado_apellido"])
            Provincia=diputado[str(lista_diputados.index(diputado) + 1)]["diputado_distrito"]
            bloq=diputado[str(lista_diputados.index(diputado) + 1)]["diputado_bloque"]
            Inicio=diputado[str(lista_diputados.index(diputado) + 1)]["mandato_inicio"]
            for viaje in lista_viajes:
                if viaje[str(lista_viajes.index(viaje) + 1)]["\ufeffPersona_id"] == id:
                        viajes += 1

            nomComp.set(nomcomp)
            prov.set(Provincia)
            bloque.set(bloq)
            anoInicio.set(Inicio[0:4])
            cantViajesDip.set(viajes)
        cont+=1

def buscarPBloq():
    bloq=buscBloq.get().upper()
    gen=buscGen.get().upper()
    cont=0
    for diputado in lista_diputados:
        if diputado[str(lista_diputados.index(diputado)+1)]["diputado_bloque"] == bloq and diputado[str(lista_diputados.index(diputado)+1)]["diputado_genero"] == gen:
            cont+=1
    buscCantBloq.set(cont)

def buscarPProvincia():
    provincia=buscProv.get().upper()
    cont=0
    for diputado in lista_diputados:
        if diputado[str(lista_diputados.index(diputado)+1)]["diputado_distrito"] == provincia:
            cont+=1
    buscCantProv.set(cont)


def buscarPViaje():
    origen = buscOrig.get()
    destino = buscDest.get()
    cont = 0
    for viaje in lista_viajes:
        if viaje[str(lista_viajes.index(viaje) + 1)]["Origen_ciudad"] == origen and viaje[str(lista_viajes.index(viaje) + 1)]["Destino_ciudad"] == destino:
            cont += 1
    buscCantViaje.set(cont)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import parcial
    parcial.vp_start_gui()




