#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 04:56:57 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Parcial2020_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Parcial2020_support.set_Tk_var()
    top = Toplevel1 (root)
    Parcial2020_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Parcial2020_support.set_Tk_var()
    top = Toplevel1 (w)
    Parcial2020_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("745x616+262+124")
        top.minsize(120, 1)
        top.maxsize(1284, 1005)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.015, rely=0.015, relheight=0.161
                , relwidth=0.976)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Cantidad de Diputados por Provincia''')
        self.Labelframe1.configure(background="#d9d9d9")

        self.Label1 = tk.Label(self.Labelframe1)
        self.Label1.place(relx=0.028, rely=0.414, height=32, width=64
                , bordermode='ignore')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Provincia :''')

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.426, rely=0.313, height=44, width=74
                , bordermode='ignore')
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Parcial2020_support.Diputadosprovincia)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Calcular''')

        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.646, rely=0.313, height=32, width=74
                , bordermode='ignore')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Cantidad :''')

        self.Label3 = tk.Label(self.Labelframe1)
        self.Label3.place(relx=0.743, rely=0.313, height=32, width=125
                , bordermode='ignore')
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''-''')

        self.TCombobox1 = ttk.Combobox(self.Labelframe1)
        self.TCombobox1.place(relx=0.124, rely=0.414, relheight=0.273
                , relwidth=0.281, bordermode='ignore')
        self.value_list = ['SANTIAGO','DEL','ESTERO','MENDOZA','BUENOS_AIRES','CATAMARCA','SANTA_FE','CORDOBA','SAN_LUIS','LA_RIOJA','JUJUY','RIO_NEGRO','TUCUMAN','SALTA','FORMOSA','CHACO','ENTRE_RIOS','MISIONES','CIUDAD_DE_BUENOS_AIRES','LA_PAMPA','SANTA_CRUZ','CORRIENTES',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=Parcial2020_support.provcombo)
        self.TCombobox1.configure(takefocus="")

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.0, rely=0.183, relheight=0.193
                , relwidth=0.976)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Cantidad de Diputados por Bloque Político''')
        self.Labelframe2.configure(background="#d9d9d9")

        self.Label4 = tk.Label(self.Labelframe2)
        self.Label4.place(relx=0.028, rely=0.345, height=37, width=83
                , bordermode='ignore')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Bloque :''')

        self.Button2 = tk.Button(self.Labelframe2)
        self.Button2.place(relx=0.426, rely=0.261, height=44, width=77
                , bordermode='ignore')
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=Parcial2020_support.diputadosbloque)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Calcular''')

        self.Label5 = tk.Label(self.Labelframe2)
        self.Label5.place(relx=0.702, rely=0.168, height=22, width=61
                , bordermode='ignore')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Hombres :''')

        self.Label6 = tk.Label(self.Labelframe2)
        self.Label6.place(relx=0.702, rely=0.605, height=21, width=74
                , bordermode='ignore')
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Mujeres :''')

        self.Label3_2 = tk.Label(self.Labelframe2)
        self.Label3_2.place(relx=0.799, rely=0.168, height=22, width=115
                , bordermode='ignore')
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#ffffff")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(foreground="#000000")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''-''')

        self.Label3_3 = tk.Label(self.Labelframe2)
        self.Label3_3.place(relx=0.799, rely=0.605, height=21, width=115
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#ffffff")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''-''')

        self.TCombobox1_7 = ttk.Combobox(self.Labelframe2)
        self.TCombobox1_7.place(relx=0.138, rely=0.345, relheight=0.227
                , relwidth=0.282, bordermode='ignore')
        self.value_list = ['SANTIAGO','DEL','ESTERO','MENDOZA','BUENOS AIRES','CATAMARCA','SANTA FE','CORDOBA','SAN LUIS','LA RIOJA','JUJUY','RIO NEGRO','TUCUMAN','SALTA','FORMOSA','CHACO','ENTRE RIOS','MISIONES','CIUDAD DE BUENOS_AIRES','LA PAMPA','SANTA CRUZ','CORRIENTES',]
        self.TCombobox1_7.configure(values=self.value_list)
        self.TCombobox1_7.configure(textvariable=Parcial2020_support.provcombo)
        self.TCombobox1_7.configure(takefocus="")

        self.Labelframe3 = tk.LabelFrame(top)
        self.Labelframe3.place(relx=0.013, rely=0.399, relheight=0.209
                , relwidth=0.976)
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Cantidad de Viajes''')
        self.Labelframe3.configure(background="#d9d9d9")

        self.Label7 = tk.Label(self.Labelframe3)
        self.Label7.place(relx=0.041, rely=0.163, height=31, width=54
                , bordermode='ignore')
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Origen :''')

        self.Label8 = tk.Label(self.Labelframe3)
        self.Label8.place(relx=0.041, rely=0.636, height=21, width=55
                , bordermode='ignore')
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Destino :''')

        self.Button2_5 = tk.Button(self.Labelframe3)
        self.Button2_5.place(relx=0.426, rely=0.318, height=44, width=77
                , bordermode='ignore')
        self.Button2_5.configure(activebackground="#ececec")
        self.Button2_5.configure(activeforeground="#000000")
        self.Button2_5.configure(background="#d9d9d9")
        self.Button2_5.configure(command=Parcial2020_support.cantidadviajes)
        self.Button2_5.configure(disabledforeground="#a3a3a3")
        self.Button2_5.configure(foreground="#000000")
        self.Button2_5.configure(highlightbackground="#d9d9d9")
        self.Button2_5.configure(highlightcolor="black")
        self.Button2_5.configure(pady="0")
        self.Button2_5.configure(text='''Calcular''')

        self.Label9 = tk.Label(self.Labelframe3)
        self.Label9.place(relx=0.662, rely=0.395, height=32, width=64
                , bordermode='ignore')
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Cantidad :''')

        self.Label3_6 = tk.Label(self.Labelframe3)
        self.Label3_6.place(relx=0.758, rely=0.395, height=32, width=125
                , bordermode='ignore')
        self.Label3_6.configure(activebackground="#f9f9f9")
        self.Label3_6.configure(activeforeground="black")
        self.Label3_6.configure(background="#ffffff")
        self.Label3_6.configure(disabledforeground="#a3a3a3")
        self.Label3_6.configure(foreground="#000000")
        self.Label3_6.configure(highlightbackground="#d9d9d9")
        self.Label3_6.configure(highlightcolor="black")
        self.Label3_6.configure(text='''-''')

        self.TCombobox1_8 = ttk.Combobox(self.Labelframe3)
        self.TCombobox1_8.place(relx=0.124, rely=0.163, relheight=0.24
                , relwidth=0.282, bordermode='ignore')
        self.value_list = ['SANTIAGO','DEL','ESTERO','MENDOZA','BUENOS_AIRES','CATAMARCA','SANTA_FE','CORDOBA','SAN_LUIS','LA_RIOJA','JUJUY','RIO_NEGRO','TUCUMAN','SALTA','FORMOSA','CHACO','ENTRE_RIOS','MISIONES','CIUDAD_DE_BUENOS_AIRES','LA_PAMPA','SANTA_CRUZ','CORRIENTES',]
        self.TCombobox1_8.configure(values=self.value_list)
        self.TCombobox1_8.configure(textvariable=Parcial2020_support.provcombo)
        self.TCombobox1_8.configure(takefocus="")

        self.TCombobox1_9 = ttk.Combobox(self.Labelframe3)
        self.TCombobox1_9.place(relx=0.124, rely=0.558, relheight=0.24
                , relwidth=0.281, bordermode='ignore')
        self.value_list = ['SANTIAGO','DEL','ESTERO','MENDOZA','BUENOS_AIRES','CATAMARCA','SANTA_FE','CORDOBA','SAN_LUIS','LA_RIOJA','JUJUY','RIO_NEGRO','TUCUMAN','SALTA','FORMOSA','CHACO','ENTRE_RIOS','MISIONES','CIUDAD_DE_BUENOS_AIRES','LA_PAMPA','SANTA_CRUZ','CORRIENTES',]
        self.TCombobox1_9.configure(values=self.value_list)
        self.TCombobox1_9.configure(textvariable=Parcial2020_support.provcombo)
        self.TCombobox1_9.configure(takefocus="")

        self.Labelframe4 = tk.LabelFrame(top)
        self.Labelframe4.place(relx=0.013, rely=0.631, relheight=0.341
                , relwidth=0.98)
        self.Labelframe4.configure(relief='groove')
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Buscador de Diputados''')
        self.Labelframe4.configure(background="#d9d9d9")

        self.Label10 = tk.Label(self.Labelframe4)
        self.Label10.place(relx=0.055, rely=0.148, height=22, width=104
                , bordermode='ignore')
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''Diputado ID :''')

        self.Label11 = tk.Label(self.Labelframe4)
        self.Label11.place(relx=0.014, rely=0.343, height=22, width=122
                , bordermode='ignore')
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''Nombre Completo :''')

        self.Label12 = tk.Label(self.Labelframe4)
        self.Label12.place(relx=0.082, rely=0.538, height=22, width=71
                , bordermode='ignore')
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(text='''Provincia :''')

        self.Label13 = tk.Label(self.Labelframe4)
        self.Label13.place(relx=0.014, rely=0.733, height=22, width=133
                , bordermode='ignore')
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(text='''Cantidad de Viajes :''')

        self.Label14 = tk.Label(self.Labelframe4)
        self.Label14.place(relx=0.466, rely=0.49, height=22, width=49
                , bordermode='ignore')
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(text='''Bloque :''')

        self.Label15 = tk.Label(self.Labelframe4)
        self.Label15.place(relx=0.438, rely=0.733, height=22, width=75
                , bordermode='ignore')
        self.Label15.configure(background="#d9d9d9")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(text='''Año Inicio :''')

        self.Button2_6 = tk.Button(self.Labelframe4)
        self.Button2_6.place(relx=0.425, rely=0.1, height=44, width=77
                , bordermode='ignore')
        self.Button2_6.configure(activebackground="#ececec")
        self.Button2_6.configure(activeforeground="#000000")
        self.Button2_6.configure(background="#d9d9d9")
        self.Button2_6.configure(command=Parcial2020_support.buscadordip)
        self.Button2_6.configure(disabledforeground="#a3a3a3")
        self.Button2_6.configure(foreground="#000000")
        self.Button2_6.configure(highlightbackground="#d9d9d9")
        self.Button2_6.configure(highlightcolor="black")
        self.Button2_6.configure(pady="0")
        self.Button2_6.configure(text='''Buscar''')

        self.Entry2 = tk.Entry(self.Labelframe4)
        self.Entry2.place(relx=0.178, rely=0.1, height=37, relwidth=0.225
                , bordermode='ignore')
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=Parcial2020_support.entrid)

        self.Label3_3 = tk.Label(self.Labelframe4)
        self.Label3_3.place(relx=0.178, rely=0.343, height=22, width=156
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#ffffff")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''-''')

        self.Label3_3 = tk.Label(self.Labelframe4)
        self.Label3_3.place(relx=0.178, rely=0.538, height=22, width=155
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#ffffff")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''-''')

        self.Label3_3 = tk.Label(self.Labelframe4)
        self.Label3_3.place(relx=0.178, rely=0.733, height=22, width=156
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#ffffff")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''-''')

        self.Label3_3 = tk.Label(self.Labelframe4)
        self.Label3_3.place(relx=0.548, rely=0.49, height=22, width=165
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#ffffff")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''-''')

        self.Label3_3 = tk.Label(self.Labelframe4)
        self.Label3_3.place(relx=0.548, rely=0.733, height=22, width=166
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#ffffff")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''-''')

if __name__ == '__main__':
    vp_start_gui()





