#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:49:56 PM -03  platform: Windows NT

import sys
import json

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

with open("diputados.json") as archivo:
    datos = json.load(archivo)

with open("viajes.json") as archivo:
    datos2 = json.load(archivo)

def set_Tk_var():
    global provcombo
    provcombo = tk.StringVar()
    global entrydipbloq
    entrydipbloq = tk.StringVar()
    global entryorigen
    entryorigen = tk.StringVar()
    global entrydestino
    entrydestino = tk.StringVar()
    global entrid
    entrid = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def Diputadosprovincia():
    for learning in datos:
        print(learning['diputado_bloque'])
        print('Parcial2020_support.Diputadosprovincia')
    sys.stdout.flush()

def buscadordip():
    print('Parcial2020_support.buscadordip')
    sys.stdout.flush()

def cantidadviajes():
    print('Parcial2020_support.cantidadviajes')
    sys.stdout.flush()

def diputadosbloque():
    print('Parcial2020_support.diputadosbloque')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Parcial2020
    Parcial2020.vp_start_gui()




