#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Jun 01, 2020 03:24:55 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 803x678+608+183
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 1005
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab45 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 96 -width 727 
    vTcl:DefineAlias "$top.lab45" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab45
    label $site_3_0.lab50 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Provincia :} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 204 
    vTcl:DefineAlias "$site_3_0.ent51" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but52" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cantidad : } 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text - 
    vTcl:DefineAlias "$site_3_0.lab54" "Label3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.028 -y 0 -rely 0.417 -width 0 \
        -relwidth 0.088 -height 0 -relheight 0.323 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent51 \
        -in $site_3_0 -x 0 -relx 0.124 -y 0 -rely 0.417 -width 204 \
        -relwidth 0 -height 27 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.426 -y 0 -rely 0.313 -width 74 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.646 -y 0 -rely 0.313 -width 0 \
        -relwidth 0.102 -height 0 -relheight 0.323 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.743 -y 0 -rely 0.313 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.323 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab46 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 116 -width 727 
    vTcl:DefineAlias "$top.lab46" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab46
    label $site_3_0.lab55 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text {Bloque :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text - 
    vTcl:DefineAlias "$site_3_0.lab57" "Label3_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but59" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Hombres :} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Mujeres :} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text - 
    vTcl:DefineAlias "$site_3_0.lab62" "Label3_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text - 
    vTcl:DefineAlias "$site_3_0.lab63" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.028 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.114 -height 0 -relheight 0.31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.138 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.241 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 0 -relx 0.427 -y 0 -rely 0.259 -width 77 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.702 -y 0 -rely 0.172 -height 0 \
        -relheight 0.181 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.702 -y 0 -rely 0.603 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.181 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.799 -y 0 -rely 0.172 -width 0 \
        -relwidth 0.158 -height 0 -relheight 0.181 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.799 -y 0 -rely 0.603 -width 0 \
        -relwidth 0.158 -height 0 -relheight 0.181 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab48 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 126 -width 727 
    vTcl:DefineAlias "$top.lab48" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    label $site_3_0.lab64 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Origen : } 
    vTcl:DefineAlias "$site_3_0.lab64" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Destino : } 
    vTcl:DefineAlias "$site_3_0.lab65" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text - 
    vTcl:DefineAlias "$site_3_0.lab67" "Label3_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text - 
    vTcl:DefineAlias "$site_3_0.lab68" "Label3_4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but69" "Button2_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cantidad :} 
    vTcl:DefineAlias "$site_3_0.lab70" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text - 
    vTcl:DefineAlias "$site_3_0.lab71" "Label3_6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.041 -y 0 -rely 0.159 -width 0 \
        -relwidth 0.074 -height 0 -relheight 0.246 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.041 -y 0 -rely 0.635 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.167 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.124 -y 0 -rely 0.159 -width 0 \
        -relwidth 0.158 -height 0 -relheight 0.246 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.124 -y 0 -rely 0.556 -width 0 \
        -relwidth 0.157 -height 0 -relheight 0.246 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 0 -relx 0.427 -y 0 -rely 0.317 -width 77 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.661 -y 0 -rely 0.397 -width 0 \
        -relwidth 0.088 -height 0 -relheight 0.246 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.758 -y 0 -rely 0.397 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.246 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab49 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 205 -width 730 
    vTcl:DefineAlias "$top.lab49" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab49
    label $site_3_0.lab72 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Diputado ID :} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Nombre Completo :} 
    vTcl:DefineAlias "$site_3_0.lab73" "Label11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Provincia :} 
    vTcl:DefineAlias "$site_3_0.lab74" "Label12" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.055 -y 0 -rely 0.147 -width 0 \
        -relwidth 0.142 -height 0 -relheight 0.103 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.343 -width 0 \
        -relwidth 0.167 -height 0 -relheight 0.103 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx 0.082 -y 0 -rely 0.539 -width 0 \
        -relwidth 0.097 -height 0 -relheight 0.103 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.013 -width 0 -relwidth 0.905 \
        -height 0 -relheight 0.142 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.162 -width 0 -relwidth 0.905 \
        -height 0 -relheight 0.171 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.354 -width 0 -relwidth 0.905 \
        -height 0 -relheight 0.186 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.56 -width 0 -relwidth 0.909 \
        -height 0 -relheight 0.302 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

