#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:43:55 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import json
with open("diputados.json", encoding = 'utf-8') as archivo:
    listaDiputados = json.load(archivo)
with open("viajes.json", encoding = 'utf-8') as archivo:
    listaViajes = json.load(archivo)

def set_Tk_var():
    global provincia
    provincia = tk.StringVar()
    global cantidad
    cantidad = tk.StringVar()
    global bloque
    bloque = tk.StringVar()
    global hombres
    hombres = tk.StringVar()
    global mujeres
    mujeres = tk.StringVar()
    global origen
    origen = tk.StringVar()
    global destino
    destino = tk.StringVar()
    global cantidadViajes
    cantidadViajes = tk.StringVar()
    global id
    id = tk.StringVar()
    global nombreCompleto
    nombreCompleto = tk.StringVar()
    global provinciaBD
    provinciaBD = tk.StringVar()
    global viajes
    viajes = tk.StringVar()
    global bloqueBD
    bloqueBD = tk.StringVar()
    global añoI
    añoI = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def buscar_diputados():
    print('parcial_support.buscar_diputados')
    sys.stdout.flush()

def calcuclar_provincia():
    global w, cantidad
    provincia = w.txtProvincia.get()
    indice = 0
    cantidadA = 0
    while indice <= 0:
        
    cantidad.set[cantidad]



def calcular_bloque():
    print('parcial_support.calcular_bloque')
    sys.stdout.flush()

def calcular_viajes():
    print('parcial_support.calcular_viajes')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import parcial
    parcial.vp_start_gui()




