#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Jun 01, 2020 03:43:57 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 990x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 95 -width 955 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab46 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Provincia: 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo47" "tcombobox_provincias" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calcular_cant_por_provincia \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but48" "btn_calcular_cant_dip" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 -textvariable lbl_cant_dip 
    vTcl:DefineAlias "$site_3_0.lab50" "lb_cant" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 135 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$site_3_0.fra54" "Frame1_10" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra54
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_4_0.lab46" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo47" "tcombobox_provincias_12" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_4_0.but48" "btn_calcular_cant_dip_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_4_0.lab49" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 
    vTcl:DefineAlias "$site_4_0.lab50" "lbl_cant_dip_8" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab46 \
        -in $site_4_0 -x 0 -relx 0.031 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo47 \
        -in $site_4_0 -x 0 -relx 0.115 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.366 -y 0 -rely 0.148 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.565 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra55 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 135 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$site_3_0.fra55" "Frame1_9" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra55
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_4_0.lab46" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo47" "tcombobox_provincias_11" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_4_0.but48" "btn_calcular_cant_dip_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_4_0.lab49" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 
    vTcl:DefineAlias "$site_4_0.lab50" "lbl_cant_dip_8" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_0.fra54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 135 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$site_4_0.fra54" "Frame1_9" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra54
    label $site_5_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_5_0.lab46" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo47" "tcomboboxprovincias_11" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_5_0.but48" "btncalcularcantdip_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_5_0.lab49" "Label1_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 
    vTcl:DefineAlias "$site_5_0.lab50" "lblcantdip_9" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab46 \
        -in $site_5_0 -x 0 -relx 0.031 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tCo47 \
        -in $site_5_0 -x 0 -relx 0.115 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but48 \
        -in $site_5_0 -x 0 -relx 0.366 -y 0 -rely 0.148 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab49 \
        -in $site_5_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab50 \
        -in $site_5_0 -x 0 -relx 0.565 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 0 -relx 0.031 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo47 \
        -in $site_4_0 -x 0 -relx 0.115 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.366 -y 0 -rely 0.148 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.565 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra54 \
        -in $site_4_0 -x 0 -relx 0.199 -y 0 -rely 2 -width 0 -relwidth 1 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.031 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.189 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo47 \
        -in $site_3_0 -x 0 -relx 0.115 -y 0 -rely 0.147 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.295 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.366 -y 0 -rely 0.148 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.565 -y 0 -rely 0.147 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.368 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra54 \
        -in $site_3_0 -x 0 -relx 0.199 -y 0 -rely 2 -width 0 -relwidth 1 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    place $site_3_0.fra55 \
        -in $site_3_0 -x 0 -relx 0.147 -y 0 -rely 1.926 -width 0 -relwidth 1 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Cantidad de Diputados por Provincia:} 
    vTcl:DefineAlias "$top.lab53" "Label1_9" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra56 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 125 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$top.fra56" "Frame1_10" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra56
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Bloque: 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo47" "tcombobox_bloque" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calcular_dip_por_bloque \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but48" "btn_calcular_cant_dip_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Hombres: 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 -textvariable lbl_cant_sex_m 
    vTcl:DefineAlias "$site_3_0.lab50" "lbl_cant_H" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 135 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$site_3_0.fra54" "Frame1_9" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra54
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_4_0.lab46" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo47" "tcomboboxprovincias_11" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_4_0.but48" "btncalcularcantdip_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_4_0.lab49" "Label1_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 
    vTcl:DefineAlias "$site_4_0.lab50" "lblcantdip_9" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab46 \
        -in $site_4_0 -x 0 -relx 0.031 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo47 \
        -in $site_4_0 -x 0 -relx 0.115 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.366 -y 0 -rely 0.148 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.565 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra55 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 135 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$site_3_0.fra55" "Frame1_10" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra55
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_4_0.lab46" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo47" "tcomboboxprovincias_12" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_4_0.but48" "btncalcularcantdip_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_4_0.lab49" "Label1_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 
    vTcl:DefineAlias "$site_4_0.lab50" "lblcantdip_9" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_0.fra54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 135 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 955 
    vTcl:DefineAlias "$site_4_0.fra54" "Frame1_10" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra54
    label $site_5_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_5_0.lab46" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo47 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo47" "tcomboboxprovincias_12" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_5_0.but48" "btncalcularcantdip_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad: 
    vTcl:DefineAlias "$site_5_0.lab49" "Label1_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 
    vTcl:DefineAlias "$site_5_0.lab50" "lblcantdip_10" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab46 \
        -in $site_5_0 -x 0 -relx 0.031 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tCo47 \
        -in $site_5_0 -x 0 -relx 0.115 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but48 \
        -in $site_5_0 -x 0 -relx 0.366 -y 0 -rely 0.148 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab49 \
        -in $site_5_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab50 \
        -in $site_5_0 -x 0 -relx 0.565 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 0 -relx 0.031 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo47 \
        -in $site_4_0 -x 0 -relx 0.115 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.366 -y 0 -rely 0.148 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.565 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra54 \
        -in $site_4_0 -x 0 -relx 0.199 -y 0 -rely 2 -width 0 -relwidth 1 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Mujeres: 
    vTcl:DefineAlias "$site_3_0.lab57" "Label1_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 0 -textvariable lbl_cant_sex_f 
    vTcl:DefineAlias "$site_3_0.lab58" "lbl_cant_F" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.031 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo47 \
        -in $site_3_0 -x 0 -relx 0.115 -y 0 -rely 0.16 -width 0 \
        -relwidth 0.196 -height 0 -relheight 0.192 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.356 -y 0 -rely 0.16 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.461 -y 0 -rely 0.148 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.586 -y 0 -rely 0.16 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.264 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra54 \
        -in $site_3_0 -x 0 -relx 0.199 -y 0 -rely 2 -width 0 -relwidth 1 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    place $site_3_0.fra55 \
        -in $site_3_0 -x 0 -relx 0.147 -y 0 -rely 1.926 -width 0 -relwidth 1 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.461 -y 0 -rely 0.48 -width 0 \
        -relwidth 0.071 -height 0 -relheight 0.264 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.586 -y 0 -rely 0.48 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.264 -anchor nw \
        -bordermode ignore 
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Cantidad de Diputados por Bloque Politico:} 
    vTcl:DefineAlias "$top.lab59" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab60 \
        -font TkDefaultFont -foreground black -text {Buscador de Diputados} \
        -background $vTcl(actual_gui_bg) -height 165 -width 950 
    vTcl:DefineAlias "$top.lab60" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab60
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Diputado ID:} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label1_8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent62" "entry_dip_id" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command buscar_diputados_por_id \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Buscar 
    vTcl:DefineAlias "$site_3_0.but63" "btn_buscar_id" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Nombre Completo:} 
    vTcl:DefineAlias "$site_3_0.lab64" "Label1_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Provincia: 
    vTcl:DefineAlias "$site_3_0.lab65" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Cantidad de Viajes:} 
    vTcl:DefineAlias "$site_3_0.lab66" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_nomb_id 
    vTcl:DefineAlias "$site_3_0.lab67" "lbl_cant_sex_m_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_prov_id 
    vTcl:DefineAlias "$site_3_0.lab68" "lblcantsexm_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text ----------- -textvariable lbl_cant_viajes_id 
    vTcl:DefineAlias "$site_3_0.lab69" "lblcantsexm_13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Bloque: 
    vTcl:DefineAlias "$site_3_0.lab70" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -textvariable lbl_bloque_id 
    vTcl:DefineAlias "$site_3_0.lab71" "lbl_bloque" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Inicio: 
    vTcl:DefineAlias "$site_3_0.lab73" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -textvariable lbl_inicio_id 
    vTcl:DefineAlias "$site_3_0.lab74" "lbl_bloque_12" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.121 -width 0 \
        -relwidth 0.145 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 0 -relx 0.137 -y 0 -rely 0.121 -width 124 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 0 -relx 0.337 -y 0 -rely 0.121 -width 65 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.021 -y 0 -rely 0.303 -width 0 \
        -relwidth 0.135 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.053 -y 0 -rely 0.545 -width 0 \
        -relwidth 0.138 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.021 -y 0 -rely 0.788 -width 0 \
        -relwidth 0.138 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.179 -y 0 -rely 0.303 -width 0 \
        -relwidth 0.155 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.179 -y 0 -rely 0.545 -width 0 \
        -relwidth 0.156 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.179 -y 0 -rely 0.788 -width 0 \
        -relwidth 0.156 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.135 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.495 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.155 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.135 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx 0.495 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.156 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx 0.03 -y 0 -rely 0.089 -width 0 -relwidth 0.965 \
        -height 0 -relheight 0.211 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.081 -y 0 -rely 0.044 -width 0 -relwidth 0.302 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.fra56 \
        -in $top -x 0 -relx 0.03 -y 0 -rely 0.333 -width 0 -relwidth 0.965 \
        -height 0 -relheight 0.278 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.061 -y 0 -rely 0.333 -width 0 -relwidth 0.302 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.02 -y 0 -rely 0.622 -width 0 -relwidth 0.96 \
        -height 0 -relheight 0.367 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

