#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:43:55 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import json
with open("diputados.json", encoding = 'utf-8') as archivo:
    listaDiputados = json.load(archivo)
with open("viajes.json", encoding = 'utf-8') as archivo:
    listaViajes = json.load(archivo)

def set_Tk_var():
    global provincia
    provincia = tk.StringVar()
    global cantidad
    cantidad = tk.StringVar()
    global bloque
    bloque = tk.StringVar()
    global hombres
    hombres = tk.StringVar()
    global mujeres
    mujeres = tk.StringVar()
    global origen
    origen = tk.StringVar()
    global destino
    destino = tk.StringVar()
    global cantidadViajes
    cantidadViajes = tk.StringVar()
    global id
    id = tk.StringVar()
    global nombreCompleto
    nombreCompleto = tk.StringVar()
    global provinciaBD
    provinciaBD = tk.StringVar()
    global viajes
    viajes = tk.StringVar()
    global bloqueBD
    bloqueBD = tk.StringVar()
    global añoI
    añoI = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def buscar_diputados():
    print('parcial_support.buscar_diputados')
    sys.stdout.flush()

def calcuclar_provincia():
    global w, cantidad
    provincia = w.txtProvincia.get()
    indice = 0
    PROVINCIA = provincia.upper()
    for diputado in listaDiputados:
        if diputado[str(listaDiputados.index(diputado) + 1)]["diputado_distrito"] == PROVINCIA:
            indice += 1
    cantidad.set(indice)

def calcular_bloque():
    global w, hombres, mujeres
    bloque = w.txtBloque.get()
    fem = 0
    masc = 0
    BLOQUE = bloque.upper()
    for diputado in listaDiputados:
        if diputado[str(listaDiputados.index(diputado)+1)]["diputado_bloque"] == BLOQUE and diputado[str(listaDiputados.index(diputado) + 1)]["diputado_genero"] == "F":
            fem += 1
        elif diputado[str(listaDiputados.index(diputado)+1)]["diputado_bloque"] == BLOQUE and diputado[str(listaDiputados.index(diputado) + 1)]["diputado_genero"] == "M":
            masc += 1
    hombres.set(masc)
    mujeres.set(fem)

def calcular_viajes():
    global w, hombres, mujeres
    origen = w.txtOrigen.get()
    destino = w.txtDestino.get()
    fem = 0
    masc = 0
    ORIGEN = origen.upper()
    DESTINO = destino.upper()
    for viaje in listaViajes:
        if diputado[str(listaDiputados.index(diputado) + 1)]["diputado_bloque"] == BLOQUE and \
                diputado[str(listaDiputados.index(diputado) + 1)]["diputado_genero"] == "F":
            fem += 1
        elif diputado[str(listaDiputados.index(diputado) + 1)]["diputado_bloque"] == BLOQUE and \
                diputado[str(listaDiputados.index(diputado) + 1)]["diputado_genero"] == "M":
            masc += 1
    hombres.set(masc)
    mujeres.set(fem)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import parcial
    parcial.vp_start_gui()




