#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 05:36:35 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SistemaParcial_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    SistemaParcial_support.set_Tk_var()
    top = Toplevel1 (root)
    SistemaParcial_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    SistemaParcial_support.set_Tk_var()
    top = Toplevel1 (w)
    SistemaParcial_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Arial} -size 10"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("784x489+312+96")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("Camara de Diputados de la Nacion")
        top.configure(background="#d9d9d9")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.013, rely=0.0, relheight=0.209
                , relwidth=0.969)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Cantidad de Diputados por Provincia''')
        self.Labelframe1.configure(background="#d9d9d9")

        self.calc_PorProv = ttk.Button(self.Labelframe1)
        self.calc_PorProv.place(relx=0.474, rely=0.48, height=25, width=166
                , bordermode='ignore')
        self.calc_PorProv.configure(command=SistemaParcial_support.calc_PorProv)
        self.calc_PorProv.configure(takefocus="")
        self.calc_PorProv.configure(text='''Calcular''')

        self.entryProv01 = tk.Entry(self.Labelframe1)
        self.entryProv01.place(relx=0.25, rely=0.48, height=20, relwidth=0.203
                , bordermode='ignore')
        self.entryProv01.configure(background="white")
        self.entryProv01.configure(disabledforeground="#a3a3a3")
        self.entryProv01.configure(font="TkFixedFont")
        self.entryProv01.configure(foreground="#000000")
        self.entryProv01.configure(insertbackground="black")
        self.entryProv01.configure(textvariable=SistemaParcial_support.entryProv01)

        self.lbl01_01 = tk.Label(self.Labelframe1)
        self.lbl01_01.place(relx=0.105, rely=0.48, height=20, width=96
                , bordermode='ignore')
        self.lbl01_01.configure(background="#d9d9d9")
        self.lbl01_01.configure(disabledforeground="#a3a3a3")
        self.lbl01_01.configure(font=font9)
        self.lbl01_01.configure(foreground="#000000")
        self.lbl01_01.configure(text='''Ingrese Provincia''')

        self.lbl01_02 = tk.Label(self.Labelframe1)
        self.lbl01_02.place(relx=0.711, rely=0.48, height=20, width=54
                , bordermode='ignore')
        self.lbl01_02.configure(background="#d9d9d9")
        self.lbl01_02.configure(disabledforeground="#a3a3a3")
        self.lbl01_02.configure(font=font9)
        self.lbl01_02.configure(foreground="#000000")
        self.lbl01_02.configure(text='''Cantidad''')

        self.lbl01_Cant = tk.Label(self.Labelframe1)
        self.lbl01_Cant.place(relx=0.789, rely=0.48, height=20, width=104
                , bordermode='ignore')
        self.lbl01_Cant.configure(background="#d9d9d9")
        self.lbl01_Cant.configure(disabledforeground="#a3a3a3")
        self.lbl01_Cant.configure(foreground="#000000")
        self.lbl01_Cant.configure(relief="ridge")
        self.lbl01_Cant.configure(textvariable=SistemaParcial_support.lbl01_Cant)

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.013, rely=0.219, relheight=0.209
                , relwidth=0.968)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Cantidad de Diputados por Bloque Politico''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")

        self.calc_PorBloq = ttk.Button(self.Labelframe2)
        self.calc_PorBloq.place(relx=0.474, rely=0.48, height=25, width=166
                , bordermode='ignore')
        self.calc_PorBloq.configure(command=SistemaParcial_support.calc_PorBloq)
        self.calc_PorBloq.configure(takefocus="")
        self.calc_PorBloq.configure(text='''Calcular''')

        self.entryBloq01 = tk.Entry(self.Labelframe2)
        self.entryBloq01.place(relx=0.25, rely=0.49, height=20, relwidth=0.203
                , bordermode='ignore')
        self.entryBloq01.configure(background="white")
        self.entryBloq01.configure(disabledforeground="#a3a3a3")
        self.entryBloq01.configure(font="TkFixedFont")
        self.entryBloq01.configure(foreground="#000000")
        self.entryBloq01.configure(highlightbackground="#d9d9d9")
        self.entryBloq01.configure(highlightcolor="black")
        self.entryBloq01.configure(insertbackground="black")
        self.entryBloq01.configure(selectbackground="#c4c4c4")
        self.entryBloq01.configure(selectforeground="black")
        self.entryBloq01.configure(textvariable=SistemaParcial_support.entryBloq01)

        self.lbl02_1 = tk.Label(self.Labelframe2)
        self.lbl02_1.place(relx=0.119, rely=0.48, height=20, width=86
                , bordermode='ignore')
        self.lbl02_1.configure(activebackground="#f9f9f9")
        self.lbl02_1.configure(activeforeground="black")
        self.lbl02_1.configure(background="#d9d9d9")
        self.lbl02_1.configure(disabledforeground="#a3a3a3")
        self.lbl02_1.configure(font="-family {Arial} -size 10")
        self.lbl02_1.configure(foreground="#000000")
        self.lbl02_1.configure(highlightbackground="#d9d9d9")
        self.lbl02_1.configure(highlightcolor="black")
        self.lbl02_1.configure(text='''Ingrese Bloque''')

        self.lbl02_2 = tk.Label(self.Labelframe2)
        self.lbl02_2.place(relx=0.711, rely=0.284, height=21, width=54
                , bordermode='ignore')
        self.lbl02_2.configure(activebackground="#f9f9f9")
        self.lbl02_2.configure(activeforeground="black")
        self.lbl02_2.configure(background="#d9d9d9")
        self.lbl02_2.configure(disabledforeground="#a3a3a3")
        self.lbl02_2.configure(font="-family {Arial} -size 10")
        self.lbl02_2.configure(foreground="#000000")
        self.lbl02_2.configure(highlightbackground="#d9d9d9")
        self.lbl02_2.configure(highlightcolor="black")
        self.lbl02_2.configure(text='''Hombre''')

        self.lbl02_hombre = tk.Label(self.Labelframe2)
        self.lbl02_hombre.place(relx=0.791, rely=0.284, height=21, width=104
                , bordermode='ignore')
        self.lbl02_hombre.configure(activebackground="#f9f9f9")
        self.lbl02_hombre.configure(activeforeground="black")
        self.lbl02_hombre.configure(background="#d9d9d9")
        self.lbl02_hombre.configure(disabledforeground="#a3a3a3")
        self.lbl02_hombre.configure(foreground="#000000")
        self.lbl02_hombre.configure(highlightbackground="#d9d9d9")
        self.lbl02_hombre.configure(highlightcolor="black")
        self.lbl02_hombre.configure(relief="ridge")
        self.lbl02_hombre.configure(textvariable=SistemaParcial_support.lbl02_hombre)

        self.lbl02_3 = tk.Label(self.Labelframe2)
        self.lbl02_3.place(relx=0.738, rely=0.569, height=21, width=34
                , bordermode='ignore')
        self.lbl02_3.configure(activebackground="#f9f9f9")
        self.lbl02_3.configure(activeforeground="black")
        self.lbl02_3.configure(background="#d9d9d9")
        self.lbl02_3.configure(disabledforeground="#a3a3a3")
        self.lbl02_3.configure(font="-family {Arial} -size 10")
        self.lbl02_3.configure(foreground="#000000")
        self.lbl02_3.configure(highlightbackground="#d9d9d9")
        self.lbl02_3.configure(highlightcolor="black")
        self.lbl02_3.configure(text='''Mujer''')

        self.lbl02_mujer = tk.Label(self.Labelframe2)
        self.lbl02_mujer.place(relx=0.791, rely=0.588, height=20, width=104
                , bordermode='ignore')
        self.lbl02_mujer.configure(activebackground="#f9f9f9")
        self.lbl02_mujer.configure(activeforeground="black")
        self.lbl02_mujer.configure(background="#d9d9d9")
        self.lbl02_mujer.configure(disabledforeground="#a3a3a3")
        self.lbl02_mujer.configure(foreground="#000000")
        self.lbl02_mujer.configure(highlightbackground="#d9d9d9")
        self.lbl02_mujer.configure(highlightcolor="black")
        self.lbl02_mujer.configure(relief="ridge")
        self.lbl02_mujer.configure(textvariable=SistemaParcial_support.lbl02_mujer)

        self.Labelframe3 = tk.LabelFrame(top)
        self.Labelframe3.place(relx=0.013, rely=0.44, relheight=0.231
                , relwidth=0.968)
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Cantidad de Viajes''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")

        self.calc_Cantviajes = ttk.Button(self.Labelframe3)
        self.calc_Cantviajes.place(relx=0.474, rely=0.381, height=25, width=166
                , bordermode='ignore')
        self.calc_Cantviajes.configure(command=SistemaParcial_support.calc_Cantviajes)
        self.calc_Cantviajes.configure(takefocus="")
        self.calc_Cantviajes.configure(text='''Calcular''')

        self.entryProvOri = tk.Entry(self.Labelframe3)
        self.entryProvOri.place(relx=0.25, rely=0.283, height=20, relwidth=0.203
                , bordermode='ignore')
        self.entryProvOri.configure(background="white")
        self.entryProvOri.configure(disabledforeground="#a3a3a3")
        self.entryProvOri.configure(font="TkFixedFont")
        self.entryProvOri.configure(foreground="#000000")
        self.entryProvOri.configure(highlightbackground="#d9d9d9")
        self.entryProvOri.configure(highlightcolor="black")
        self.entryProvOri.configure(insertbackground="black")
        self.entryProvOri.configure(selectbackground="#c4c4c4")
        self.entryProvOri.configure(selectforeground="black")
        self.entryProvOri.configure(textvariable=SistemaParcial_support.entryProvOri)

        self.lbl03_1 = tk.Label(self.Labelframe3)
        self.lbl03_1.place(relx=0.026, rely=0.283, height=22, width=166
                , bordermode='ignore')
        self.lbl03_1.configure(activebackground="#f9f9f9")
        self.lbl03_1.configure(activeforeground="black")
        self.lbl03_1.configure(background="#d9d9d9")
        self.lbl03_1.configure(disabledforeground="#a3a3a3")
        self.lbl03_1.configure(font="-family {Arial} -size 10")
        self.lbl03_1.configure(foreground="#000000")
        self.lbl03_1.configure(highlightbackground="#d9d9d9")
        self.lbl03_1.configure(highlightcolor="black")
        self.lbl03_1.configure(text='''Ingrese Provincia de Origen''')

        self.lbl03_3 = tk.Label(self.Labelframe3)
        self.lbl03_3.place(relx=0.711, rely=0.381, height=22, width=54
                , bordermode='ignore')
        self.lbl03_3.configure(activebackground="#f9f9f9")
        self.lbl03_3.configure(activeforeground="black")
        self.lbl03_3.configure(background="#d9d9d9")
        self.lbl03_3.configure(disabledforeground="#a3a3a3")
        self.lbl03_3.configure(font="-family {Arial} -size 10")
        self.lbl03_3.configure(foreground="#000000")
        self.lbl03_3.configure(highlightbackground="#d9d9d9")
        self.lbl03_3.configure(highlightcolor="black")
        self.lbl03_3.configure(text='''Cantidad''')

        self.lbl03_CantViajes = tk.Label(self.Labelframe3)
        self.lbl03_CantViajes.place(relx=0.791, rely=0.381, height=22, width=104
                , bordermode='ignore')
        self.lbl03_CantViajes.configure(activebackground="#f9f9f9")
        self.lbl03_CantViajes.configure(activeforeground="black")
        self.lbl03_CantViajes.configure(background="#d9d9d9")
        self.lbl03_CantViajes.configure(disabledforeground="#a3a3a3")
        self.lbl03_CantViajes.configure(foreground="#000000")
        self.lbl03_CantViajes.configure(highlightbackground="#d9d9d9")
        self.lbl03_CantViajes.configure(highlightcolor="black")
        self.lbl03_CantViajes.configure(relief="ridge")
        self.lbl03_CantViajes.configure(textvariable=SistemaParcial_support.lbl03_CantViajes)

        self.lbl03_2 = tk.Label(self.Labelframe3)
        self.lbl03_2.place(relx=0.026, rely=0.566, height=22, width=166
                , bordermode='ignore')
        self.lbl03_2.configure(activebackground="#f9f9f9")
        self.lbl03_2.configure(activeforeground="black")
        self.lbl03_2.configure(background="#d9d9d9")
        self.lbl03_2.configure(disabledforeground="#a3a3a3")
        self.lbl03_2.configure(font="-family {Arial} -size 10")
        self.lbl03_2.configure(foreground="#000000")
        self.lbl03_2.configure(highlightbackground="#d9d9d9")
        self.lbl03_2.configure(highlightcolor="black")
        self.lbl03_2.configure(text='''Ingrese Provincia de Destino''')

        self.entryProvDst = tk.Entry(self.Labelframe3)
        self.entryProvDst.place(relx=0.25, rely=0.566, height=20, relwidth=0.203
                , bordermode='ignore')
        self.entryProvDst.configure(background="white")
        self.entryProvDst.configure(disabledforeground="#a3a3a3")
        self.entryProvDst.configure(font="TkFixedFont")
        self.entryProvDst.configure(foreground="#000000")
        self.entryProvDst.configure(highlightbackground="#d9d9d9")
        self.entryProvDst.configure(highlightcolor="black")
        self.entryProvDst.configure(insertbackground="black")
        self.entryProvDst.configure(selectbackground="#c4c4c4")
        self.entryProvDst.configure(selectforeground="black")
        self.entryProvDst.configure(textvariable=SistemaParcial_support.entryProvDst)

        self.Labelframe4 = tk.LabelFrame(top)
        self.Labelframe4.place(relx=0.013, rely=0.675, relheight=0.317
                , relwidth=0.968)
        self.Labelframe4.configure(relief='groove')
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Buscador de Diputados''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")

        self.btn_buscar_Id = ttk.Button(self.Labelframe4)
        self.btn_buscar_Id.place(relx=0.54, rely=0.129, height=25, width=166
                , bordermode='ignore')
        self.btn_buscar_Id.configure(command=SistemaParcial_support.buscar_ID)
        self.btn_buscar_Id.configure(takefocus="")
        self.btn_buscar_Id.configure(text='''Calcular''')

        self.entryProvIDDip = tk.Entry(self.Labelframe4)
        self.entryProvIDDip.place(relx=0.29, rely=0.129, height=20
                , relwidth=0.203, bordermode='ignore')
        self.entryProvIDDip.configure(background="white")
        self.entryProvIDDip.configure(disabledforeground="#a3a3a3")
        self.entryProvIDDip.configure(font="TkFixedFont")
        self.entryProvIDDip.configure(foreground="#000000")
        self.entryProvIDDip.configure(highlightbackground="#d9d9d9")
        self.entryProvIDDip.configure(highlightcolor="black")
        self.entryProvIDDip.configure(insertbackground="black")
        self.entryProvIDDip.configure(selectbackground="#c4c4c4")
        self.entryProvIDDip.configure(selectforeground="black")
        self.entryProvIDDip.configure(textvariable=SistemaParcial_support.entryProvIDDip)

        self.lbl04_1 = tk.Label(self.Labelframe4)
        self.lbl04_1.place(relx=0.171, rely=0.129, height=16, width=86
                , bordermode='ignore')
        self.lbl04_1.configure(activebackground="#f9f9f9")
        self.lbl04_1.configure(activeforeground="black")
        self.lbl04_1.configure(background="#d9d9d9")
        self.lbl04_1.configure(disabledforeground="#a3a3a3")
        self.lbl04_1.configure(font="-family {Arial} -size 10")
        self.lbl04_1.configure(foreground="#000000")
        self.lbl04_1.configure(highlightbackground="#d9d9d9")
        self.lbl04_1.configure(highlightcolor="black")
        self.lbl04_1.configure(text='''ID de Diputado''')

        self.lbl04_2 = tk.Label(self.Labelframe4)
        self.lbl04_2.place(relx=0.184, rely=0.387, height=16, width=56
                , bordermode='ignore')
        self.lbl04_2.configure(activebackground="#f9f9f9")
        self.lbl04_2.configure(activeforeground="black")
        self.lbl04_2.configure(background="#d9d9d9")
        self.lbl04_2.configure(disabledforeground="#a3a3a3")
        self.lbl04_2.configure(font="-family {Arial} -size 10")
        self.lbl04_2.configure(foreground="#000000")
        self.lbl04_2.configure(highlightbackground="#d9d9d9")
        self.lbl04_2.configure(highlightcolor="black")
        self.lbl04_2.configure(text='''Nombre''')

        self.lbl04_3 = tk.Label(self.Labelframe4)
        self.lbl04_3.place(relx=0.184, rely=0.581, height=16, width=56
                , bordermode='ignore')
        self.lbl04_3.configure(activebackground="#f9f9f9")
        self.lbl04_3.configure(activeforeground="black")
        self.lbl04_3.configure(background="#d9d9d9")
        self.lbl04_3.configure(disabledforeground="#a3a3a3")
        self.lbl04_3.configure(font="-family {Arial} -size 10")
        self.lbl04_3.configure(foreground="#000000")
        self.lbl04_3.configure(highlightbackground="#d9d9d9")
        self.lbl04_3.configure(highlightcolor="black")
        self.lbl04_3.configure(text='''Provincia''')

        self.lbl04_4 = tk.Label(self.Labelframe4)
        self.lbl04_4.place(relx=0.184, rely=0.774, height=16, width=56
                , bordermode='ignore')
        self.lbl04_4.configure(activebackground="#f9f9f9")
        self.lbl04_4.configure(activeforeground="black")
        self.lbl04_4.configure(background="#d9d9d9")
        self.lbl04_4.configure(disabledforeground="#a3a3a3")
        self.lbl04_4.configure(font="-family {Arial} -size 10")
        self.lbl04_4.configure(foreground="#000000")
        self.lbl04_4.configure(highlightbackground="#d9d9d9")
        self.lbl04_4.configure(highlightcolor="black")
        self.lbl04_4.configure(text='''Cantidad''')

        self.lbl_nom04 = tk.Label(self.Labelframe4)
        self.lbl_nom04.place(relx=0.264, rely=0.387, height=22, width=176
                , bordermode='ignore')
        self.lbl_nom04.configure(background="#d9d9d9")
        self.lbl_nom04.configure(disabledforeground="#a3a3a3")
        self.lbl_nom04.configure(foreground="#000000")
        self.lbl_nom04.configure(relief="ridge")
        self.lbl_nom04.configure(textvariable=SistemaParcial_support.lbl_nom04)

        self.lbl_prov04 = tk.Label(self.Labelframe4)
        self.lbl_prov04.place(relx=0.264, rely=0.581, height=22, width=176
                , bordermode='ignore')
        self.lbl_prov04.configure(activebackground="#f9f9f9")
        self.lbl_prov04.configure(activeforeground="black")
        self.lbl_prov04.configure(background="#d9d9d9")
        self.lbl_prov04.configure(disabledforeground="#a3a3a3")
        self.lbl_prov04.configure(foreground="#000000")
        self.lbl_prov04.configure(highlightbackground="#d9d9d9")
        self.lbl_prov04.configure(highlightcolor="black")
        self.lbl_prov04.configure(relief="ridge")
        self.lbl_prov04.configure(textvariable=SistemaParcial_support.lbl_prov04)

        self.lbl_canti = tk.Label(self.Labelframe4)
        self.lbl_canti.place(relx=0.264, rely=0.774, height=22, width=176
                , bordermode='ignore')
        self.lbl_canti.configure(activebackground="#f9f9f9")
        self.lbl_canti.configure(activeforeground="black")
        self.lbl_canti.configure(background="#d9d9d9")
        self.lbl_canti.configure(disabledforeground="#a3a3a3")
        self.lbl_canti.configure(foreground="#000000")
        self.lbl_canti.configure(highlightbackground="#d9d9d9")
        self.lbl_canti.configure(highlightcolor="black")
        self.lbl_canti.configure(relief="ridge")
        self.lbl_canti.configure(textvariable=SistemaParcial_support.lbl_canti)

        self.lbl04_5 = tk.Label(self.Labelframe4)
        self.lbl04_5.place(relx=0.553, rely=0.387, height=16, width=46
                , bordermode='ignore')
        self.lbl04_5.configure(activebackground="#f9f9f9")
        self.lbl04_5.configure(activeforeground="black")
        self.lbl04_5.configure(background="#d9d9d9")
        self.lbl04_5.configure(disabledforeground="#a3a3a3")
        self.lbl04_5.configure(font="-family {Arial} -size 10")
        self.lbl04_5.configure(foreground="#000000")
        self.lbl04_5.configure(highlightbackground="#d9d9d9")
        self.lbl04_5.configure(highlightcolor="black")
        self.lbl04_5.configure(text='''Bloque''')

        self.lbl04_6 = tk.Label(self.Labelframe4)
        self.lbl04_6.place(relx=0.54, rely=0.581, height=16, width=56
                , bordermode='ignore')
        self.lbl04_6.configure(activebackground="#f9f9f9")
        self.lbl04_6.configure(activeforeground="black")
        self.lbl04_6.configure(background="#d9d9d9")
        self.lbl04_6.configure(disabledforeground="#a3a3a3")
        self.lbl04_6.configure(font="-family {Arial} -size 10")
        self.lbl04_6.configure(foreground="#000000")
        self.lbl04_6.configure(highlightbackground="#d9d9d9")
        self.lbl04_6.configure(highlightcolor="black")
        self.lbl04_6.configure(text='''Año Inicio''')

        self.lbl_bloque = tk.Label(self.Labelframe4)
        self.lbl_bloque.place(relx=0.619, rely=0.387, height=22, width=176
                , bordermode='ignore')
        self.lbl_bloque.configure(activebackground="#f9f9f9")
        self.lbl_bloque.configure(activeforeground="black")
        self.lbl_bloque.configure(background="#d9d9d9")
        self.lbl_bloque.configure(disabledforeground="#a3a3a3")
        self.lbl_bloque.configure(foreground="#000000")
        self.lbl_bloque.configure(highlightbackground="#d9d9d9")
        self.lbl_bloque.configure(highlightcolor="black")
        self.lbl_bloque.configure(relief="ridge")
        self.lbl_bloque.configure(textvariable=SistemaParcial_support.lbl_bloque)

        self.lbl_año = tk.Label(self.Labelframe4)
        self.lbl_año.place(relx=0.619, rely=0.581, height=22, width=176
                , bordermode='ignore')
        self.lbl_año.configure(activebackground="#f9f9f9")
        self.lbl_año.configure(activeforeground="black")
        self.lbl_año.configure(background="#d9d9d9")
        self.lbl_año.configure(disabledforeground="#a3a3a3")
        self.lbl_año.configure(foreground="#000000")
        self.lbl_año.configure(highlightbackground="#d9d9d9")
        self.lbl_año.configure(highlightcolor="black")
        self.lbl_año.configure(relief="ridge")
        self.lbl_año.configure(textvariable=SistemaParcial_support.lbl_año)

if __name__ == '__main__':
    vp_start_gui()





