#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 03:58:20 PM -03  platform: Windows NT
#    May 27, 2020 04:29:23 PM -03  platform: Windows NT

import sys
import json
from tkinter import messagebox
from decimal import Decimal

with open('covid19.json', encoding = 'utf-8') as file:
    lstPaises = json.load(file)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entry_dia
    entry_dia = tk.StringVar()
    global lbl_conf
    lbl_conf = tk.StringVar()
    lbl_conf.set('')
    global lbl01_recup
    lbl01_recup = tk.StringVar()
    lbl01_recup.set('Label')
    global lbl01_fall
    lbl01_fall = tk.StringVar()
    lbl01_fall.set('Label')
    global lbl02_conf
    lbl02_conf = tk.StringVar()
    lbl02_conf.set('Label')
    global lbl02_fall
    lbl02_fall = tk.StringVar()
    lbl02_fall.set('Label')
    global lbl02_recup
    lbl02_recup = tk.StringVar()
    lbl02_recup.set('Label')
    global lbl03_conf
    lbl03_conf = tk.StringVar()
    lbl03_conf.set('Label')
    global lbl03_fall
    lbl03_fall = tk.StringVar()
    lbl03_fall.set('Label')
    global lbl03_recup
    lbl03_recup = tk.StringVar()
    lbl03_recup.set('Label')
    global lbl04_conf
    lbl04_conf = tk.StringVar()
    lbl04_conf.set('Label')
    global lbl04_fall
    lbl04_fall = tk.StringVar()
    lbl04_fall.set('Label')
    global lbl04_recup
    lbl04_recup = tk.StringVar()
    lbl04_recup.set('Label')
    global lbl_pais
    lbl_pais = tk.StringVar()
    lbl_pais.set('')
    global lbl_cant
    lbl_cant = tk.StringVar()
    lbl_cant.set('')
    global entry_pais
    entry_pais = tk.StringVar()
    global lbl_cantConf
    lbl_cantConf = tk.StringVar()
    lbl_cantConf.set('')
    global lbl_cantFall
    lbl_cantFall = tk.StringVar()
    lbl_cantFall.set('')
    global lbl_cantRecup
    lbl_cantRecup = tk.StringVar()
    lbl_cantRecup.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    topo()

def topo():
    pais01 = "Argentina"
    pais02 = "Paraguay"
    pais03 = "Uruguay"
    pais04 = "Brazil"
    for Pais in lstPaises:
        if pais01 == Pais['pais']:
            confirmados = Pais['confirmados']
            fallecidos = Pais['muertos']
            recuperados = Pais['recuperados']
            lbl_conf.set(confirmados)
            lbl01_fall.set(fallecidos)
            lbl01_recup.set(recuperados)
        elif pais02 == Pais['pais']:
            confirmados = Pais['confirmados']
            fallecidos = Pais['muertos']
            recuperados = Pais['recuperados']
            lbl02_conf.set(confirmados)
            lbl02_fall.set(fallecidos)
            lbl02_recup.set(recuperados)
        elif pais03 == Pais['pais']:
            confirmados = Pais['confirmados']
            fallecidos = Pais['muertos']
            recuperados = Pais['recuperados']
            lbl03_conf.set(confirmados)
            lbl03_fall.set(fallecidos)
            lbl03_recup.set(recuperados)
        elif pais04 == Pais['pais']:
            confirmados = Pais['confirmados']
            fallecidos = Pais['muertos']
            recuperados = Pais['recuperados']
            lbl04_conf.set(confirmados)
            lbl04_fall.set(fallecidos)
            lbl04_recup.set(recuperados)

def Buscar():
    Pais = entry_pais.get()
    unPais = []
    unaFecha = []
    for Paises in lstPaises:
        if entry_pais.get() == Paises['pais']:
            unPais.append(Paises)
    for dia in unPais:
        if entry_dia.get() == dia['dia']:
            confirmados = dia['confirmados']
            fallecidos = dia['muertos']
            recuperados = dia['recuperados']
            unaFecha.append(dia)

    lbl_cantConf.set(confirmados)
    lbl_cantFall.set(fallecidos)
    lbl_cantRecup.set(recuperados)




def Buscar_Pais():
    conteo = 0
    Pais = []
    for Paises in lstPaises:
        if Paises['pais'] in lstPaises:
            conteo += 1
    lbl_pais.set(Pais)
    lbl_cant.set(conteo)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import SistemaCOVID
    SistemaCOVID.vp_start_gui()






