#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:46:52 PM -03  platform: Windows NT

import sys
import json
from tkinter import messagebox
from decimal import Decimal

with open('diputados.json', encoding = 'utf-8') as file:
    lstDiputados = json.load(file)

with open('viajes.json', encoding = 'utf-8') as file:
    lstViajes = json.load(file)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entryProv01
    entryProv01 = tk.StringVar()
    global entryBloq01
    entryBloq01 = tk.StringVar()
    global lbl01_Cant
    lbl01_Cant = tk.StringVar()
    lbl01_Cant.set('')
    global lbl_canti
    lbl_canti = tk.StringVar()
    lbl_canti.set('')
    global lbl02_hombre
    lbl02_hombre = tk.StringVar()
    lbl02_hombre.set('')
    global lbl02_mujer
    lbl02_mujer = tk.StringVar()
    lbl02_mujer.set('')
    global entryProvOri
    entryProvOri = tk.StringVar()
    global lbl03_CantViajes
    lbl03_CantViajes = tk.StringVar()
    lbl03_CantViajes.set('')
    global entryProvDst
    entryProvDst = tk.StringVar()
    global entryProvIDDip
    entryProvIDDip = tk.StringVar()
    global lbl_nom04
    lbl_nom04 = tk.StringVar()
    lbl_nom04.set('')
    global lbl_prov04
    lbl_prov04 = tk.StringVar()
    lbl_prov04.set('')
    global lbl_bloque
    lbl_bloque = tk.StringVar()
    lbl_bloque.set('')
    global lbl_año
    lbl_año = tk.StringVar()
    lbl_año.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def buscar_ID():
    listaDet = []
    for detalles in lstDiputados:
        for values in detalles.values():
            listaDet.append(values)
    for honorable in listaDet:
        if entryProvIDDip.get() == honorable['\ufeffdiputado_id']:
            print(honorable)
            nombre = str(honorable['diputado_nombre']) + " " + str(honorable['diputado_apellido'])
            provincia = honorable['diputado_distrito']
            bloque = honorable['diputado_bloque']
            año = honorable['bloque_inicio']
            lbl_nom04.set(nombre)
            lbl_prov04.set(provincia)
            lbl_bloque.set(bloque)
            lbl_año.set(año)
    cantidad = 0
    lista = []
    for viajes in lstViajes:
        for values in viajes.values():
            lista.append(values)
    for viajes in lista:
        if entryProvIDDip.get() == viajes['\ufeffPersona_id']:
            cantidad += 1
            lbl_canti.set(cantidad)








def calc_Cantviajes():
    cantidad = 0
    lista = []
    for viajes in lstViajes:
        for values in viajes.values():
            lista.append(values)
    for viajes in lista:
        if entryProvOri.get() == viajes['Origen_ciudad'] and entryProvDst.get() == viajes['Destino_ciudad']:
            cantidad += 1
    lbl03_CantViajes.set(cantidad)



def calc_PorBloq():
    hombre = "M"
    contarH = 0
    mujer = "F"
    contarM = 0
    listaBloq = []
    for diputados in lstDiputados:
        for values in diputados.values():
            listaBloq.append(values)
    for tipo in listaBloq:
        if entryBloq01.get() == tipo['diputado_bloque'] and tipo['diputado_genero'] == hombre:
                contarH += 1
        elif entryBloq01.get() == tipo['diputado_bloque'] and tipo['diputado_genero'] == mujer:
                 contarM += 1
    lbl02_hombre.set(contarH)
    lbl02_mujer.set(contarM)


def calc_PorProv():
    conteo = 0
    listaProv = []
    for diputados in lstDiputados:
        for values in diputados.values():
            listaProv.append(values)
    for origen in listaProv:
        if entryProv01.get() == origen['diputado_distrito']:
            conteo += 1
    lbl01_Cant.set(conteo)






def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import SistemaParcial
    SistemaParcial.vp_start_gui()

