#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Jun 01, 2020 03:32:33 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 948x725+242+91
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3364 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab44 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cantidad de Diputados por Provincia } 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 95 -width 935 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab46 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Cantidad 
    vTcl:DefineAlias "$site_3_0.lab46" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calcant \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_cant -width 184 
    vTcl:DefineAlias "$site_3_0.ent48" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cantidad 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 154 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.316 -width 0 \
        -relwidth 0.09 -height 0 -relheight 0.368 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.364 -y 0 -rely 0.316 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.107 -y 0 -rely 0.421 -width 184 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.524 -y 0 -rely 0.316 -width 0 \
        -relwidth 0.09 -height 0 -relheight 0.368 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.631 -y 0 -rely 0.316 -width 154 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab51 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cantidad de Diputados por Bloque Politico} 
    vTcl:DefineAlias "$top.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra52 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 94 -width 936 
    vTcl:DefineAlias "$top.fra52" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab53 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Bloque 
    vTcl:DefineAlias "$site_3_0.lab53" "Label4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_bloque -width 174 
    vTcl:DefineAlias "$site_3_0.ent54" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calbloque \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but55" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Hombre 
    vTcl:DefineAlias "$site_3_0.lab57" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Mujeres 
    vTcl:DefineAlias "$site_3_0.lab58" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent59 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_homb -width 124 
    vTcl:DefineAlias "$site_3_0.ent59" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent60 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_mujeres -width 124 
    vTcl:DefineAlias "$site_3_0.ent60" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.021 -y 0 -rely 0.319 -width 0 \
        -relwidth 0.058 -height 0 -relheight 0.436 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 0 -relx 0.107 -y 0 -rely 0.426 -width 174 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 0 -relx 0.363 -y 0 -rely 0.319 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.513 -y 0 -rely 0.106 -width 0 \
        -relwidth 0.09 -height 0 -relheight 0.223 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.534 -y 0 -rely 0.532 -width 0 \
        -relwidth 0.047 -height 0 -relheight 0.223 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 0 -relx 0.609 -y 0 -rely 0.106 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 0 -relx 0.609 -y 0 -rely 0.532 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra61 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 104 -width 936 
    vTcl:DefineAlias "$top.fra61" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra61
    label $site_3_0.lab63 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Origen 
    vTcl:DefineAlias "$site_3_0.lab63" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Destino 
    vTcl:DefineAlias "$site_3_0.lab64" "Label9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent65 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_orig -width 154 
    vTcl:DefineAlias "$site_3_0.ent65" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent66 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_dest -width 154 
    vTcl:DefineAlias "$site_3_0.ent66" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calviaje \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but67" "Button3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Cantidad 
    vTcl:DefineAlias "$site_3_0.lab68" "Label10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent69 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_cantviaje -width 134 
    vTcl:DefineAlias "$site_3_0.ent69" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.021 -y 0 -rely 0.096 -width 0 \
        -relwidth 0.079 -height 0 -relheight 0.202 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.032 -y 0 -rely 0.577 -width 0 \
        -relwidth 0.058 -height 0 -relheight 0.202 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 0 -relx 0.107 -y 0 -rely 0.096 -width 154 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 0 -relx 0.107 -y 0 -rely 0.577 -width 154 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 0 -relx 0.363 -y 0 -rely 0.291 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.537 -y 0 -rely 0.388 -width 0 \
        -relwidth 0.058 -height 0 -relheight 0.204 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 0 -relx 0.623 -y 0 -rely 0.388 -width 134 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab62 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cantidad de Viajes} 
    vTcl:DefineAlias "$top.lab62" "Label7" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra70 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 235 -width 927 
    vTcl:DefineAlias "$top.fra70" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra70
    label $site_3_0.lab72 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Diputado ID} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Nombre Completo} 
    vTcl:DefineAlias "$site_3_0.lab73" "Label13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Provincia 
    vTcl:DefineAlias "$site_3_0.lab74" "Label14" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab75 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cantidad de Viajes} 
    vTcl:DefineAlias "$site_3_0.lab75" "Label15" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent76 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_ID -width 124 
    vTcl:DefineAlias "$site_3_0.ent76" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent77 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable entry_nombcomp -width 124 
    vTcl:DefineAlias "$site_3_0.ent77" "Entry9_2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent78 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable entry_prov -width 124 
    vTcl:DefineAlias "$site_3_0.ent78" "Entry9_3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent79 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable entry_cantviajes -width 124 
    vTcl:DefineAlias "$site_3_0.ent79" "Entry9_4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but80 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calbusdiputados \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Calcular 
    vTcl:DefineAlias "$site_3_0.but80" "Button4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Bloque 
    vTcl:DefineAlias "$site_3_0.lab81" "Label16" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab82 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Año de Inicio} 
    vTcl:DefineAlias "$site_3_0.lab82" "Label17" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent83 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_Bloque -width 154 
    vTcl:DefineAlias "$site_3_0.ent83" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent84 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable entry_añoinicio -width 154 
    vTcl:DefineAlias "$site_3_0.ent84" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.065 -y 0 -rely 0.085 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.255 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.426 -width 0 \
        -relwidth 0.123 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 0 -relx 0.032 -y 0 -rely 0.638 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent76 \
        -in $site_3_0 -x 0 -relx 0.183 -y 0 -rely 0.085 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 0 -relx 0.183 -y 0 -rely 0.255 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent78 \
        -in $site_3_0 -x 0 -relx 0.183 -y 0 -rely 0.426 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent79 \
        -in $site_3_0 -x 0 -relx 0.183 -y 0 -rely 0.638 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but80 \
        -in $site_3_0 -x 0 -relx 0.398 -y 0 -rely 0.085 -width 107 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 0 -relx 0.581 -y 0 -rely 0.213 -width 0 \
        -relwidth 0.1 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -relx 0.581 -y 0 -rely 0.383 -width 0 \
        -relwidth 0.081 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent83 \
        -in $site_3_0 -x 0 -relx 0.689 -y 0 -rely 0.213 -width 154 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent84 \
        -in $site_3_0 -x 0 -relx 0.689 -y 0 -rely 0.383 -width 154 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab71 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Buscador de Diputados} 
    vTcl:DefineAlias "$top.lab71" "Label11" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.014 -width 0 -relwidth 0.289 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.055 -width 0 -relwidth 0.986 \
        -height 0 -relheight 0.131 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.042 -y 0 -rely 0.207 -width 0 -relwidth 0.257 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.248 -width 0 -relwidth 0.987 \
        -height 0 -relheight 0.13 -anchor nw -bordermode ignore 
    place $top.fra61 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.441 -width 0 -relwidth 0.982 \
        -height 0 -relheight 0.142 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx -0.011 -y 0 -rely 0.386 -width 0 -relwidth 0.226 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.fra70 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.634 -width 0 -relwidth 0.98 \
        -height 0 -relheight 0.324 -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.593 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

