#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 04:20:40 PM -03  platform: Windows NT

import sys
import json
with open('diputados.json',encoding ='utf-8') as archivoDip:
    lstdiputados = json.load(archivoDip)
with open('viajes.json',encoding ='utf-8') as archivoviaj:
    lstviajes = json.load(archivoviaj)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entry_Provincia1
    entry_Provincia1 = tk.StringVar()
    global entry_cantidad
    entry_cantidad = tk.StringVar()
    global entry_bloque
    entry_bloque = tk.StringVar()
    global entry_homb
    entry_homb = tk.StringVar()
    global entry_mujeres
    entry_mujeres = tk.StringVar()
    global entry_orig
    entry_orig = tk.StringVar()
    global entry_dest
    entry_dest = tk.StringVar()
    global entry_cantviaje
    entry_cantviaje = tk.StringVar()
    global entry_ID
    entry_ID = tk.StringVar()
    global entry_nombcomp
    entry_nombcomp = tk.StringVar()
    global entry_prov
    entry_prov = tk.StringVar()
    global entry_cantviajes
    entry_cantviajes = tk.StringVar()
    global entry_Bloque
    entry_Bloque = tk.StringVar()
    global entry_añoinicio
    entry_añoinicio = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def calbloque():
    print('ProgI_Parcial_support.calbloque')
    sys.stdout.flush()




def calbusdiputados():
    print('ProgI_Parcial_support.calbusdiputados')
    sys.stdout.flush()

def calcant():
    print('ProgI_Parcial_support.calcant')
    sys.stdout.flush()
    prov=0
    provin=entry_Provincia1.get().upper()
    for info in lstdiputados:
        if info [str(lstdiputados.index(info)+1)]["diputado_distrito"] == provin:
            prov+=1
    entry_cantidad.set(prov)

def calviaje():
    print('ProgI_Parcial_support.calviaje')
    sys.stdout.flush()
    viajes=0
    origen=str(entry_orig.get().upper())
    destino=str(entry_dest.get().upper())
    for info in lstviajes:
        if (info[str(lstviajes.index(info)+1)]["Origen_ciudad"] == origen and info[str(lstviajes.index(info)+1)]["Destino_ciudad"]) == destino:
            viajes+=1
            print(viaje)
    entry_cantviaje.set(viajes)





def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ProgI_Parcial
    ProgI_Parcial.vp_start_gui()




