#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:35:42 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DiputadosIrala_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    DiputadosIrala_support.set_Tk_var()
    top = Toplevel1 (root)
    DiputadosIrala_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    DiputadosIrala_support.set_Tk_var()
    top = Toplevel1 (w)
    DiputadosIrala_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 11 -weight bold"
        font9 = "-family {Segoe UI} -size 10 -underline 1"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1165x848+457+120")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Diputados Argentina - Programacion II")
        top.configure(background="#d9d9d9")

        self.lblProvincia = tk.Label(top)
        self.lblProvincia.place(relx=0.026, rely=0.106, height=24, width=103)
        self.lblProvincia.configure(background="#d9d9d9")
        self.lblProvincia.configure(cursor="fleur")
        self.lblProvincia.configure(disabledforeground="#a3a3a3")
        self.lblProvincia.configure(font=font9)
        self.lblProvincia.configure(foreground="#000000")
        self.lblProvincia.configure(text='''Provincia:''')

        self.entProvincia = tk.Entry(top)
        self.entProvincia.place(relx=0.112, rely=0.106, height=24
                , relwidth=0.132)
        self.entProvincia.configure(background="white")
        self.entProvincia.configure(disabledforeground="#a3a3a3")
        self.entProvincia.configure(font="TkFixedFont")
        self.entProvincia.configure(foreground="#000000")
        self.entProvincia.configure(insertbackground="black")
        self.entProvincia.configure(textvariable=DiputadosIrala_support.provincia)

        self.btnCalcular = tk.Button(top)
        self.btnCalcular.place(relx=0.326, rely=0.094, height=33, width=156)
        self.btnCalcular.configure(activebackground="#ececec")
        self.btnCalcular.configure(activeforeground="#000000")
        self.btnCalcular.configure(background="#d9d9d9")
        self.btnCalcular.configure(command=DiputadosIrala_support.diputadosXProvincia)
        self.btnCalcular.configure(disabledforeground="#a3a3a3")
        self.btnCalcular.configure(foreground="#000000")
        self.btnCalcular.configure(highlightbackground="#d9d9d9")
        self.btnCalcular.configure(highlightcolor="black")
        self.btnCalcular.configure(pady="0")
        self.btnCalcular.configure(text='''Calcular''')

        self.lblCantidad = tk.Label(top)
        self.lblCantidad.place(relx=0.567, rely=0.106, height=23, width=113)
        self.lblCantidad.configure(activebackground="#f9f9f9")
        self.lblCantidad.configure(activeforeground="black")
        self.lblCantidad.configure(background="#d9d9d9")
        self.lblCantidad.configure(disabledforeground="#a3a3a3")
        self.lblCantidad.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblCantidad.configure(foreground="#000000")
        self.lblCantidad.configure(highlightbackground="#d9d9d9")
        self.lblCantidad.configure(highlightcolor="black")
        self.lblCantidad.configure(text='''Cantidad:''')

        self.lblMostrarCantidad = tk.Label(top)
        self.lblMostrarCantidad.place(relx=0.67, rely=0.106, height=26
                , width=142)
        self.lblMostrarCantidad.configure(background="#d9d9d9")
        self.lblMostrarCantidad.configure(disabledforeground="#a3a3a3")
        self.lblMostrarCantidad.configure(foreground="#000000")
        self.lblMostrarCantidad.configure(text='''0''')

        self.lblTitulo1 = tk.Label(top)
        self.lblTitulo1.place(relx=0.034, rely=0.024, height=27, width=361)
        self.lblTitulo1.configure(background="#d9d9d9")
        self.lblTitulo1.configure(disabledforeground="#a3a3a3")
        self.lblTitulo1.configure(font=font10)
        self.lblTitulo1.configure(foreground="#000000")
        self.lblTitulo1.configure(text='''Cantidad de diputados por provincia''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.0, rely=0.059, relwidth=0.995)
        self.TSeparator1.configure(cursor="fleur")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.lblTitulo2 = tk.Label(top)
        self.lblTitulo2.place(relx=0.043, rely=0.212, height=27, width=361)
        self.lblTitulo2.configure(activebackground="#f9f9f9")
        self.lblTitulo2.configure(activeforeground="black")
        self.lblTitulo2.configure(background="#d9d9d9")
        self.lblTitulo2.configure(disabledforeground="#a3a3a3")
        self.lblTitulo2.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblTitulo2.configure(foreground="#000000")
        self.lblTitulo2.configure(highlightbackground="#d9d9d9")
        self.lblTitulo2.configure(highlightcolor="black")
        self.lblTitulo2.configure(text='''Cantidad de diputados por Bloque politico''')

        self.TSeparator1_3 = ttk.Separator(top)
        self.TSeparator1_3.place(relx=0.0, rely=0.259, relwidth=0.995)

        self.lblBloque = tk.Label(top)
        self.lblBloque.place(relx=0.026, rely=0.307, height=24, width=103)
        self.lblBloque.configure(activebackground="#f9f9f9")
        self.lblBloque.configure(activeforeground="black")
        self.lblBloque.configure(background="#d9d9d9")
        self.lblBloque.configure(disabledforeground="#a3a3a3")
        self.lblBloque.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblBloque.configure(foreground="#000000")
        self.lblBloque.configure(highlightbackground="#d9d9d9")
        self.lblBloque.configure(highlightcolor="black")
        self.lblBloque.configure(text='''Bloque:''')

        self.entBloque = tk.Entry(top)
        self.entBloque.place(relx=0.103, rely=0.307,height=24, relwidth=0.141)
        self.entBloque.configure(background="white")
        self.entBloque.configure(disabledforeground="#a3a3a3")
        self.entBloque.configure(font="TkFixedFont")
        self.entBloque.configure(foreground="#000000")
        self.entBloque.configure(highlightbackground="#d9d9d9")
        self.entBloque.configure(highlightcolor="black")
        self.entBloque.configure(insertbackground="black")
        self.entBloque.configure(selectbackground="#c4c4c4")
        self.entBloque.configure(selectforeground="black")
        self.entBloque.configure(textvariable=DiputadosIrala_support.bloque)

        self.btnCalcularBloque = tk.Button(top)
        self.btnCalcularBloque.place(relx=0.318, rely=0.295, height=33
                , width=166)
        self.btnCalcularBloque.configure(activebackground="#ececec")
        self.btnCalcularBloque.configure(activeforeground="#000000")
        self.btnCalcularBloque.configure(background="#d9d9d9")
        self.btnCalcularBloque.configure(command=DiputadosIrala_support.diputadosXBloque)
        self.btnCalcularBloque.configure(disabledforeground="#a3a3a3")
        self.btnCalcularBloque.configure(foreground="#000000")
        self.btnCalcularBloque.configure(highlightbackground="#d9d9d9")
        self.btnCalcularBloque.configure(highlightcolor="black")
        self.btnCalcularBloque.configure(pady="0")
        self.btnCalcularBloque.configure(text='''Calcular''')

        self.lblHombres = tk.Label(top)
        self.lblHombres.place(relx=0.575, rely=0.295, height=23, width=113)
        self.lblHombres.configure(activebackground="#f9f9f9")
        self.lblHombres.configure(activeforeground="black")
        self.lblHombres.configure(background="#d9d9d9")
        self.lblHombres.configure(cursor="fleur")
        self.lblHombres.configure(disabledforeground="#a3a3a3")
        self.lblHombres.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblHombres.configure(foreground="#000000")
        self.lblHombres.configure(highlightbackground="#d9d9d9")
        self.lblHombres.configure(highlightcolor="black")
        self.lblHombres.configure(text='''Hombres:''')

        self.lblMujeres = tk.Label(top)
        self.lblMujeres.place(relx=0.575, rely=0.342, height=23, width=113)
        self.lblMujeres.configure(activebackground="#f9f9f9")
        self.lblMujeres.configure(activeforeground="black")
        self.lblMujeres.configure(background="#d9d9d9")
        self.lblMujeres.configure(disabledforeground="#a3a3a3")
        self.lblMujeres.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblMujeres.configure(foreground="#000000")
        self.lblMujeres.configure(highlightbackground="#d9d9d9")
        self.lblMujeres.configure(highlightcolor="black")
        self.lblMujeres.configure(text='''Mujeres:''')

        self.lblMostrarHombres = tk.Label(top)
        self.lblMostrarHombres.place(relx=0.678, rely=0.295, height=26
                , width=142)
        self.lblMostrarHombres.configure(activebackground="#f9f9f9")
        self.lblMostrarHombres.configure(activeforeground="black")
        self.lblMostrarHombres.configure(background="#d9d9d9")
        self.lblMostrarHombres.configure(disabledforeground="#a3a3a3")
        self.lblMostrarHombres.configure(foreground="#000000")
        self.lblMostrarHombres.configure(highlightbackground="#d9d9d9")
        self.lblMostrarHombres.configure(highlightcolor="black")
        self.lblMostrarHombres.configure(text='''0''')

        self.lblMostrarMujeres = tk.Label(top)
        self.lblMostrarMujeres.place(relx=0.678, rely=0.342, height=26
                , width=142)
        self.lblMostrarMujeres.configure(activebackground="#f9f9f9")
        self.lblMostrarMujeres.configure(activeforeground="black")
        self.lblMostrarMujeres.configure(background="#d9d9d9")
        self.lblMostrarMujeres.configure(disabledforeground="#a3a3a3")
        self.lblMostrarMujeres.configure(foreground="#000000")
        self.lblMostrarMujeres.configure(highlightbackground="#d9d9d9")
        self.lblMostrarMujeres.configure(highlightcolor="black")
        self.lblMostrarMujeres.configure(text='''0''')

        self.lblTitulo3 = tk.Label(top)
        self.lblTitulo3.place(relx=0.017, rely=0.413, height=27, width=201)
        self.lblTitulo3.configure(activebackground="#f9f9f9")
        self.lblTitulo3.configure(activeforeground="black")
        self.lblTitulo3.configure(background="#d9d9d9")
        self.lblTitulo3.configure(disabledforeground="#a3a3a3")
        self.lblTitulo3.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblTitulo3.configure(foreground="#000000")
        self.lblTitulo3.configure(highlightbackground="#d9d9d9")
        self.lblTitulo3.configure(highlightcolor="black")
        self.lblTitulo3.configure(text='''Cantidad de Viajes''')

        self.TSeparator1_4 = ttk.Separator(top)
        self.TSeparator1_4.place(relx=0.0, rely=0.46, relwidth=0.995)

        self.lblOrigen = tk.Label(top)
        self.lblOrigen.place(relx=0.034, rely=0.495, height=24, width=102)
        self.lblOrigen.configure(activebackground="#f9f9f9")
        self.lblOrigen.configure(activeforeground="black")
        self.lblOrigen.configure(background="#d9d9d9")
        self.lblOrigen.configure(disabledforeground="#a3a3a3")
        self.lblOrigen.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblOrigen.configure(foreground="#000000")
        self.lblOrigen.configure(highlightbackground="#d9d9d9")
        self.lblOrigen.configure(highlightcolor="black")
        self.lblOrigen.configure(text='''Origen:''')

        self.lblDestino = tk.Label(top)
        self.lblDestino.place(relx=0.034, rely=0.554, height=24, width=102)
        self.lblDestino.configure(activebackground="#f9f9f9")
        self.lblDestino.configure(activeforeground="black")
        self.lblDestino.configure(background="#d9d9d9")
        self.lblDestino.configure(disabledforeground="#a3a3a3")
        self.lblDestino.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblDestino.configure(foreground="#000000")
        self.lblDestino.configure(highlightbackground="#d9d9d9")
        self.lblDestino.configure(highlightcolor="black")
        self.lblDestino.configure(text='''Destino:''')

        self.entProvinciaOrigen = tk.Entry(top)
        self.entProvinciaOrigen.place(relx=0.129, rely=0.495, height=24
                , relwidth=0.132)
        self.entProvinciaOrigen.configure(background="white")
        self.entProvinciaOrigen.configure(disabledforeground="#a3a3a3")
        self.entProvinciaOrigen.configure(font="TkFixedFont")
        self.entProvinciaOrigen.configure(foreground="#000000")
        self.entProvinciaOrigen.configure(highlightbackground="#d9d9d9")
        self.entProvinciaOrigen.configure(highlightcolor="black")
        self.entProvinciaOrigen.configure(insertbackground="black")
        self.entProvinciaOrigen.configure(selectbackground="#c4c4c4")
        self.entProvinciaOrigen.configure(selectforeground="black")
        self.entProvinciaOrigen.configure(textvariable=DiputadosIrala_support.provinciaOrigen)

        self.entProvinciaDestino = tk.Entry(top)
        self.entProvinciaDestino.place(relx=0.129, rely=0.554, height=24
                , relwidth=0.132)
        self.entProvinciaDestino.configure(background="white")
        self.entProvinciaDestino.configure(disabledforeground="#a3a3a3")
        self.entProvinciaDestino.configure(font="TkFixedFont")
        self.entProvinciaDestino.configure(foreground="#000000")
        self.entProvinciaDestino.configure(highlightbackground="#d9d9d9")
        self.entProvinciaDestino.configure(highlightcolor="black")
        self.entProvinciaDestino.configure(insertbackground="black")
        self.entProvinciaDestino.configure(selectbackground="#c4c4c4")
        self.entProvinciaDestino.configure(selectforeground="black")
        self.entProvinciaDestino.configure(textvariable=DiputadosIrala_support.provinciaDestino)

        self.btnCalcularViaje = tk.Button(top)
        self.btnCalcularViaje.place(relx=0.318, rely=0.519, height=33, width=166)

        self.btnCalcularViaje.configure(activebackground="#ececec")
        self.btnCalcularViaje.configure(activeforeground="#000000")
        self.btnCalcularViaje.configure(background="#d9d9d9")
        self.btnCalcularViaje.configure(command=DiputadosIrala_support.cantidadViajes)
        self.btnCalcularViaje.configure(disabledforeground="#a3a3a3")
        self.btnCalcularViaje.configure(foreground="#000000")
        self.btnCalcularViaje.configure(highlightbackground="#d9d9d9")
        self.btnCalcularViaje.configure(highlightcolor="black")
        self.btnCalcularViaje.configure(pady="0")
        self.btnCalcularViaje.configure(text='''Calcular''')

        self.lblCantidad_10 = tk.Label(top)
        self.lblCantidad_10.place(relx=0.584, rely=0.531, height=23, width=113)
        self.lblCantidad_10.configure(activebackground="#f9f9f9")
        self.lblCantidad_10.configure(activeforeground="black")
        self.lblCantidad_10.configure(background="#d9d9d9")
        self.lblCantidad_10.configure(disabledforeground="#a3a3a3")
        self.lblCantidad_10.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblCantidad_10.configure(foreground="#000000")
        self.lblCantidad_10.configure(highlightbackground="#d9d9d9")
        self.lblCantidad_10.configure(highlightcolor="black")
        self.lblCantidad_10.configure(text='''Cantidad:''')

        self.lblMostrarViajes = tk.Label(top)
        self.lblMostrarViajes.place(relx=0.704, rely=0.531, height=27, width=142)

        self.lblMostrarViajes.configure(activebackground="#f9f9f9")
        self.lblMostrarViajes.configure(activeforeground="black")
        self.lblMostrarViajes.configure(background="#d9d9d9")
        self.lblMostrarViajes.configure(disabledforeground="#a3a3a3")
        self.lblMostrarViajes.configure(foreground="#000000")
        self.lblMostrarViajes.configure(highlightbackground="#d9d9d9")
        self.lblMostrarViajes.configure(highlightcolor="black")
        self.lblMostrarViajes.configure(text='''0''')

        self.lblTitulo4 = tk.Label(top)
        self.lblTitulo4.place(relx=0.009, rely=0.613, height=27, width=202)
        self.lblTitulo4.configure(activebackground="#f9f9f9")
        self.lblTitulo4.configure(activeforeground="black")
        self.lblTitulo4.configure(background="#d9d9d9")
        self.lblTitulo4.configure(disabledforeground="#a3a3a3")
        self.lblTitulo4.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblTitulo4.configure(foreground="#000000")
        self.lblTitulo4.configure(highlightbackground="#d9d9d9")
        self.lblTitulo4.configure(highlightcolor="black")
        self.lblTitulo4.configure(text='''Buscador de Diputados''')

        self.TSeparator1_5 = ttk.Separator(top)
        self.TSeparator1_5.place(relx=0.0, rely=0.672, relwidth=0.995)

        self.lblDiputadoID = tk.Label(top)
        self.lblDiputadoID.place(relx=0.215, rely=0.696, height=24, width=112)
        self.lblDiputadoID.configure(activebackground="#f9f9f9")
        self.lblDiputadoID.configure(activeforeground="black")
        self.lblDiputadoID.configure(background="#d9d9d9")
        self.lblDiputadoID.configure(disabledforeground="#a3a3a3")
        self.lblDiputadoID.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblDiputadoID.configure(foreground="#000000")
        self.lblDiputadoID.configure(highlightbackground="#d9d9d9")
        self.lblDiputadoID.configure(highlightcolor="black")
        self.lblDiputadoID.configure(text='''Diputado ID:''')

        self.entDiputadoID = tk.Entry(top)
        self.entDiputadoID.place(relx=0.361, rely=0.696, height=24
                , relwidth=0.132)
        self.entDiputadoID.configure(background="white")
        self.entDiputadoID.configure(disabledforeground="#a3a3a3")
        self.entDiputadoID.configure(font="TkFixedFont")
        self.entDiputadoID.configure(foreground="#000000")
        self.entDiputadoID.configure(highlightbackground="#d9d9d9")
        self.entDiputadoID.configure(highlightcolor="black")
        self.entDiputadoID.configure(insertbackground="black")
        self.entDiputadoID.configure(selectbackground="#c4c4c4")
        self.entDiputadoID.configure(selectforeground="black")
        self.entDiputadoID.configure(textvariable=DiputadosIrala_support.diputadoID)

        self.btnBuscar = tk.Button(top)
        self.btnBuscar.place(relx=0.549, rely=0.696, height=33, width=166)
        self.btnBuscar.configure(activebackground="#ececec")
        self.btnBuscar.configure(activeforeground="#000000")
        self.btnBuscar.configure(background="#d9d9d9")
        self.btnBuscar.configure(command=DiputadosIrala_support.diputadoXID)
        self.btnBuscar.configure(disabledforeground="#a3a3a3")
        self.btnBuscar.configure(foreground="#000000")
        self.btnBuscar.configure(highlightbackground="#d9d9d9")
        self.btnBuscar.configure(highlightcolor="black")
        self.btnBuscar.configure(pady="0")
        self.btnBuscar.configure(text='''Buscar''')

        self.lblNombreCompleto = tk.Label(top)
        self.lblNombreCompleto.place(relx=0.017, rely=0.767, height=24
                , width=161)
        self.lblNombreCompleto.configure(activebackground="#f9f9f9")
        self.lblNombreCompleto.configure(activeforeground="black")
        self.lblNombreCompleto.configure(background="#d9d9d9")
        self.lblNombreCompleto.configure(disabledforeground="#a3a3a3")
        self.lblNombreCompleto.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblNombreCompleto.configure(foreground="#000000")
        self.lblNombreCompleto.configure(highlightbackground="#d9d9d9")
        self.lblNombreCompleto.configure(highlightcolor="black")
        self.lblNombreCompleto.configure(text='''Nombre Completo:''')

        self.lblProvincia_10 = tk.Label(top)
        self.lblProvincia_10.place(relx=0.009, rely=0.814, height=24, width=103)
        self.lblProvincia_10.configure(activebackground="#f9f9f9")
        self.lblProvincia_10.configure(activeforeground="black")
        self.lblProvincia_10.configure(background="#d9d9d9")
        self.lblProvincia_10.configure(disabledforeground="#a3a3a3")
        self.lblProvincia_10.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblProvincia_10.configure(foreground="#000000")
        self.lblProvincia_10.configure(highlightbackground="#d9d9d9")
        self.lblProvincia_10.configure(highlightcolor="black")
        self.lblProvincia_10.configure(text='''Provincia:''')

        self.lblCantidadViajess = tk.Label(top)
        self.lblCantidadViajess.place(relx=0.017, rely=0.861, height=24
                , width=163)
        self.lblCantidadViajess.configure(activebackground="#f9f9f9")
        self.lblCantidadViajess.configure(activeforeground="black")
        self.lblCantidadViajess.configure(background="#d9d9d9")
        self.lblCantidadViajess.configure(disabledforeground="#a3a3a3")
        self.lblCantidadViajess.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblCantidadViajess.configure(foreground="#000000")
        self.lblCantidadViajess.configure(highlightbackground="#d9d9d9")
        self.lblCantidadViajess.configure(highlightcolor="black")
        self.lblCantidadViajess.configure(text='''Cantidad de Viajes:''')

        self.lblCantViajesID = tk.Label(top)
        self.lblCantViajesID.place(relx=0.223, rely=0.861, height=26, width=142)
        self.lblCantViajesID.configure(activebackground="#f9f9f9")
        self.lblCantViajesID.configure(activeforeground="black")
        self.lblCantViajesID.configure(background="#d9d9d9")
        self.lblCantViajesID.configure(disabledforeground="#a3a3a3")
        self.lblCantViajesID.configure(foreground="#000000")
        self.lblCantViajesID.configure(highlightbackground="#d9d9d9")
        self.lblCantViajesID.configure(highlightcolor="black")
        self.lblCantViajesID.configure(text='''0''')

        self.lblMostrarNomCompleto = tk.Label(top)
        self.lblMostrarNomCompleto.place(relx=0.197, rely=0.767, height=28
                , width=208)
        self.lblMostrarNomCompleto.configure(background="#d9d9d9")
        self.lblMostrarNomCompleto.configure(disabledforeground="#a3a3a3")
        self.lblMostrarNomCompleto.configure(foreground="#000000")
        self.lblMostrarNomCompleto.configure(text='''-''')

        self.lblMostrarProvinciaID = tk.Label(top)
        self.lblMostrarProvinciaID.place(relx=0.197, rely=0.814, height=28
                , width=208)
        self.lblMostrarProvinciaID.configure(activebackground="#f9f9f9")
        self.lblMostrarProvinciaID.configure(activeforeground="black")
        self.lblMostrarProvinciaID.configure(background="#d9d9d9")
        self.lblMostrarProvinciaID.configure(disabledforeground="#a3a3a3")
        self.lblMostrarProvinciaID.configure(foreground="#000000")
        self.lblMostrarProvinciaID.configure(highlightbackground="#d9d9d9")
        self.lblMostrarProvinciaID.configure(highlightcolor="black")
        self.lblMostrarProvinciaID.configure(text='''-''')

        self.lblBloque_14 = tk.Label(top)
        self.lblBloque_14.place(relx=0.515, rely=0.767, height=23, width=102)
        self.lblBloque_14.configure(activebackground="#f9f9f9")
        self.lblBloque_14.configure(activeforeground="black")
        self.lblBloque_14.configure(background="#d9d9d9")
        self.lblBloque_14.configure(disabledforeground="#a3a3a3")
        self.lblBloque_14.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblBloque_14.configure(foreground="#000000")
        self.lblBloque_14.configure(highlightbackground="#d9d9d9")
        self.lblBloque_14.configure(highlightcolor="black")
        self.lblBloque_14.configure(text='''Bloque:''')

        self.lblAñoInicio = tk.Label(top)
        self.lblAñoInicio.place(relx=0.515, rely=0.837, height=24, width=102)
        self.lblAñoInicio.configure(activebackground="#f9f9f9")
        self.lblAñoInicio.configure(activeforeground="black")
        self.lblAñoInicio.configure(background="#d9d9d9")
        self.lblAñoInicio.configure(disabledforeground="#a3a3a3")
        self.lblAñoInicio.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.lblAñoInicio.configure(foreground="#000000")
        self.lblAñoInicio.configure(highlightbackground="#d9d9d9")
        self.lblAñoInicio.configure(highlightcolor="black")
        self.lblAñoInicio.configure(text='''Año Inicio:''')

        self.lblMostrarBloqueID = tk.Label(top)
        self.lblMostrarBloqueID.place(relx=0.635, rely=0.767, height=28
                , width=208)
        self.lblMostrarBloqueID.configure(activebackground="#f9f9f9")
        self.lblMostrarBloqueID.configure(activeforeground="black")
        self.lblMostrarBloqueID.configure(background="#d9d9d9")
        self.lblMostrarBloqueID.configure(disabledforeground="#a3a3a3")
        self.lblMostrarBloqueID.configure(foreground="#000000")
        self.lblMostrarBloqueID.configure(highlightbackground="#d9d9d9")
        self.lblMostrarBloqueID.configure(highlightcolor="black")
        self.lblMostrarBloqueID.configure(text='''-''')

        self.lblMostrarAñoInicio = tk.Label(top)
        self.lblMostrarAñoInicio.place(relx=0.635, rely=0.825, height=28
                , width=208)
        self.lblMostrarAñoInicio.configure(activebackground="#f9f9f9")
        self.lblMostrarAñoInicio.configure(activeforeground="black")
        self.lblMostrarAñoInicio.configure(background="#d9d9d9")
        self.lblMostrarAñoInicio.configure(disabledforeground="#a3a3a3")
        self.lblMostrarAñoInicio.configure(foreground="#000000")
        self.lblMostrarAñoInicio.configure(highlightbackground="#d9d9d9")
        self.lblMostrarAñoInicio.configure(highlightcolor="black")
        self.lblMostrarAñoInicio.configure(text='''-''')

if __name__ == '__main__':
    vp_start_gui()





