#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:35:47 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global provincia
    provincia = tk.StringVar()
    global bloque
    bloque = tk.StringVar()
    global provinciaOrigen
    provinciaOrigen = tk.StringVar()
    global provinciaDestino
    provinciaDestino = tk.StringVar()
    global diputadoID
    diputadoID = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def cantidadViajes():
    print('DiputadosIrala_support.cantidadViajes')
    sys.stdout.flush()

def diputadoXID():
    print('DiputadosIrala_support.diputadoXID')
    sys.stdout.flush()

def diputadosXBloque():
    print('DiputadosIrala_support.diputadosXBloque')
    sys.stdout.flush()

def diputadosXProvincia():
    print('DiputadosIrala_support.diputadosXProvincia')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import DiputadosIrala
    DiputadosIrala.vp_start_gui()




