#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 01, 2020 03:35:47 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global provincia
    provincia = tk.StringVar()
    global bloque
    bloque = tk.StringVar()
    global provinciaOrigen
    provinciaOrigen = tk.StringVar()
    global provinciaDestino
    provinciaDestino = tk.StringVar()
    global diputadoID
    diputadoID = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

import DIPUTADOS
import VIAJES

def cantidadViajes():
    lstViajes=VIAJES.getListaDatos()
    clave=0
    contViajes=0
    for unViaje in lstViajes:
        clave+=1
        if unViaje[str(clave)]["Origen_ciudad"]==provinciaOrigen.get() and unViaje[str(clave)]["Destino_ciudad"]==provinciaDestino.get():
            contViajes+=1
    w.lblMostrarViajes.configure(text=contViajes)

def diputadoXID():
    lstDiputados=DIPUTADOS.getListaDatos()
    clave=0
    for unDiputado in lstDiputados:
        clave+=1
        print(unDiputado[str(clave)]["diputado_id"])
        if unDiputado[str(clave)]["diputado_id"]==diputadoID.get():
            nombre=unDiputado[str(clave)]["diputado_nombre"]
            apellido=unDiputado[str(clave)]["diputado_apellido"]
            nombreCompleto=nombre+apellido
            w.lblMostrarNomCompleto.configure(text=nombreCompleto)

def diputadosXBloque():
    lstDiputados=DIPUTADOS.getListaDatos()
    clave=0
    contHombres=0
    contMujeres=0
    for unDiputado in lstDiputados:
        clave+=1
        if unDiputado[str(clave)]["diputado_bloque"]==bloque.get():
            if unDiputado[str(clave)]["diputado_genero"]=="M":
                contHombres+=1
            elif unDiputado[str(clave)]["diputado_genero"]=="F":
                contMujeres+=1
    w.lblMostrarHombres.configure(text=contHombres)
    w.lblMostrarMujeres.configure(text=contMujeres)

def diputadosXProvincia():
    lstDiputados=DIPUTADOS.getListaDatos()
    clave=0
    contDiputados=0
    for unDiputado in lstDiputados:
        clave+=1
        if unDiputado[str(clave)]["diputado_distrito"]==provincia.get():
            contDiputados+=1
    w.lblMostrarCantidad.configure(text=contDiputados)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import DiputadosIrala
    DiputadosIrala.vp_start_gui()



